/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/vinyl.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfTheme.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLed.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include "CalfVuMeter.hpp"
#include <calf/metadata.h>
#ifndef ENABLE_EXPERIMENTAL
#define ENABLE_EXPERIMENTAL 1
#endif
#include <calf/modules_dist.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLed;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfVuMeter;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class VinylUI : public UI, public CalfWidgetBase::Callback
{
public:
    VinylUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = vinyl_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 8, false);
            {
                auto c_2 = std::make_unique<CalfTableItem>(1, 7, false, 5, 5);
                auto* w_3 = new CalfLabel(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"), nullptr);
                fWidgets.emplace_back(w_3);
                fByIndex[_resolve("level_in")].push_back(w_3);
                c_2->add(std::make_unique<CalfWidgetItem>(w_3), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true});
                auto* w_4 = new CalfKnob(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                w_4->setShowLabels(false);
                fWidgets.emplace_back(w_4);
                fByIndex[_resolve("level_in")].push_back(w_4);
                c_2->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=1, .attachH=2});
                auto* w_5 = new CalfValue(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                fWidgets.emplace_back(w_5);
                fByIndex[_resolve("level_in")].push_back(w_5);
                c_2->add(std::make_unique<CalfWidgetItem>(w_5), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=3});
                auto* w_6 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Input level");
                fWidgets.emplace_back(w_6);
                c_2->add(std::make_unique<CalfWidgetItem>(w_6), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                auto* w_7 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inL")), _resolve("meter_inL"));
                w_7->setShowLabels(false);
                fWidgets.emplace_back(w_7);
                fByIndex[_resolve("meter_inL")].push_back(w_7);
                c_2->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                auto* w_8 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inR")), _resolve("meter_inR"));
                w_8->setShowLabels(false);
                fWidgets.emplace_back(w_8);
                fByIndex[_resolve("meter_inR")].push_back(w_8);
                c_2->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2});
                auto* w_9 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_9);
                fByIndex[_resolve("meter_outR")].push_back(w_9);
                c_2->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=3});
                auto* w_10 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_10);
                c_2->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                auto* w_11 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inL")), _resolve("clip_inL"));
                w_11->setShowLabels(false);
                fWidgets.emplace_back(w_11);
                fByIndex[_resolve("clip_inL")].push_back(w_11);
                c_2->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                auto* w_12 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inR")), _resolve("clip_inR"));
                w_12->setShowLabels(false);
                fWidgets.emplace_back(w_12);
                fByIndex[_resolve("clip_inR")].push_back(w_12);
                c_2->add(std::make_unique<CalfWidgetItem>(w_12), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=2});
                auto* w_13 = new CalfLabel(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"), nullptr);
                fWidgets.emplace_back(w_13);
                fByIndex[_resolve("bypass")].push_back(w_13);
                c_2->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=4});
                auto* w_14 = new CalfToggle(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"));
                w_14->setShowLabels(false);
                fWidgets.emplace_back(w_14);
                fByIndex[_resolve("bypass")].push_back(w_14);
                c_2->add(std::make_unique<CalfWidgetItem>(w_14), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .padX=10, .attachX=4, .attachY=1, .attachH=2});
                auto* w_15 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Output level");
                fWidgets.emplace_back(w_15);
                c_2->add(std::make_unique<CalfWidgetItem>(w_15), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5});
                auto* w_16 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outL")), _resolve("meter_outL"));
                w_16->setShowLabels(false);
                fWidgets.emplace_back(w_16);
                fByIndex[_resolve("meter_outL")].push_back(w_16);
                c_2->add(std::make_unique<CalfWidgetItem>(w_16), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=1});
                auto* w_17 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                w_17->setShowLabels(false);
                fWidgets.emplace_back(w_17);
                fByIndex[_resolve("meter_outR")].push_back(w_17);
                c_2->add(std::make_unique<CalfWidgetItem>(w_17), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=2});
                auto* w_18 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_18);
                fByIndex[_resolve("meter_outR")].push_back(w_18);
                c_2->add(std::make_unique<CalfWidgetItem>(w_18), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=3});
                auto* w_19 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_19);
                c_2->add(std::make_unique<CalfWidgetItem>(w_19), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6});
                auto* w_20 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outL")), _resolve("clip_outL"));
                w_20->setShowLabels(false);
                fWidgets.emplace_back(w_20);
                fByIndex[_resolve("clip_outL")].push_back(w_20);
                c_2->add(std::make_unique<CalfWidgetItem>(w_20), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=1});
                auto* w_21 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outR")), _resolve("clip_outR"));
                w_21->setShowLabels(false);
                fWidgets.emplace_back(w_21);
                fByIndex[_resolve("clip_outR")].push_back(w_21);
                c_2->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=2});
                auto* w_22 = new CalfLabel(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"), nullptr);
                fWidgets.emplace_back(w_22);
                fByIndex[_resolve("level_out")].push_back(w_22);
                c_2->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=8});
                auto* w_23 = new CalfKnob(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                w_23->setShowLabels(false);
                fWidgets.emplace_back(w_23);
                fByIndex[_resolve("level_out")].push_back(w_23);
                c_2->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=8, .attachY=1, .attachH=2});
                auto* w_24 = new CalfValue(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                fWidgets.emplace_back(w_24);
                fByIndex[_resolve("level_out")].push_back(w_24);
                c_2->add(std::make_unique<CalfWidgetItem>(w_24), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=8, .attachY=3});
                c_1->add(std::move(c_2), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=true});
            }
            {
                auto c_25 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 16, false);
                {
                    auto c_26 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 5, true);
                    {
                        auto c_27 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        auto* w_28 = new CalfToggle(this, *meta.get_param_props(_resolve("active0")), _resolve("active0"));
                        w_28->setShowLabels(false);
                        fWidgets.emplace_back(w_28);
                        fByIndex[_resolve("active0")].push_back(w_28);
                        c_27->add(std::make_unique<CalfWidgetItem>(w_28), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_29 = new CalfKnob(this, *meta.get_param_props(_resolve("gain0")), _resolve("gain0"));
                        w_29->setShowLabels(false);
                        fWidgets.emplace_back(w_29);
                        fByIndex[_resolve("gain0")].push_back(w_29);
                        c_27->add(std::make_unique<CalfWidgetItem>(w_29), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_30 = new CalfKnob(this, *meta.get_param_props(_resolve("pitch0")), _resolve("pitch0"));
                        w_30->setKnobSize(1);
                        w_30->setShowLabels(false);
                        fWidgets.emplace_back(w_30);
                        fByIndex[_resolve("pitch0")].push_back(w_30);
                        c_27->add(std::make_unique<CalfWidgetItem>(w_30), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_31 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Hum");
                        fWidgets.emplace_back(w_31);
                        c_27->add(std::make_unique<CalfWidgetItem>(w_31), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_27), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_32 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        auto* w_33 = new CalfToggle(this, *meta.get_param_props(_resolve("active1")), _resolve("active1"));
                        w_33->setShowLabels(false);
                        fWidgets.emplace_back(w_33);
                        fByIndex[_resolve("active1")].push_back(w_33);
                        c_32->add(std::make_unique<CalfWidgetItem>(w_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_34 = new CalfKnob(this, *meta.get_param_props(_resolve("gain1")), _resolve("gain1"));
                        w_34->setShowLabels(false);
                        fWidgets.emplace_back(w_34);
                        fByIndex[_resolve("gain1")].push_back(w_34);
                        c_32->add(std::make_unique<CalfWidgetItem>(w_34), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_35 = new CalfKnob(this, *meta.get_param_props(_resolve("pitch1")), _resolve("pitch1"));
                        w_35->setKnobSize(1);
                        w_35->setShowLabels(false);
                        fWidgets.emplace_back(w_35);
                        fByIndex[_resolve("pitch1")].push_back(w_35);
                        c_32->add(std::make_unique<CalfWidgetItem>(w_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_36 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Motor");
                        fWidgets.emplace_back(w_36);
                        c_32->add(std::make_unique<CalfWidgetItem>(w_36), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_37 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        auto* w_38 = new CalfToggle(this, *meta.get_param_props(_resolve("active2")), _resolve("active2"));
                        w_38->setShowLabels(false);
                        fWidgets.emplace_back(w_38);
                        fByIndex[_resolve("active2")].push_back(w_38);
                        c_37->add(std::make_unique<CalfWidgetItem>(w_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_39 = new CalfKnob(this, *meta.get_param_props(_resolve("gain2")), _resolve("gain2"));
                        w_39->setShowLabels(false);
                        fWidgets.emplace_back(w_39);
                        fByIndex[_resolve("gain2")].push_back(w_39);
                        c_37->add(std::make_unique<CalfWidgetItem>(w_39), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_40 = new CalfKnob(this, *meta.get_param_props(_resolve("pitch2")), _resolve("pitch2"));
                        w_40->setKnobSize(1);
                        w_40->setShowLabels(false);
                        fWidgets.emplace_back(w_40);
                        fByIndex[_resolve("pitch2")].push_back(w_40);
                        c_37->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_41 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Static");
                        fWidgets.emplace_back(w_41);
                        c_37->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_37), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_42 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        auto* w_43 = new CalfToggle(this, *meta.get_param_props(_resolve("active3")), _resolve("active3"));
                        w_43->setShowLabels(false);
                        fWidgets.emplace_back(w_43);
                        fByIndex[_resolve("active3")].push_back(w_43);
                        c_42->add(std::make_unique<CalfWidgetItem>(w_43), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_44 = new CalfKnob(this, *meta.get_param_props(_resolve("gain3")), _resolve("gain3"));
                        w_44->setShowLabels(false);
                        fWidgets.emplace_back(w_44);
                        fByIndex[_resolve("gain3")].push_back(w_44);
                        c_42->add(std::make_unique<CalfWidgetItem>(w_44), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_45 = new CalfKnob(this, *meta.get_param_props(_resolve("pitch3")), _resolve("pitch3"));
                        w_45->setKnobSize(1);
                        w_45->setShowLabels(false);
                        fWidgets.emplace_back(w_45);
                        fByIndex[_resolve("pitch3")].push_back(w_45);
                        c_42->add(std::make_unique<CalfWidgetItem>(w_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_46 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Noise");
                        fWidgets.emplace_back(w_46);
                        c_42->add(std::make_unique<CalfWidgetItem>(w_46), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_42), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_47 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        auto* w_48 = new CalfToggle(this, *meta.get_param_props(_resolve("active4")), _resolve("active4"));
                        w_48->setShowLabels(false);
                        fWidgets.emplace_back(w_48);
                        fByIndex[_resolve("active4")].push_back(w_48);
                        c_47->add(std::make_unique<CalfWidgetItem>(w_48), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_49 = new CalfKnob(this, *meta.get_param_props(_resolve("gain4")), _resolve("gain4"));
                        w_49->setShowLabels(false);
                        fWidgets.emplace_back(w_49);
                        fByIndex[_resolve("gain4")].push_back(w_49);
                        c_47->add(std::make_unique<CalfWidgetItem>(w_49), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_50 = new CalfKnob(this, *meta.get_param_props(_resolve("pitch4")), _resolve("pitch4"));
                        w_50->setKnobSize(1);
                        w_50->setShowLabels(false);
                        fWidgets.emplace_back(w_50);
                        fByIndex[_resolve("pitch4")].push_back(w_50);
                        c_47->add(std::make_unique<CalfWidgetItem>(w_50), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_51 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Rumble");
                        fWidgets.emplace_back(w_51);
                        c_47->add(std::make_unique<CalfWidgetItem>(w_51), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_47), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_52 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        auto* w_53 = new CalfToggle(this, *meta.get_param_props(_resolve("active5")), _resolve("active5"));
                        w_53->setShowLabels(false);
                        fWidgets.emplace_back(w_53);
                        fByIndex[_resolve("active5")].push_back(w_53);
                        c_52->add(std::make_unique<CalfWidgetItem>(w_53), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_54 = new CalfKnob(this, *meta.get_param_props(_resolve("gain5")), _resolve("gain5"));
                        w_54->setShowLabels(false);
                        fWidgets.emplace_back(w_54);
                        fByIndex[_resolve("gain5")].push_back(w_54);
                        c_52->add(std::make_unique<CalfWidgetItem>(w_54), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_55 = new CalfKnob(this, *meta.get_param_props(_resolve("pitch5")), _resolve("pitch5"));
                        w_55->setKnobSize(1);
                        w_55->setShowLabels(false);
                        fWidgets.emplace_back(w_55);
                        fByIndex[_resolve("pitch5")].push_back(w_55);
                        c_52->add(std::make_unique<CalfWidgetItem>(w_55), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_56 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Crackle");
                        fWidgets.emplace_back(w_56);
                        c_52->add(std::make_unique<CalfWidgetItem>(w_56), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_52), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_57 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        auto* w_58 = new CalfToggle(this, *meta.get_param_props(_resolve("active6")), _resolve("active6"));
                        w_58->setShowLabels(false);
                        fWidgets.emplace_back(w_58);
                        fByIndex[_resolve("active6")].push_back(w_58);
                        c_57->add(std::make_unique<CalfWidgetItem>(w_58), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_59 = new CalfKnob(this, *meta.get_param_props(_resolve("gain6")), _resolve("gain6"));
                        w_59->setShowLabels(false);
                        fWidgets.emplace_back(w_59);
                        fByIndex[_resolve("gain6")].push_back(w_59);
                        c_57->add(std::make_unique<CalfWidgetItem>(w_59), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_60 = new CalfKnob(this, *meta.get_param_props(_resolve("pitch6")), _resolve("pitch6"));
                        w_60->setKnobSize(1);
                        w_60->setShowLabels(false);
                        fWidgets.emplace_back(w_60);
                        fByIndex[_resolve("pitch6")].push_back(w_60);
                        c_57->add(std::make_unique<CalfWidgetItem>(w_60), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_61 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Crinkle");
                        fWidgets.emplace_back(w_61);
                        c_57->add(std::make_unique<CalfWidgetItem>(w_61), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_57), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_25->add(std::move(c_26), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_63 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    auto* w_64 = new CalfLineGraph(this, *meta.get_param_props(_resolve("freq")), _resolve("freq"), 240, 160);
                    fLineGraphs.push_back({ w_64, static_cast<int>(_resolve("freq")) });
                    w_64->setSize(static_cast<uint>(240), static_cast<uint>(160));
                    fWidgets.emplace_back(w_64);
                    fByIndex[_resolve("freq")].push_back(w_64);
                    c_63->add(std::make_unique<CalfWidgetItem>(w_64), CalfPacking{});
                    auto c_62 = std::make_unique<CalfFrameItem>("Frequency Response", std::move(c_63));
                    c_25->add(std::move(c_62), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_65 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_66 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_67 = new CalfLabel(this, *meta.get_param_props(_resolve("aging")), _resolve("aging"), nullptr);
                        fWidgets.emplace_back(w_67);
                        fByIndex[_resolve("aging")].push_back(w_67);
                        c_66->add(std::make_unique<CalfWidgetItem>(w_67), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_68 = new CalfKnob(this, *meta.get_param_props(_resolve("aging")), _resolve("aging"));
                        w_68->setKnobSize(3);
                        w_68->setShowLabels(false);
                        fWidgets.emplace_back(w_68);
                        fByIndex[_resolve("aging")].push_back(w_68);
                        c_66->add(std::make_unique<CalfWidgetItem>(w_68), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_69 = new CalfValue(this, *meta.get_param_props(_resolve("aging")), _resolve("aging"));
                        fWidgets.emplace_back(w_69);
                        fByIndex[_resolve("aging")].push_back(w_69);
                        c_66->add(std::make_unique<CalfWidgetItem>(w_69), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_65->add(std::move(c_66), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_70 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_71 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Color");
                        fWidgets.emplace_back(w_71);
                        c_70->add(std::make_unique<CalfWidgetItem>(w_71), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_72 = new CalfKnob(this, *meta.get_param_props(_resolve("freq")), _resolve("freq"));
                        w_72->setKnobSize(2);
                        w_72->setShowLabels(false);
                        fWidgets.emplace_back(w_72);
                        fByIndex[_resolve("freq")].push_back(w_72);
                        c_70->add(std::make_unique<CalfWidgetItem>(w_72), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_73 = new CalfValue(this, *meta.get_param_props(_resolve("freq")), _resolve("freq"));
                        fWidgets.emplace_back(w_73);
                        fByIndex[_resolve("freq")].push_back(w_73);
                        c_70->add(std::make_unique<CalfWidgetItem>(w_73), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_65->add(std::move(c_70), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_25->add(std::move(c_65), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_74 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_75 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_76 = new CalfLabel(this, *meta.get_param_props(_resolve("drone")), _resolve("drone"), nullptr);
                        fWidgets.emplace_back(w_76);
                        fByIndex[_resolve("drone")].push_back(w_76);
                        c_75->add(std::make_unique<CalfWidgetItem>(w_76), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_77 = new CalfKnob(this, *meta.get_param_props(_resolve("drone")), _resolve("drone"));
                        w_77->setKnobSize(3);
                        w_77->setShowLabels(false);
                        fWidgets.emplace_back(w_77);
                        fByIndex[_resolve("drone")].push_back(w_77);
                        c_75->add(std::make_unique<CalfWidgetItem>(w_77), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_78 = new CalfValue(this, *meta.get_param_props(_resolve("drone")), _resolve("drone"));
                        fWidgets.emplace_back(w_78);
                        fByIndex[_resolve("drone")].push_back(w_78);
                        c_75->add(std::make_unique<CalfWidgetItem>(w_78), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_74->add(std::move(c_75), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_79 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_80 = new CalfLabel(this, *meta.get_param_props(_resolve("speed")), _resolve("speed"), nullptr);
                        fWidgets.emplace_back(w_80);
                        fByIndex[_resolve("speed")].push_back(w_80);
                        c_79->add(std::make_unique<CalfWidgetItem>(w_80), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_81 = new CalfKnob(this, *meta.get_param_props(_resolve("speed")), _resolve("speed"));
                        w_81->setKnobSize(2);
                        w_81->setShowLabels(false);
                        fWidgets.emplace_back(w_81);
                        fByIndex[_resolve("speed")].push_back(w_81);
                        c_79->add(std::make_unique<CalfWidgetItem>(w_81), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        {
                            auto c_82 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, false);
                            auto* w_83 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                            fWidgets.emplace_back(w_83);
                            c_82->add(std::make_unique<CalfWidgetItem>(w_83), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_84 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                            fWidgets.emplace_back(w_84);
                            c_82->add(std::make_unique<CalfWidgetItem>(w_84), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_85 = new CalfValue(this, *meta.get_param_props(_resolve("speed")), _resolve("speed"));
                            fWidgets.emplace_back(w_85);
                            fByIndex[_resolve("speed")].push_back(w_85);
                            c_82->add(std::make_unique<CalfWidgetItem>(w_85), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_86 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "rpm");
                            fWidgets.emplace_back(w_86);
                            c_82->add(std::make_unique<CalfWidgetItem>(w_86), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_87 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                            fWidgets.emplace_back(w_87);
                            c_82->add(std::make_unique<CalfWidgetItem>(w_87), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_88 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                            fWidgets.emplace_back(w_88);
                            c_82->add(std::make_unique<CalfWidgetItem>(w_88), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_79->add(std::move(c_82), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        c_74->add(std::move(c_79), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_25->add(std::move(c_74), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_25), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);

        // Shadow module: same DSP class as the running plugin, instantiated
        // UI-side just so <line-graph> widgets can query line_graph_iface
        // synchronously during paint.
        fShadow = std::make_unique<calf_plugins::vinyl_audio_module>();
        fShadowParams.assign(Meta::param_count, 0.0f);
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            fShadowParams[i] = meta.get_param_props(static_cast<int>(i))->def_value;
            fShadow->params[i] = &fShadowParams[i];
        }
        fShadow->post_instantiate(48000);
        fShadow->set_sample_rate(48000);
        fShadow->params_changed();
        fShadow->activate();
        // Not every Calf module inherits line_graph_iface — only the
        // ones that draw curves do. Cross-cast at runtime; null means
        // "this plugin has no curves to draw, paint the placeholder".
        const calf_plugins::line_graph_iface* _lg =
            dynamic_cast<const calf_plugins::line_graph_iface*>(fShadow.get());
        if (_lg) {
            for (auto& g : fLineGraphs)
                g.w->setGraphSource(_lg, g.idx);
        }
    }

protected:
    void onNanoDisplay() override
    {
        const float w = static_cast<float>(getWidth());
        const float h = static_cast<float>(getHeight());

        // Themed background: stretch the GTK Calf_Default plugin
        // background across the whole UI. Falls back to the dark flat
        // fill if the asset failed to decode.
        beginPath();
        rect(0, 0, w, h);
        NanoImage* _bg = fTheme.image("background_plugin.png");
        if (_bg && _bg->isValid()) {
            fillPaint(imagePattern(0, 0, w, h, 0.0f, *_bg, 1.0f));
        } else {
            fillColor(Color(0.12f, 0.12f, 0.14f));
        }
        fill();

        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it != fByIndex.end())
            for (auto* w : it->second) w->setValue(value, /*notify=*/false);
        if (fShadow && index < fShadowParams.size()) {
            fShadowParams[index] = value;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
        if (fShadow && w->getParamIndex() < fShadowParams.size()) {
            fShadowParams[w->getParamIndex()] = v;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    // No-op for WANT_STATE plugins (Monosynth, Organ, FluidSynth, Wavetable).
    // Codegen UIs don't yet visualise state keys (organ presets, wavetable
    // data, SF2 path, modmatrix rows); hand-written subclasses can override.
    // DPF only declares stateChanged when the plugin opts in, so guard.
#if DISTRHO_PLUGIN_WANT_STATE
    void stateChanged(const char* /*key*/, const char* /*value*/) override {}
#endif

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    CalfTheme                                         fTheme{*this};
    std::unique_ptr<calf_plugins::vinyl_audio_module> fShadow;
    std::vector<float>                            fShadowParams;
    struct LineGraphRef { CalfLineGraph* w; int idx; };
    std::vector<LineGraphRef>                     fLineGraphs;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(VinylUI)
};

UI* createUI() { return new VinylUI(); }

END_NAMESPACE_DISTRHO
