/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/eq12.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfComboBox.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLed.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include "CalfVuMeter.hpp"
#include <calf/metadata.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfComboBox;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLed;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfVuMeter;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class Eq12UI : public UI, public CalfWidgetBase::Callback
{
public:
    Eq12UI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = equalizer12band_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
            {
                auto c_2 = std::make_unique<CalfTableItem>(1, 7, false, 5, 5);
                auto* w_3 = new CalfLabel(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"), nullptr);
                fWidgets.emplace_back(w_3);
                fByIndex[_resolve("level_in")].push_back(w_3);
                c_2->add(std::make_unique<CalfWidgetItem>(w_3), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true});
                auto* w_4 = new CalfKnob(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                w_4->setShowLabels(false);
                fWidgets.emplace_back(w_4);
                fByIndex[_resolve("level_in")].push_back(w_4);
                c_2->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=1, .attachH=2});
                auto* w_5 = new CalfValue(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                fWidgets.emplace_back(w_5);
                fByIndex[_resolve("level_in")].push_back(w_5);
                c_2->add(std::make_unique<CalfWidgetItem>(w_5), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=3});
                auto* w_6 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Input level");
                fWidgets.emplace_back(w_6);
                c_2->add(std::make_unique<CalfWidgetItem>(w_6), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                auto* w_7 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inL")), _resolve("meter_inL"));
                w_7->setShowLabels(false);
                fWidgets.emplace_back(w_7);
                fByIndex[_resolve("meter_inL")].push_back(w_7);
                c_2->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                auto* w_8 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inR")), _resolve("meter_inR"));
                w_8->setShowLabels(false);
                fWidgets.emplace_back(w_8);
                fByIndex[_resolve("meter_inR")].push_back(w_8);
                c_2->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2});
                auto* w_9 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_9);
                fByIndex[_resolve("meter_outR")].push_back(w_9);
                c_2->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=3});
                auto* w_10 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_10);
                c_2->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                auto* w_11 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inL")), _resolve("clip_inL"));
                w_11->setShowLabels(false);
                fWidgets.emplace_back(w_11);
                fByIndex[_resolve("clip_inL")].push_back(w_11);
                c_2->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                auto* w_12 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inR")), _resolve("clip_inR"));
                w_12->setShowLabels(false);
                fWidgets.emplace_back(w_12);
                fByIndex[_resolve("clip_inR")].push_back(w_12);
                c_2->add(std::make_unique<CalfWidgetItem>(w_12), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=2});
                auto* w_13 = new CalfLabel(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"), nullptr);
                fWidgets.emplace_back(w_13);
                fByIndex[_resolve("bypass")].push_back(w_13);
                c_2->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=3});
                auto* w_14 = new CalfToggle(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"));
                w_14->setShowLabels(false);
                fWidgets.emplace_back(w_14);
                fByIndex[_resolve("bypass")].push_back(w_14);
                c_2->add(std::make_unique<CalfWidgetItem>(w_14), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .padX=10, .attachX=3, .attachY=1, .attachH=2});
                auto* w_15 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Output level");
                fWidgets.emplace_back(w_15);
                c_2->add(std::make_unique<CalfWidgetItem>(w_15), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4});
                auto* w_16 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outL")), _resolve("meter_outL"));
                w_16->setShowLabels(false);
                fWidgets.emplace_back(w_16);
                fByIndex[_resolve("meter_outL")].push_back(w_16);
                c_2->add(std::make_unique<CalfWidgetItem>(w_16), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=1});
                auto* w_17 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                w_17->setShowLabels(false);
                fWidgets.emplace_back(w_17);
                fByIndex[_resolve("meter_outR")].push_back(w_17);
                c_2->add(std::make_unique<CalfWidgetItem>(w_17), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=2});
                auto* w_18 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_18);
                fByIndex[_resolve("meter_outR")].push_back(w_18);
                c_2->add(std::make_unique<CalfWidgetItem>(w_18), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=3});
                auto* w_19 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_19);
                c_2->add(std::make_unique<CalfWidgetItem>(w_19), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=5});
                auto* w_20 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outL")), _resolve("clip_outL"));
                w_20->setShowLabels(false);
                fWidgets.emplace_back(w_20);
                fByIndex[_resolve("clip_outL")].push_back(w_20);
                c_2->add(std::make_unique<CalfWidgetItem>(w_20), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=1});
                auto* w_21 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outR")), _resolve("clip_outR"));
                w_21->setShowLabels(false);
                fWidgets.emplace_back(w_21);
                fByIndex[_resolve("clip_outR")].push_back(w_21);
                c_2->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=2});
                auto* w_22 = new CalfLabel(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"), nullptr);
                fWidgets.emplace_back(w_22);
                fByIndex[_resolve("level_out")].push_back(w_22);
                c_2->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6});
                auto* w_23 = new CalfKnob(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                w_23->setShowLabels(false);
                fWidgets.emplace_back(w_23);
                fByIndex[_resolve("level_out")].push_back(w_23);
                c_2->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=1, .attachH=2});
                auto* w_24 = new CalfValue(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                fWidgets.emplace_back(w_24);
                fByIndex[_resolve("level_out")].push_back(w_24);
                c_2->add(std::make_unique<CalfWidgetItem>(w_24), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=3});
                c_1->add(std::move(c_2), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=true});
            }
            {
                auto c_26 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_27 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 30, false);
                    {
                        auto c_28 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 10, false);
                        auto* w_29 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Individual Graphs");
                        fWidgets.emplace_back(w_29);
                        c_28->add(std::make_unique<CalfWidgetItem>(w_29), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_30 = new CalfToggle(this, *meta.get_param_props(_resolve("individuals")), _resolve("individuals"));
                        w_30->setShowLabels(false);
                        fWidgets.emplace_back(w_30);
                        fByIndex[_resolve("individuals")].push_back(w_30);
                        c_28->add(std::make_unique<CalfWidgetItem>(w_30), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_27->add(std::move(c_28), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    }
                    {
                        auto c_31 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 10, false);
                        auto* w_32 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Analyzer");
                        fWidgets.emplace_back(w_32);
                        c_31->add(std::make_unique<CalfWidgetItem>(w_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_33 = new CalfToggle(this, *meta.get_param_props(_resolve("analyzer")), _resolve("analyzer"));
                        w_33->setShowLabels(false);
                        fWidgets.emplace_back(w_33);
                        fByIndex[_resolve("analyzer")].push_back(w_33);
                        c_31->add(std::make_unique<CalfWidgetItem>(w_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_34 = new CalfComboBox(this, *meta.get_param_props(_resolve("analyzer_mode")), _resolve("analyzer_mode"));
                        w_34->setShowLabels(false);
                        fWidgets.emplace_back(w_34);
                        fByIndex[_resolve("analyzer_mode")].push_back(w_34);
                        c_31->add(std::make_unique<CalfWidgetItem>(w_34), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_27->add(std::move(c_31), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    }
                    c_26->add(std::move(c_27), CalfPacking{});
                }
                auto c_25 = std::make_unique<CalfAlignItem>(std::move(c_26), 1.0f, 0.5f, 0.0f, 0.0f);
                c_1->add(std::move(c_25), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachW=2});
            }
            {
                auto c_36 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_37 = std::make_unique<CalfTableItem>(1, 2, false, 0, 0);
                    auto* w_38 = new CalfLineGraph(this, *meta.get_param_props(_resolve("ls_freq")), _resolve("ls_freq"), 500, 200);
                    w_38->setSize(static_cast<uint>(500), static_cast<uint>(200));
                    fWidgets.emplace_back(w_38);
                    fByIndex[_resolve("ls_freq")].push_back(w_38);
                    c_37->add(std::make_unique<CalfWidgetItem>(w_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    {
                        auto c_39 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 3, false);
                        auto* w_40 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Zoom");
                        fWidgets.emplace_back(w_40);
                        c_39->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        auto* w_41 = new CalfKnob(this, *meta.get_param_props(_resolve("zoom")), _resolve("zoom"));
                        w_41->setShowLabels(false);
                        fWidgets.emplace_back(w_41);
                        fByIndex[_resolve("zoom")].push_back(w_41);
                        c_39->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        auto* w_42 = new CalfValue(this, *meta.get_param_props(_resolve("zoom")), _resolve("zoom"));
                        fWidgets.emplace_back(w_42);
                        fByIndex[_resolve("zoom")].push_back(w_42);
                        c_39->add(std::make_unique<CalfWidgetItem>(w_42), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        c_37->add(std::move(c_39), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=1});
                    }
                    c_36->add(std::move(c_37), CalfPacking{});
                }
                auto c_35 = std::make_unique<CalfFrameItem>("Frequency Response", std::move(c_36));
                c_1->add(std::move(c_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
            }
            {
                auto c_43 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 8, false);
                {
                    auto c_45 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_46 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 3, false);
                        auto* w_47 = new CalfComboBox(this, *meta.get_param_props(_resolve("hp_active")), _resolve("hp_active"));
                        w_47->setShowLabels(false);
                        fWidgets.emplace_back(w_47);
                        fByIndex[_resolve("hp_active")].push_back(w_47);
                        c_46->add(std::make_unique<CalfWidgetItem>(w_47), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_48 = new CalfLabel(this, *meta.get_param_props(_resolve("hp_freq")), _resolve("hp_freq"), "Frequency");
                        fWidgets.emplace_back(w_48);
                        fByIndex[_resolve("hp_freq")].push_back(w_48);
                        c_46->add(std::make_unique<CalfWidgetItem>(w_48), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_49 = new CalfKnob(this, *meta.get_param_props(_resolve("hp_freq")), _resolve("hp_freq"));
                        w_49->setShowLabels(false);
                        fWidgets.emplace_back(w_49);
                        fByIndex[_resolve("hp_freq")].push_back(w_49);
                        c_46->add(std::make_unique<CalfWidgetItem>(w_49), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_50 = new CalfValue(this, *meta.get_param_props(_resolve("hp_freq")), _resolve("hp_freq"));
                        fWidgets.emplace_back(w_50);
                        fByIndex[_resolve("hp_freq")].push_back(w_50);
                        c_46->add(std::make_unique<CalfWidgetItem>(w_50), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_51 = new CalfLabel(this, *meta.get_param_props(_resolve("hp_q")), _resolve("hp_q"), "Q");
                        fWidgets.emplace_back(w_51);
                        fByIndex[_resolve("hp_q")].push_back(w_51);
                        c_46->add(std::make_unique<CalfWidgetItem>(w_51), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_52 = new CalfKnob(this, *meta.get_param_props(_resolve("hp_q")), _resolve("hp_q"));
                        w_52->setShowLabels(false);
                        fWidgets.emplace_back(w_52);
                        fByIndex[_resolve("hp_q")].push_back(w_52);
                        c_46->add(std::make_unique<CalfWidgetItem>(w_52), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_53 = new CalfValue(this, *meta.get_param_props(_resolve("hp_q")), _resolve("hp_q"));
                        fWidgets.emplace_back(w_53);
                        fByIndex[_resolve("hp_q")].push_back(w_53);
                        c_46->add(std::make_unique<CalfWidgetItem>(w_53), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_54 = new CalfComboBox(this, *meta.get_param_props(_resolve("hp_mode")), _resolve("hp_mode"));
                        w_54->setShowLabels(false);
                        fWidgets.emplace_back(w_54);
                        fByIndex[_resolve("hp_mode")].push_back(w_54);
                        c_46->add(std::make_unique<CalfWidgetItem>(w_54), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_45->add(std::move(c_46), CalfPacking{});
                    }
                    auto c_44 = std::make_unique<CalfFrameItem>("Highpass", std::move(c_45));
                    c_43->add(std::move(c_44), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_56 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_57 = std::make_unique<CalfTableItem>(4, 1, false, 0, 0);
                        {
                            auto c_58 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_59 = new CalfComboBox(this, *meta.get_param_props(_resolve("ls_active")), _resolve("ls_active"));
                            w_59->setShowLabels(false);
                            fWidgets.emplace_back(w_59);
                            fByIndex[_resolve("ls_active")].push_back(w_59);
                            c_58->add(std::make_unique<CalfWidgetItem>(w_59), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_57->add(std::move(c_58), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_60 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_61 = new CalfKnob(this, *meta.get_param_props(_resolve("ls_freq")), _resolve("ls_freq"));
                            w_61->setShowLabels(false);
                            fWidgets.emplace_back(w_61);
                            fByIndex[_resolve("ls_freq")].push_back(w_61);
                            c_60->add(std::make_unique<CalfWidgetItem>(w_61), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_62 = new CalfValue(this, *meta.get_param_props(_resolve("ls_freq")), _resolve("ls_freq"));
                            fWidgets.emplace_back(w_62);
                            fByIndex[_resolve("ls_freq")].push_back(w_62);
                            c_60->add(std::make_unique<CalfWidgetItem>(w_62), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_57->add(std::move(c_60), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                        }
                        {
                            auto c_63 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_64 = new CalfKnob(this, *meta.get_param_props(_resolve("ls_level")), _resolve("ls_level"));
                            w_64->setShowLabels(false);
                            fWidgets.emplace_back(w_64);
                            fByIndex[_resolve("ls_level")].push_back(w_64);
                            c_63->add(std::make_unique<CalfWidgetItem>(w_64), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_65 = new CalfValue(this, *meta.get_param_props(_resolve("ls_level")), _resolve("ls_level"));
                            fWidgets.emplace_back(w_65);
                            fByIndex[_resolve("ls_level")].push_back(w_65);
                            c_63->add(std::make_unique<CalfWidgetItem>(w_65), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_57->add(std::move(c_63), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=2});
                        }
                        {
                            auto c_66 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_67 = new CalfKnob(this, *meta.get_param_props(_resolve("ls_q")), _resolve("ls_q"));
                            w_67->setShowLabels(false);
                            fWidgets.emplace_back(w_67);
                            fByIndex[_resolve("ls_q")].push_back(w_67);
                            c_66->add(std::make_unique<CalfWidgetItem>(w_67), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_68 = new CalfValue(this, *meta.get_param_props(_resolve("ls_q")), _resolve("ls_q"));
                            fWidgets.emplace_back(w_68);
                            fByIndex[_resolve("ls_q")].push_back(w_68);
                            c_66->add(std::make_unique<CalfWidgetItem>(w_68), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_57->add(std::move(c_66), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=3});
                        }
                        c_56->add(std::move(c_57), CalfPacking{});
                    }
                    auto c_55 = std::make_unique<CalfFrameItem>("Lowshelf", std::move(c_56));
                    c_43->add(std::move(c_55), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_70 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_71 = std::make_unique<CalfTableItem>(4, 9, false, 0, 0);
                        auto* w_72 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Freq");
                        fWidgets.emplace_back(w_72);
                        c_71->add(std::make_unique<CalfWidgetItem>(w_72), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                        auto* w_73 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Level");
                        fWidgets.emplace_back(w_73);
                        c_71->add(std::make_unique<CalfWidgetItem>(w_73), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=2});
                        auto* w_74 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Q");
                        fWidgets.emplace_back(w_74);
                        c_71->add(std::make_unique<CalfWidgetItem>(w_74), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=3});
                        auto* w_75 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Active");
                        fWidgets.emplace_back(w_75);
                        c_71->add(std::make_unique<CalfWidgetItem>(w_75), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        {
                            auto c_76 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_77 = new CalfKnob(this, *meta.get_param_props(_resolve("p1_freq")), _resolve("p1_freq"));
                            w_77->setShowLabels(false);
                            fWidgets.emplace_back(w_77);
                            fByIndex[_resolve("p1_freq")].push_back(w_77);
                            c_76->add(std::make_unique<CalfWidgetItem>(w_77), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_78 = new CalfValue(this, *meta.get_param_props(_resolve("p1_freq")), _resolve("p1_freq"));
                            fWidgets.emplace_back(w_78);
                            fByIndex[_resolve("p1_freq")].push_back(w_78);
                            c_76->add(std::make_unique<CalfWidgetItem>(w_78), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_76), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                        }
                        {
                            auto c_79 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_80 = new CalfKnob(this, *meta.get_param_props(_resolve("p1_level")), _resolve("p1_level"));
                            w_80->setShowLabels(false);
                            fWidgets.emplace_back(w_80);
                            fByIndex[_resolve("p1_level")].push_back(w_80);
                            c_79->add(std::make_unique<CalfWidgetItem>(w_80), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_81 = new CalfValue(this, *meta.get_param_props(_resolve("p1_level")), _resolve("p1_level"));
                            fWidgets.emplace_back(w_81);
                            fByIndex[_resolve("p1_level")].push_back(w_81);
                            c_79->add(std::make_unique<CalfWidgetItem>(w_81), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_79), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2});
                        }
                        {
                            auto c_82 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_83 = new CalfKnob(this, *meta.get_param_props(_resolve("p1_q")), _resolve("p1_q"));
                            w_83->setShowLabels(false);
                            fWidgets.emplace_back(w_83);
                            fByIndex[_resolve("p1_q")].push_back(w_83);
                            c_82->add(std::make_unique<CalfWidgetItem>(w_83), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_84 = new CalfValue(this, *meta.get_param_props(_resolve("p1_q")), _resolve("p1_q"));
                            fWidgets.emplace_back(w_84);
                            fByIndex[_resolve("p1_q")].push_back(w_84);
                            c_82->add(std::make_unique<CalfWidgetItem>(w_84), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_82), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=3});
                        }
                        {
                            auto c_85 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_86 = new CalfComboBox(this, *meta.get_param_props(_resolve("p1_active")), _resolve("p1_active"));
                            w_86->setShowLabels(false);
                            fWidgets.emplace_back(w_86);
                            fByIndex[_resolve("p1_active")].push_back(w_86);
                            c_85->add(std::make_unique<CalfWidgetItem>(w_86), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_85), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                        }
                        {
                            auto c_87 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_88 = new CalfKnob(this, *meta.get_param_props(_resolve("p2_freq")), _resolve("p2_freq"));
                            w_88->setShowLabels(false);
                            fWidgets.emplace_back(w_88);
                            fByIndex[_resolve("p2_freq")].push_back(w_88);
                            c_87->add(std::make_unique<CalfWidgetItem>(w_88), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_89 = new CalfValue(this, *meta.get_param_props(_resolve("p2_freq")), _resolve("p2_freq"));
                            fWidgets.emplace_back(w_89);
                            fByIndex[_resolve("p2_freq")].push_back(w_89);
                            c_87->add(std::make_unique<CalfWidgetItem>(w_89), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_87), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                        }
                        {
                            auto c_90 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_91 = new CalfKnob(this, *meta.get_param_props(_resolve("p2_level")), _resolve("p2_level"));
                            w_91->setShowLabels(false);
                            fWidgets.emplace_back(w_91);
                            fByIndex[_resolve("p2_level")].push_back(w_91);
                            c_90->add(std::make_unique<CalfWidgetItem>(w_91), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_92 = new CalfValue(this, *meta.get_param_props(_resolve("p2_level")), _resolve("p2_level"));
                            fWidgets.emplace_back(w_92);
                            fByIndex[_resolve("p2_level")].push_back(w_92);
                            c_90->add(std::make_unique<CalfWidgetItem>(w_92), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_90), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=2});
                        }
                        {
                            auto c_93 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_94 = new CalfKnob(this, *meta.get_param_props(_resolve("p2_q")), _resolve("p2_q"));
                            w_94->setShowLabels(false);
                            fWidgets.emplace_back(w_94);
                            fByIndex[_resolve("p2_q")].push_back(w_94);
                            c_93->add(std::make_unique<CalfWidgetItem>(w_94), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_95 = new CalfValue(this, *meta.get_param_props(_resolve("p2_q")), _resolve("p2_q"));
                            fWidgets.emplace_back(w_95);
                            fByIndex[_resolve("p2_q")].push_back(w_95);
                            c_93->add(std::make_unique<CalfWidgetItem>(w_95), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_93), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=3});
                        }
                        {
                            auto c_96 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_97 = new CalfComboBox(this, *meta.get_param_props(_resolve("p2_active")), _resolve("p2_active"));
                            w_97->setShowLabels(false);
                            fWidgets.emplace_back(w_97);
                            fByIndex[_resolve("p2_active")].push_back(w_97);
                            c_96->add(std::make_unique<CalfWidgetItem>(w_97), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_96), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                        }
                        {
                            auto c_98 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_99 = new CalfKnob(this, *meta.get_param_props(_resolve("p3_freq")), _resolve("p3_freq"));
                            w_99->setShowLabels(false);
                            fWidgets.emplace_back(w_99);
                            fByIndex[_resolve("p3_freq")].push_back(w_99);
                            c_98->add(std::make_unique<CalfWidgetItem>(w_99), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_100 = new CalfValue(this, *meta.get_param_props(_resolve("p3_freq")), _resolve("p3_freq"));
                            fWidgets.emplace_back(w_100);
                            fByIndex[_resolve("p3_freq")].push_back(w_100);
                            c_98->add(std::make_unique<CalfWidgetItem>(w_100), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_98), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=1});
                        }
                        {
                            auto c_101 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_102 = new CalfKnob(this, *meta.get_param_props(_resolve("p3_level")), _resolve("p3_level"));
                            w_102->setShowLabels(false);
                            fWidgets.emplace_back(w_102);
                            fByIndex[_resolve("p3_level")].push_back(w_102);
                            c_101->add(std::make_unique<CalfWidgetItem>(w_102), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_103 = new CalfValue(this, *meta.get_param_props(_resolve("p3_level")), _resolve("p3_level"));
                            fWidgets.emplace_back(w_103);
                            fByIndex[_resolve("p3_level")].push_back(w_103);
                            c_101->add(std::make_unique<CalfWidgetItem>(w_103), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_101), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=2});
                        }
                        {
                            auto c_104 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_105 = new CalfKnob(this, *meta.get_param_props(_resolve("p3_q")), _resolve("p3_q"));
                            w_105->setShowLabels(false);
                            fWidgets.emplace_back(w_105);
                            fByIndex[_resolve("p3_q")].push_back(w_105);
                            c_104->add(std::make_unique<CalfWidgetItem>(w_105), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_106 = new CalfValue(this, *meta.get_param_props(_resolve("p3_q")), _resolve("p3_q"));
                            fWidgets.emplace_back(w_106);
                            fByIndex[_resolve("p3_q")].push_back(w_106);
                            c_104->add(std::make_unique<CalfWidgetItem>(w_106), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_104), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=3});
                        }
                        {
                            auto c_107 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_108 = new CalfComboBox(this, *meta.get_param_props(_resolve("p3_active")), _resolve("p3_active"));
                            w_108->setShowLabels(false);
                            fWidgets.emplace_back(w_108);
                            fByIndex[_resolve("p3_active")].push_back(w_108);
                            c_107->add(std::make_unique<CalfWidgetItem>(w_108), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_107), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3});
                        }
                        {
                            auto c_109 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_110 = new CalfKnob(this, *meta.get_param_props(_resolve("p4_freq")), _resolve("p4_freq"));
                            w_110->setShowLabels(false);
                            fWidgets.emplace_back(w_110);
                            fByIndex[_resolve("p4_freq")].push_back(w_110);
                            c_109->add(std::make_unique<CalfWidgetItem>(w_110), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_111 = new CalfValue(this, *meta.get_param_props(_resolve("p4_freq")), _resolve("p4_freq"));
                            fWidgets.emplace_back(w_111);
                            fByIndex[_resolve("p4_freq")].push_back(w_111);
                            c_109->add(std::make_unique<CalfWidgetItem>(w_111), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_109), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=1});
                        }
                        {
                            auto c_112 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_113 = new CalfKnob(this, *meta.get_param_props(_resolve("p4_level")), _resolve("p4_level"));
                            w_113->setShowLabels(false);
                            fWidgets.emplace_back(w_113);
                            fByIndex[_resolve("p4_level")].push_back(w_113);
                            c_112->add(std::make_unique<CalfWidgetItem>(w_113), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_114 = new CalfValue(this, *meta.get_param_props(_resolve("p4_level")), _resolve("p4_level"));
                            fWidgets.emplace_back(w_114);
                            fByIndex[_resolve("p4_level")].push_back(w_114);
                            c_112->add(std::make_unique<CalfWidgetItem>(w_114), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_112), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=2});
                        }
                        {
                            auto c_115 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_116 = new CalfKnob(this, *meta.get_param_props(_resolve("p4_q")), _resolve("p4_q"));
                            w_116->setShowLabels(false);
                            fWidgets.emplace_back(w_116);
                            fByIndex[_resolve("p4_q")].push_back(w_116);
                            c_115->add(std::make_unique<CalfWidgetItem>(w_116), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_117 = new CalfValue(this, *meta.get_param_props(_resolve("p4_q")), _resolve("p4_q"));
                            fWidgets.emplace_back(w_117);
                            fByIndex[_resolve("p4_q")].push_back(w_117);
                            c_115->add(std::make_unique<CalfWidgetItem>(w_117), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_115), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=3});
                        }
                        {
                            auto c_118 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_119 = new CalfComboBox(this, *meta.get_param_props(_resolve("p4_active")), _resolve("p4_active"));
                            w_119->setShowLabels(false);
                            fWidgets.emplace_back(w_119);
                            fByIndex[_resolve("p4_active")].push_back(w_119);
                            c_118->add(std::make_unique<CalfWidgetItem>(w_119), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_118), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4});
                        }
                        {
                            auto c_120 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_121 = new CalfKnob(this, *meta.get_param_props(_resolve("p5_freq")), _resolve("p5_freq"));
                            w_121->setShowLabels(false);
                            fWidgets.emplace_back(w_121);
                            fByIndex[_resolve("p5_freq")].push_back(w_121);
                            c_120->add(std::make_unique<CalfWidgetItem>(w_121), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_122 = new CalfValue(this, *meta.get_param_props(_resolve("p5_freq")), _resolve("p5_freq"));
                            fWidgets.emplace_back(w_122);
                            fByIndex[_resolve("p5_freq")].push_back(w_122);
                            c_120->add(std::make_unique<CalfWidgetItem>(w_122), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_120), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=1});
                        }
                        {
                            auto c_123 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_124 = new CalfKnob(this, *meta.get_param_props(_resolve("p5_level")), _resolve("p5_level"));
                            w_124->setShowLabels(false);
                            fWidgets.emplace_back(w_124);
                            fByIndex[_resolve("p5_level")].push_back(w_124);
                            c_123->add(std::make_unique<CalfWidgetItem>(w_124), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_125 = new CalfValue(this, *meta.get_param_props(_resolve("p5_level")), _resolve("p5_level"));
                            fWidgets.emplace_back(w_125);
                            fByIndex[_resolve("p5_level")].push_back(w_125);
                            c_123->add(std::make_unique<CalfWidgetItem>(w_125), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_123), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=2});
                        }
                        {
                            auto c_126 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_127 = new CalfKnob(this, *meta.get_param_props(_resolve("p5_q")), _resolve("p5_q"));
                            w_127->setShowLabels(false);
                            fWidgets.emplace_back(w_127);
                            fByIndex[_resolve("p5_q")].push_back(w_127);
                            c_126->add(std::make_unique<CalfWidgetItem>(w_127), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_128 = new CalfValue(this, *meta.get_param_props(_resolve("p5_q")), _resolve("p5_q"));
                            fWidgets.emplace_back(w_128);
                            fByIndex[_resolve("p5_q")].push_back(w_128);
                            c_126->add(std::make_unique<CalfWidgetItem>(w_128), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_126), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=3});
                        }
                        {
                            auto c_129 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_130 = new CalfComboBox(this, *meta.get_param_props(_resolve("p5_active")), _resolve("p5_active"));
                            w_130->setShowLabels(false);
                            fWidgets.emplace_back(w_130);
                            fByIndex[_resolve("p5_active")].push_back(w_130);
                            c_129->add(std::make_unique<CalfWidgetItem>(w_130), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_129), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5});
                        }
                        {
                            auto c_131 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_132 = new CalfKnob(this, *meta.get_param_props(_resolve("p6_freq")), _resolve("p6_freq"));
                            w_132->setShowLabels(false);
                            fWidgets.emplace_back(w_132);
                            fByIndex[_resolve("p6_freq")].push_back(w_132);
                            c_131->add(std::make_unique<CalfWidgetItem>(w_132), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_133 = new CalfValue(this, *meta.get_param_props(_resolve("p6_freq")), _resolve("p6_freq"));
                            fWidgets.emplace_back(w_133);
                            fByIndex[_resolve("p6_freq")].push_back(w_133);
                            c_131->add(std::make_unique<CalfWidgetItem>(w_133), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_131), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=1});
                        }
                        {
                            auto c_134 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_135 = new CalfKnob(this, *meta.get_param_props(_resolve("p6_level")), _resolve("p6_level"));
                            w_135->setShowLabels(false);
                            fWidgets.emplace_back(w_135);
                            fByIndex[_resolve("p6_level")].push_back(w_135);
                            c_134->add(std::make_unique<CalfWidgetItem>(w_135), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_136 = new CalfValue(this, *meta.get_param_props(_resolve("p6_level")), _resolve("p6_level"));
                            fWidgets.emplace_back(w_136);
                            fByIndex[_resolve("p6_level")].push_back(w_136);
                            c_134->add(std::make_unique<CalfWidgetItem>(w_136), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_134), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=2});
                        }
                        {
                            auto c_137 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_138 = new CalfKnob(this, *meta.get_param_props(_resolve("p6_q")), _resolve("p6_q"));
                            w_138->setShowLabels(false);
                            fWidgets.emplace_back(w_138);
                            fByIndex[_resolve("p6_q")].push_back(w_138);
                            c_137->add(std::make_unique<CalfWidgetItem>(w_138), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_139 = new CalfValue(this, *meta.get_param_props(_resolve("p6_q")), _resolve("p6_q"));
                            fWidgets.emplace_back(w_139);
                            fByIndex[_resolve("p6_q")].push_back(w_139);
                            c_137->add(std::make_unique<CalfWidgetItem>(w_139), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_137), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=3});
                        }
                        {
                            auto c_140 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_141 = new CalfComboBox(this, *meta.get_param_props(_resolve("p6_active")), _resolve("p6_active"));
                            w_141->setShowLabels(false);
                            fWidgets.emplace_back(w_141);
                            fByIndex[_resolve("p6_active")].push_back(w_141);
                            c_140->add(std::make_unique<CalfWidgetItem>(w_141), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_140), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=6});
                        }
                        {
                            auto c_142 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_143 = new CalfKnob(this, *meta.get_param_props(_resolve("p7_freq")), _resolve("p7_freq"));
                            w_143->setShowLabels(false);
                            fWidgets.emplace_back(w_143);
                            fByIndex[_resolve("p7_freq")].push_back(w_143);
                            c_142->add(std::make_unique<CalfWidgetItem>(w_143), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_144 = new CalfValue(this, *meta.get_param_props(_resolve("p7_freq")), _resolve("p7_freq"));
                            fWidgets.emplace_back(w_144);
                            fByIndex[_resolve("p7_freq")].push_back(w_144);
                            c_142->add(std::make_unique<CalfWidgetItem>(w_144), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_142), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=7, .attachY=1});
                        }
                        {
                            auto c_145 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_146 = new CalfKnob(this, *meta.get_param_props(_resolve("p7_level")), _resolve("p7_level"));
                            w_146->setShowLabels(false);
                            fWidgets.emplace_back(w_146);
                            fByIndex[_resolve("p7_level")].push_back(w_146);
                            c_145->add(std::make_unique<CalfWidgetItem>(w_146), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_147 = new CalfValue(this, *meta.get_param_props(_resolve("p7_level")), _resolve("p7_level"));
                            fWidgets.emplace_back(w_147);
                            fByIndex[_resolve("p7_level")].push_back(w_147);
                            c_145->add(std::make_unique<CalfWidgetItem>(w_147), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_145), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=7, .attachY=2});
                        }
                        {
                            auto c_148 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_149 = new CalfKnob(this, *meta.get_param_props(_resolve("p7_q")), _resolve("p7_q"));
                            w_149->setShowLabels(false);
                            fWidgets.emplace_back(w_149);
                            fByIndex[_resolve("p7_q")].push_back(w_149);
                            c_148->add(std::make_unique<CalfWidgetItem>(w_149), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_150 = new CalfValue(this, *meta.get_param_props(_resolve("p7_q")), _resolve("p7_q"));
                            fWidgets.emplace_back(w_150);
                            fByIndex[_resolve("p7_q")].push_back(w_150);
                            c_148->add(std::make_unique<CalfWidgetItem>(w_150), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_148), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=7, .attachY=3});
                        }
                        {
                            auto c_151 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_152 = new CalfComboBox(this, *meta.get_param_props(_resolve("p7_active")), _resolve("p7_active"));
                            w_152->setShowLabels(false);
                            fWidgets.emplace_back(w_152);
                            fByIndex[_resolve("p7_active")].push_back(w_152);
                            c_151->add(std::make_unique<CalfWidgetItem>(w_152), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_151), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=7});
                        }
                        {
                            auto c_153 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_154 = new CalfKnob(this, *meta.get_param_props(_resolve("p8_freq")), _resolve("p8_freq"));
                            w_154->setShowLabels(false);
                            fWidgets.emplace_back(w_154);
                            fByIndex[_resolve("p8_freq")].push_back(w_154);
                            c_153->add(std::make_unique<CalfWidgetItem>(w_154), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_155 = new CalfValue(this, *meta.get_param_props(_resolve("p8_freq")), _resolve("p8_freq"));
                            fWidgets.emplace_back(w_155);
                            fByIndex[_resolve("p8_freq")].push_back(w_155);
                            c_153->add(std::make_unique<CalfWidgetItem>(w_155), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_153), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=8, .attachY=1});
                        }
                        {
                            auto c_156 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_157 = new CalfKnob(this, *meta.get_param_props(_resolve("p8_level")), _resolve("p8_level"));
                            w_157->setShowLabels(false);
                            fWidgets.emplace_back(w_157);
                            fByIndex[_resolve("p8_level")].push_back(w_157);
                            c_156->add(std::make_unique<CalfWidgetItem>(w_157), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_158 = new CalfValue(this, *meta.get_param_props(_resolve("p8_level")), _resolve("p8_level"));
                            fWidgets.emplace_back(w_158);
                            fByIndex[_resolve("p8_level")].push_back(w_158);
                            c_156->add(std::make_unique<CalfWidgetItem>(w_158), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_156), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=8, .attachY=2});
                        }
                        {
                            auto c_159 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_160 = new CalfKnob(this, *meta.get_param_props(_resolve("p8_q")), _resolve("p8_q"));
                            w_160->setShowLabels(false);
                            fWidgets.emplace_back(w_160);
                            fByIndex[_resolve("p8_q")].push_back(w_160);
                            c_159->add(std::make_unique<CalfWidgetItem>(w_160), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_161 = new CalfValue(this, *meta.get_param_props(_resolve("p8_q")), _resolve("p8_q"));
                            fWidgets.emplace_back(w_161);
                            fByIndex[_resolve("p8_q")].push_back(w_161);
                            c_159->add(std::make_unique<CalfWidgetItem>(w_161), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_159), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=8, .attachY=3});
                        }
                        {
                            auto c_162 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_163 = new CalfComboBox(this, *meta.get_param_props(_resolve("p8_active")), _resolve("p8_active"));
                            w_163->setShowLabels(false);
                            fWidgets.emplace_back(w_163);
                            fByIndex[_resolve("p8_active")].push_back(w_163);
                            c_162->add(std::make_unique<CalfWidgetItem>(w_163), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_71->add(std::move(c_162), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=8});
                        }
                        c_70->add(std::move(c_71), CalfPacking{});
                    }
                    auto c_69 = std::make_unique<CalfFrameItem>("Parametrics", std::move(c_70));
                    c_43->add(std::move(c_69), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                }
                {
                    auto c_165 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_166 = std::make_unique<CalfTableItem>(4, 1, false, 0, 0);
                        {
                            auto c_167 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_168 = new CalfComboBox(this, *meta.get_param_props(_resolve("hs_active")), _resolve("hs_active"));
                            w_168->setShowLabels(false);
                            fWidgets.emplace_back(w_168);
                            fByIndex[_resolve("hs_active")].push_back(w_168);
                            c_167->add(std::make_unique<CalfWidgetItem>(w_168), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_166->add(std::move(c_167), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_169 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_170 = new CalfKnob(this, *meta.get_param_props(_resolve("hs_freq")), _resolve("hs_freq"));
                            w_170->setShowLabels(false);
                            fWidgets.emplace_back(w_170);
                            fByIndex[_resolve("hs_freq")].push_back(w_170);
                            c_169->add(std::make_unique<CalfWidgetItem>(w_170), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_171 = new CalfValue(this, *meta.get_param_props(_resolve("hs_freq")), _resolve("hs_freq"));
                            fWidgets.emplace_back(w_171);
                            fByIndex[_resolve("hs_freq")].push_back(w_171);
                            c_169->add(std::make_unique<CalfWidgetItem>(w_171), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_166->add(std::move(c_169), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                        }
                        {
                            auto c_172 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_173 = new CalfKnob(this, *meta.get_param_props(_resolve("hs_level")), _resolve("hs_level"));
                            w_173->setShowLabels(false);
                            fWidgets.emplace_back(w_173);
                            fByIndex[_resolve("hs_level")].push_back(w_173);
                            c_172->add(std::make_unique<CalfWidgetItem>(w_173), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_174 = new CalfValue(this, *meta.get_param_props(_resolve("hs_level")), _resolve("hs_level"));
                            fWidgets.emplace_back(w_174);
                            fByIndex[_resolve("hs_level")].push_back(w_174);
                            c_172->add(std::make_unique<CalfWidgetItem>(w_174), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_166->add(std::move(c_172), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=2});
                        }
                        {
                            auto c_175 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_176 = new CalfKnob(this, *meta.get_param_props(_resolve("hs_q")), _resolve("hs_q"));
                            w_176->setShowLabels(false);
                            fWidgets.emplace_back(w_176);
                            fByIndex[_resolve("hs_q")].push_back(w_176);
                            c_175->add(std::make_unique<CalfWidgetItem>(w_176), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_177 = new CalfValue(this, *meta.get_param_props(_resolve("hs_q")), _resolve("hs_q"));
                            fWidgets.emplace_back(w_177);
                            fByIndex[_resolve("hs_q")].push_back(w_177);
                            c_175->add(std::make_unique<CalfWidgetItem>(w_177), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_166->add(std::move(c_175), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=3});
                        }
                        c_165->add(std::move(c_166), CalfPacking{});
                    }
                    auto c_164 = std::make_unique<CalfFrameItem>("Highshelf", std::move(c_165));
                    c_43->add(std::move(c_164), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_179 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_180 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 3, false);
                        auto* w_181 = new CalfComboBox(this, *meta.get_param_props(_resolve("lp_active")), _resolve("lp_active"));
                        w_181->setShowLabels(false);
                        fWidgets.emplace_back(w_181);
                        fByIndex[_resolve("lp_active")].push_back(w_181);
                        c_180->add(std::make_unique<CalfWidgetItem>(w_181), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_182 = new CalfLabel(this, *meta.get_param_props(_resolve("lp_freq")), _resolve("lp_freq"), "Frequency");
                        fWidgets.emplace_back(w_182);
                        fByIndex[_resolve("lp_freq")].push_back(w_182);
                        c_180->add(std::make_unique<CalfWidgetItem>(w_182), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_183 = new CalfKnob(this, *meta.get_param_props(_resolve("lp_freq")), _resolve("lp_freq"));
                        w_183->setShowLabels(false);
                        fWidgets.emplace_back(w_183);
                        fByIndex[_resolve("lp_freq")].push_back(w_183);
                        c_180->add(std::make_unique<CalfWidgetItem>(w_183), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_184 = new CalfValue(this, *meta.get_param_props(_resolve("lp_freq")), _resolve("lp_freq"));
                        fWidgets.emplace_back(w_184);
                        fByIndex[_resolve("lp_freq")].push_back(w_184);
                        c_180->add(std::make_unique<CalfWidgetItem>(w_184), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_185 = new CalfLabel(this, *meta.get_param_props(_resolve("lp_q")), _resolve("lp_q"), "Q");
                        fWidgets.emplace_back(w_185);
                        fByIndex[_resolve("lp_q")].push_back(w_185);
                        c_180->add(std::make_unique<CalfWidgetItem>(w_185), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_186 = new CalfKnob(this, *meta.get_param_props(_resolve("lp_q")), _resolve("lp_q"));
                        w_186->setShowLabels(false);
                        fWidgets.emplace_back(w_186);
                        fByIndex[_resolve("lp_q")].push_back(w_186);
                        c_180->add(std::make_unique<CalfWidgetItem>(w_186), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_187 = new CalfValue(this, *meta.get_param_props(_resolve("lp_q")), _resolve("lp_q"));
                        fWidgets.emplace_back(w_187);
                        fByIndex[_resolve("lp_q")].push_back(w_187);
                        c_180->add(std::make_unique<CalfWidgetItem>(w_187), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_188 = new CalfComboBox(this, *meta.get_param_props(_resolve("lp_mode")), _resolve("lp_mode"));
                        w_188->setShowLabels(false);
                        fWidgets.emplace_back(w_188);
                        fByIndex[_resolve("lp_mode")].push_back(w_188);
                        c_180->add(std::make_unique<CalfWidgetItem>(w_188), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_179->add(std::move(c_180), CalfPacking{});
                    }
                    auto c_178 = std::make_unique<CalfFrameItem>("Lowpass", std::move(c_179));
                    c_43->add(std::move(c_178), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_43), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);
    }

protected:
    void onNanoDisplay() override
    {
        beginPath();
        rect(0, 0, getWidth(), getHeight());
        fillColor(Color(0.12f, 0.12f, 0.14f));
        fill();
        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it == fByIndex.end()) return;
        for (auto* w : it->second) w->setValue(value, /*notify=*/false);
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
    }

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(Eq12UI)
};

UI* createUI() { return new Eq12UI(); }

END_NAMESPACE_DISTRHO
