/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/pitch.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfTheme.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLineGraph.hpp"
#include "CalfValue.hpp"
#include <calf/metadata.h>
#ifndef ENABLE_EXPERIMENTAL
#define ENABLE_EXPERIMENTAL 1
#endif
#include <calf/modules_pitch.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class PitchUI : public UI, public CalfWidgetBase::Callback
{
public:
    PitchUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = pitch_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
            {
                auto c_2 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, false);
                {
                    auto c_3 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    auto* w_4 = new CalfLabel(this, *meta.get_param_props(_resolve("pd_threshold")), _resolve("pd_threshold"), nullptr);
                    fWidgets.emplace_back(w_4);
                    fByIndex[_resolve("pd_threshold")].push_back(w_4);
                    c_3->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_5 = new CalfKnob(this, *meta.get_param_props(_resolve("pd_threshold")), _resolve("pd_threshold"));
                    w_5->setShowLabels(false);
                    fWidgets.emplace_back(w_5);
                    fByIndex[_resolve("pd_threshold")].push_back(w_5);
                    c_3->add(std::make_unique<CalfWidgetItem>(w_5), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_6 = new CalfValue(this, *meta.get_param_props(_resolve("pd_threshold")), _resolve("pd_threshold"));
                    fWidgets.emplace_back(w_6);
                    fByIndex[_resolve("pd_threshold")].push_back(w_6);
                    c_3->add(std::make_unique<CalfWidgetItem>(w_6), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    c_2->add(std::move(c_3), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                }
                {
                    auto c_7 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    auto* w_8 = new CalfLabel(this, *meta.get_param_props(_resolve("pd_subdivide")), _resolve("pd_subdivide"), nullptr);
                    fWidgets.emplace_back(w_8);
                    fByIndex[_resolve("pd_subdivide")].push_back(w_8);
                    c_7->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_9 = new CalfKnob(this, *meta.get_param_props(_resolve("pd_subdivide")), _resolve("pd_subdivide"));
                    w_9->setShowLabels(false);
                    fWidgets.emplace_back(w_9);
                    fByIndex[_resolve("pd_subdivide")].push_back(w_9);
                    c_7->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_10 = new CalfValue(this, *meta.get_param_props(_resolve("pd_subdivide")), _resolve("pd_subdivide"));
                    fWidgets.emplace_back(w_10);
                    fByIndex[_resolve("pd_subdivide")].push_back(w_10);
                    c_7->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    c_2->add(std::move(c_7), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                }
                {
                    auto c_11 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    auto* w_12 = new CalfLabel(this, *meta.get_param_props(_resolve("tune")), _resolve("tune"), nullptr);
                    fWidgets.emplace_back(w_12);
                    fByIndex[_resolve("tune")].push_back(w_12);
                    c_11->add(std::make_unique<CalfWidgetItem>(w_12), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_13 = new CalfKnob(this, *meta.get_param_props(_resolve("tune")), _resolve("tune"));
                    w_13->setShowLabels(false);
                    fWidgets.emplace_back(w_13);
                    fByIndex[_resolve("tune")].push_back(w_13);
                    c_11->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_14 = new CalfValue(this, *meta.get_param_props(_resolve("tune")), _resolve("tune"));
                    fWidgets.emplace_back(w_14);
                    fByIndex[_resolve("tune")].push_back(w_14);
                    c_11->add(std::make_unique<CalfWidgetItem>(w_14), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    c_2->add(std::move(c_11), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                }
                {
                    auto c_15 = std::make_unique<CalfTableItem>(3, 2, false, 0, 0);
                    auto* w_16 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "MIDI Note:");
                    fWidgets.emplace_back(w_16);
                    c_15->add(std::make_unique<CalfWidgetItem>(w_16), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_17 = new CalfValue(this, *meta.get_param_props(_resolve("note")), _resolve("note"));
                    fWidgets.emplace_back(w_17);
                    fByIndex[_resolve("note")].push_back(w_17);
                    c_15->add(std::make_unique<CalfWidgetItem>(w_17), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                    auto* w_18 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Cents:");
                    fWidgets.emplace_back(w_18);
                    c_15->add(std::make_unique<CalfWidgetItem>(w_18), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                    auto* w_19 = new CalfValue(this, *meta.get_param_props(_resolve("cents")), _resolve("cents"));
                    fWidgets.emplace_back(w_19);
                    fByIndex[_resolve("cents")].push_back(w_19);
                    c_15->add(std::make_unique<CalfWidgetItem>(w_19), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                    auto* w_20 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clarity:");
                    fWidgets.emplace_back(w_20);
                    c_15->add(std::make_unique<CalfWidgetItem>(w_20), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=2});
                    auto* w_21 = new CalfValue(this, *meta.get_param_props(_resolve("clarity")), _resolve("clarity"));
                    fWidgets.emplace_back(w_21);
                    fByIndex[_resolve("clarity")].push_back(w_21);
                    c_15->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2});
                    c_2->add(std::move(c_15), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_2), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
            }
            {
                auto c_23 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                auto* w_24 = new CalfLineGraph(this, *meta.get_param_props(_resolve("pd_threshold")), _resolve("pd_threshold"), 400, 160);
                fLineGraphs.push_back({ w_24, static_cast<int>(_resolve("pd_threshold")) });
                w_24->setSize(static_cast<uint>(400), static_cast<uint>(160));
                fWidgets.emplace_back(w_24);
                fByIndex[_resolve("pd_threshold")].push_back(w_24);
                c_23->add(std::make_unique<CalfWidgetItem>(w_24), CalfPacking{});
                auto c_22 = std::make_unique<CalfFrameItem>("Autocorrelation/Spectrum", std::move(c_23));
                c_1->add(std::move(c_22), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            {
                auto c_26 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                auto* w_27 = new CalfLineGraph(this, *meta.get_param_props(_resolve("note")), _resolve("note"));
                w_27->setSize(static_cast<uint>(400), static_cast<uint>(160));
                fWidgets.emplace_back(w_27);
                fByIndex[_resolve("note")].push_back(w_27);
                c_26->add(std::make_unique<CalfWidgetItem>(w_27), CalfPacking{});
                auto c_25 = std::make_unique<CalfFrameItem>("Tuner", std::move(c_26));
                c_1->add(std::move(c_25), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);

        // Shadow module: same DSP class as the running plugin, instantiated
        // UI-side just so <line-graph> widgets can query line_graph_iface
        // synchronously during paint.
        fShadow = std::make_unique<calf_plugins::pitch_audio_module>();
        fShadowParams.assign(Meta::param_count, 0.0f);
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            fShadowParams[i] = meta.get_param_props(static_cast<int>(i))->def_value;
            fShadow->params[i] = &fShadowParams[i];
        }
        fShadow->post_instantiate(48000);
        fShadow->set_sample_rate(48000);
        fShadow->params_changed();
        fShadow->activate();
        // Not every Calf module inherits line_graph_iface — only the
        // ones that draw curves do. Cross-cast at runtime; null means
        // "this plugin has no curves to draw, paint the placeholder".
        const calf_plugins::line_graph_iface* _lg =
            dynamic_cast<const calf_plugins::line_graph_iface*>(fShadow.get());
        if (_lg) {
            for (auto& g : fLineGraphs)
                g.w->setGraphSource(_lg, g.idx);
        }
    }

protected:
    void onNanoDisplay() override
    {
        const float w = static_cast<float>(getWidth());
        const float h = static_cast<float>(getHeight());

        // Themed background: stretch the GTK Calf_Default plugin
        // background across the whole UI. Falls back to the dark flat
        // fill if the asset failed to decode.
        beginPath();
        rect(0, 0, w, h);
        NanoImage* _bg = fTheme.image("background_plugin.png");
        if (_bg && _bg->isValid()) {
            fillPaint(imagePattern(0, 0, w, h, 0.0f, *_bg, 1.0f));
        } else {
            fillColor(Color(0.12f, 0.12f, 0.14f));
        }
        fill();

        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it != fByIndex.end())
            for (auto* w : it->second) w->setValue(value, /*notify=*/false);
        if (fShadow && index < fShadowParams.size()) {
            fShadowParams[index] = value;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
        if (fShadow && w->getParamIndex() < fShadowParams.size()) {
            fShadowParams[w->getParamIndex()] = v;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    // No-op for WANT_STATE plugins (Monosynth, Organ, FluidSynth, Wavetable).
    // Codegen UIs don't yet visualise state keys (organ presets, wavetable
    // data, SF2 path, modmatrix rows); hand-written subclasses can override.
    // DPF only declares stateChanged when the plugin opts in, so guard.
#if DISTRHO_PLUGIN_WANT_STATE
    void stateChanged(const char* /*key*/, const char* /*value*/) override {}
#endif

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    CalfTheme                                         fTheme{*this};
    std::unique_ptr<calf_plugins::pitch_audio_module> fShadow;
    std::vector<float>                            fShadowParams;
    struct LineGraphRef { CalfLineGraph* w; int idx; };
    std::vector<LineGraphRef>                     fLineGraphs;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(PitchUI)
};

UI* createUI() { return new PitchUI(); }

END_NAMESPACE_DISTRHO
