#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND   "CalfDPFClaude"
#define DISTRHO_PLUGIN_NAME    "XOver2"
#define DISTRHO_PLUGIN_URI     "https://calf-studio-gear.org/plugins/xover2"
#define DISTRHO_PLUGIN_CLAP_ID "org.calf-studio-gear.xover2"

#define DISTRHO_PLUGIN_BRAND_ID  CalfDPFClaude
#define DISTRHO_PLUGIN_UNIQUE_ID cXo2

#define DISTRHO_PLUGIN_HAS_UI       1
#define DISTRHO_UI_USE_NANOVG       1
#define DISTRHO_PLUGIN_IS_RT_SAFE   1
#define DISTRHO_PLUGIN_NUM_INPUTS   2
#define DISTRHO_PLUGIN_NUM_OUTPUTS  4
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 0
#define DISTRHO_PLUGIN_WANT_STATE   0

#endif
