/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/compressor.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfTheme.hpp"
#include "CalfComboBox.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLed.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include "CalfVuMeter.hpp"
#include <calf/metadata.h>
#ifndef ENABLE_EXPERIMENTAL
#define ENABLE_EXPERIMENTAL 1
#endif
#include <calf/modules_comp.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfComboBox;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLed;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfVuMeter;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class CompressorUI : public UI, public CalfWidgetBase::Callback
{
public:
    CompressorUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = compressor_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 8, false);
            {
                auto c_2 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 8, false);
                {
                    auto c_3 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 7, false);
                    auto* w_4 = new CalfLabel(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"), nullptr);
                    fWidgets.emplace_back(w_4);
                    fByIndex[_resolve("bypass")].push_back(w_4);
                    c_3->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    {
                        auto c_6 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_7 = new CalfToggle(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"));
                        w_7->setIcon("bypass");
                        w_7->setShowLabels(false);
                        fWidgets.emplace_back(w_7);
                        fByIndex[_resolve("bypass")].push_back(w_7);
                        c_6->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{});
                        auto c_5 = std::make_unique<CalfAlignItem>(std::move(c_6), 0.5f, 0.5f, 0.0f, 0.0f);
                        c_3->add(std::move(c_5), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_2->add(std::move(c_3), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                }
                {
                    auto c_8 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    auto* w_9 = new CalfLabel(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"), nullptr);
                    fWidgets.emplace_back(w_9);
                    fByIndex[_resolve("level_in")].push_back(w_9);
                    c_8->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_10 = new CalfKnob(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                    w_10->setShowLabels(false);
                    w_10->setKnobSize(5);
                    fWidgets.emplace_back(w_10);
                    fByIndex[_resolve("level_in")].push_back(w_10);
                    c_8->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_11 = new CalfValue(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                    fWidgets.emplace_back(w_11);
                    fByIndex[_resolve("level_in")].push_back(w_11);
                    c_8->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_2->add(std::move(c_8), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                }
                {
                    auto c_12 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    auto* w_13 = new CalfLabel(this, *meta.get_param_props(_resolve("mix")), _resolve("mix"), nullptr);
                    fWidgets.emplace_back(w_13);
                    fByIndex[_resolve("mix")].push_back(w_13);
                    c_12->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_14 = new CalfKnob(this, *meta.get_param_props(_resolve("mix")), _resolve("mix"));
                    w_14->setShowLabels(false);
                    w_14->setKnobSize(3);
                    fWidgets.emplace_back(w_14);
                    fByIndex[_resolve("mix")].push_back(w_14);
                    c_12->add(std::make_unique<CalfWidgetItem>(w_14), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_15 = new CalfValue(this, *meta.get_param_props(_resolve("mix")), _resolve("mix"));
                    fWidgets.emplace_back(w_15);
                    fByIndex[_resolve("mix")].push_back(w_15);
                    c_12->add(std::make_unique<CalfWidgetItem>(w_15), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_2->add(std::move(c_12), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                }
                c_1->add(std::move(c_2), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
            }
            {
                auto c_16 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                {
                    auto c_18 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_19 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        {
                            auto c_20 = std::make_unique<CalfTableItem>(3, 3, false, 0, 0);
                            auto* w_21 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_in")), _resolve("meter_in"), nullptr);
                            fWidgets.emplace_back(w_21);
                            fByIndex[_resolve("meter_in")].push_back(w_21);
                            c_20->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true});
                            auto* w_22 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_in")), _resolve("meter_in"));
                            w_22->setShowLabels(false);
                            fWidgets.emplace_back(w_22);
                            fByIndex[_resolve("meter_in")].push_back(w_22);
                            c_20->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                            auto* w_23 = new CalfLed(this, *meta.get_param_props(_resolve("clip_in")), _resolve("clip_in"));
                            w_23->setShowLabels(false);
                            fWidgets.emplace_back(w_23);
                            fByIndex[_resolve("clip_in")].push_back(w_23);
                            c_20->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=2});
                            auto* w_24 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_out")), _resolve("meter_out"), nullptr);
                            fWidgets.emplace_back(w_24);
                            fByIndex[_resolve("meter_out")].push_back(w_24);
                            c_20->add(std::make_unique<CalfWidgetItem>(w_24), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachY=1});
                            auto* w_25 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_out")), _resolve("meter_out"));
                            w_25->setShowLabels(false);
                            fWidgets.emplace_back(w_25);
                            fByIndex[_resolve("meter_out")].push_back(w_25);
                            c_20->add(std::make_unique<CalfWidgetItem>(w_25), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                            auto* w_26 = new CalfLed(this, *meta.get_param_props(_resolve("clip_out")), _resolve("clip_out"));
                            w_26->setShowLabels(false);
                            fWidgets.emplace_back(w_26);
                            fByIndex[_resolve("clip_out")].push_back(w_26);
                            c_20->add(std::make_unique<CalfWidgetItem>(w_26), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=2, .attachY=1});
                            auto* w_27 = new CalfLabel(this, *meta.get_param_props(_resolve("compression")), _resolve("compression"), nullptr);
                            fWidgets.emplace_back(w_27);
                            fByIndex[_resolve("compression")].push_back(w_27);
                            c_20->add(std::make_unique<CalfWidgetItem>(w_27), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachY=2});
                            auto* w_28 = new CalfVuMeter(this, *meta.get_param_props(_resolve("compression")), _resolve("compression"));
                            w_28->setShowLabels(false);
                            fWidgets.emplace_back(w_28);
                            fByIndex[_resolve("compression")].push_back(w_28);
                            c_20->add(std::make_unique<CalfWidgetItem>(w_28), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2, .attachW=2});
                            c_19->add(std::move(c_20), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        }
                        {
                            auto c_29 = std::make_unique<CalfTableItem>(2, 3, true, 0, 0);
                            {
                                auto c_30 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_31 = new CalfLabel(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"), nullptr);
                                fWidgets.emplace_back(w_31);
                                fByIndex[_resolve("attack")].push_back(w_31);
                                c_30->add(std::make_unique<CalfWidgetItem>(w_31), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_32 = new CalfKnob(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"));
                                w_32->setShowLabels(false);
                                fWidgets.emplace_back(w_32);
                                fByIndex[_resolve("attack")].push_back(w_32);
                                c_30->add(std::make_unique<CalfWidgetItem>(w_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_33 = new CalfValue(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"));
                                fWidgets.emplace_back(w_33);
                                fByIndex[_resolve("attack")].push_back(w_33);
                                c_30->add(std::make_unique<CalfWidgetItem>(w_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_29->add(std::move(c_30), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_34 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_35 = new CalfLabel(this, *meta.get_param_props(_resolve("release")), _resolve("release"), nullptr);
                                fWidgets.emplace_back(w_35);
                                fByIndex[_resolve("release")].push_back(w_35);
                                c_34->add(std::make_unique<CalfWidgetItem>(w_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_36 = new CalfKnob(this, *meta.get_param_props(_resolve("release")), _resolve("release"));
                                w_36->setShowLabels(false);
                                fWidgets.emplace_back(w_36);
                                fByIndex[_resolve("release")].push_back(w_36);
                                c_34->add(std::make_unique<CalfWidgetItem>(w_36), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_37 = new CalfValue(this, *meta.get_param_props(_resolve("release")), _resolve("release"));
                                fWidgets.emplace_back(w_37);
                                fByIndex[_resolve("release")].push_back(w_37);
                                c_34->add(std::make_unique<CalfWidgetItem>(w_37), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_29->add(std::move(c_34), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachX=1});
                            }
                            {
                                auto c_38 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_39 = new CalfLabel(this, *meta.get_param_props(_resolve("knee")), _resolve("knee"), nullptr);
                                fWidgets.emplace_back(w_39);
                                fByIndex[_resolve("knee")].push_back(w_39);
                                c_38->add(std::make_unique<CalfWidgetItem>(w_39), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_40 = new CalfKnob(this, *meta.get_param_props(_resolve("knee")), _resolve("knee"));
                                w_40->setShowLabels(false);
                                fWidgets.emplace_back(w_40);
                                fByIndex[_resolve("knee")].push_back(w_40);
                                c_38->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_41 = new CalfValue(this, *meta.get_param_props(_resolve("knee")), _resolve("knee"));
                                fWidgets.emplace_back(w_41);
                                fByIndex[_resolve("knee")].push_back(w_41);
                                c_38->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_29->add(std::move(c_38), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachX=2});
                            }
                            {
                                auto c_42 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_43 = new CalfLabel(this, *meta.get_param_props(_resolve("ratio")), _resolve("ratio"), nullptr);
                                fWidgets.emplace_back(w_43);
                                fByIndex[_resolve("ratio")].push_back(w_43);
                                c_42->add(std::make_unique<CalfWidgetItem>(w_43), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_44 = new CalfKnob(this, *meta.get_param_props(_resolve("ratio")), _resolve("ratio"));
                                w_44->setShowLabels(false);
                                fWidgets.emplace_back(w_44);
                                fByIndex[_resolve("ratio")].push_back(w_44);
                                c_42->add(std::make_unique<CalfWidgetItem>(w_44), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_45 = new CalfValue(this, *meta.get_param_props(_resolve("ratio")), _resolve("ratio"));
                                fWidgets.emplace_back(w_45);
                                fByIndex[_resolve("ratio")].push_back(w_45);
                                c_42->add(std::make_unique<CalfWidgetItem>(w_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_29->add(std::move(c_42), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachY=1});
                            }
                            {
                                auto c_46 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_47 = new CalfLabel(this, *meta.get_param_props(_resolve("threshold")), _resolve("threshold"), nullptr);
                                fWidgets.emplace_back(w_47);
                                fByIndex[_resolve("threshold")].push_back(w_47);
                                c_46->add(std::make_unique<CalfWidgetItem>(w_47), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_48 = new CalfKnob(this, *meta.get_param_props(_resolve("threshold")), _resolve("threshold"));
                                w_48->setShowLabels(false);
                                fWidgets.emplace_back(w_48);
                                fByIndex[_resolve("threshold")].push_back(w_48);
                                c_46->add(std::make_unique<CalfWidgetItem>(w_48), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_49 = new CalfValue(this, *meta.get_param_props(_resolve("threshold")), _resolve("threshold"));
                                fWidgets.emplace_back(w_49);
                                fByIndex[_resolve("threshold")].push_back(w_49);
                                c_46->add(std::make_unique<CalfWidgetItem>(w_49), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_29->add(std::move(c_46), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                            }
                            {
                                auto c_50 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_51 = new CalfLabel(this, *meta.get_param_props(_resolve("makeup")), _resolve("makeup"), nullptr);
                                fWidgets.emplace_back(w_51);
                                fByIndex[_resolve("makeup")].push_back(w_51);
                                c_50->add(std::make_unique<CalfWidgetItem>(w_51), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_52 = new CalfKnob(this, *meta.get_param_props(_resolve("makeup")), _resolve("makeup"));
                                w_52->setShowLabels(false);
                                fWidgets.emplace_back(w_52);
                                fByIndex[_resolve("makeup")].push_back(w_52);
                                c_50->add(std::make_unique<CalfWidgetItem>(w_52), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_53 = new CalfValue(this, *meta.get_param_props(_resolve("makeup")), _resolve("makeup"));
                                fWidgets.emplace_back(w_53);
                                fByIndex[_resolve("makeup")].push_back(w_53);
                                c_50->add(std::make_unique<CalfWidgetItem>(w_53), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_29->add(std::move(c_50), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                            }
                            c_19->add(std::move(c_29), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_54 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, true);
                            {
                                auto c_55 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_56 = new CalfLabel(this, *meta.get_param_props(_resolve("stereo_link")), _resolve("stereo_link"), nullptr);
                                fWidgets.emplace_back(w_56);
                                fByIndex[_resolve("stereo_link")].push_back(w_56);
                                c_55->add(std::make_unique<CalfWidgetItem>(w_56), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false});
                                auto* w_57 = new CalfComboBox(this, *meta.get_param_props(_resolve("stereo_link")), _resolve("stereo_link"));
                                w_57->setShowLabels(false);
                                fWidgets.emplace_back(w_57);
                                fByIndex[_resolve("stereo_link")].push_back(w_57);
                                c_55->add(std::make_unique<CalfWidgetItem>(w_57), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_54->add(std::move(c_55), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_58 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_59 = new CalfLabel(this, *meta.get_param_props(_resolve("detection")), _resolve("detection"), nullptr);
                                fWidgets.emplace_back(w_59);
                                fByIndex[_resolve("detection")].push_back(w_59);
                                c_58->add(std::make_unique<CalfWidgetItem>(w_59), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false});
                                auto* w_60 = new CalfComboBox(this, *meta.get_param_props(_resolve("detection")), _resolve("detection"));
                                w_60->setShowLabels(false);
                                fWidgets.emplace_back(w_60);
                                fByIndex[_resolve("detection")].push_back(w_60);
                                c_58->add(std::make_unique<CalfWidgetItem>(w_60), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_54->add(std::move(c_58), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            c_19->add(std::move(c_54), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        c_18->add(std::move(c_19), CalfPacking{});
                    }
                    auto c_17 = std::make_unique<CalfFrameItem>("Compressor", std::move(c_18));
                    c_16->add(std::move(c_17), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_16), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            {
                auto c_62 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_63 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    auto* w_64 = new CalfLineGraph(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"), 320, 320);
                    fLineGraphs.push_back({ w_64, static_cast<int>(_resolve("level_in")) });
                    w_64->setSize(static_cast<uint>(320), static_cast<uint>(320));
                    fWidgets.emplace_back(w_64);
                    fByIndex[_resolve("level_in")].push_back(w_64);
                    c_63->add(std::make_unique<CalfWidgetItem>(w_64), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_62->add(std::move(c_63), CalfPacking{});
                }
                auto c_61 = std::make_unique<CalfFrameItem>("Compression", std::move(c_62));
                c_1->add(std::move(c_61), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);

        // Shadow module: same DSP class as the running plugin, instantiated
        // UI-side just so <line-graph> widgets can query line_graph_iface
        // synchronously during paint.
        fShadow = std::make_unique<calf_plugins::compressor_audio_module>();
        fShadowParams.assign(Meta::param_count, 0.0f);
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            fShadowParams[i] = meta.get_param_props(static_cast<int>(i))->def_value;
            fShadow->params[i] = &fShadowParams[i];
        }
        fShadow->post_instantiate(48000);
        fShadow->set_sample_rate(48000);
        fShadow->params_changed();
        fShadow->activate();
        // Not every Calf module inherits line_graph_iface — only the
        // ones that draw curves do. Cross-cast at runtime; null means
        // "this plugin has no curves to draw, paint the placeholder".
        const calf_plugins::line_graph_iface* _lg =
            dynamic_cast<const calf_plugins::line_graph_iface*>(fShadow.get());
        if (_lg) {
            for (auto& g : fLineGraphs)
                g.w->setGraphSource(_lg, g.idx);
        }
    }

protected:
    void onNanoDisplay() override
    {
        const float w = static_cast<float>(getWidth());
        const float h = static_cast<float>(getHeight());

        // Themed background: stretch the GTK Calf_Default plugin
        // background across the whole UI. Falls back to the dark flat
        // fill if the asset failed to decode.
        beginPath();
        rect(0, 0, w, h);
        NanoImage* _bg = fTheme.image("background_plugin.png");
        if (_bg && _bg->isValid()) {
            fillPaint(imagePattern(0, 0, w, h, 0.0f, *_bg, 1.0f));
        } else {
            fillColor(Color(0.12f, 0.12f, 0.14f));
        }
        fill();

        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it != fByIndex.end())
            for (auto* w : it->second) w->setValue(value, /*notify=*/false);
        if (fShadow && index < fShadowParams.size()) {
            fShadowParams[index] = value;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
        if (fShadow && w->getParamIndex() < fShadowParams.size()) {
            fShadowParams[w->getParamIndex()] = v;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    // No-op for WANT_STATE plugins (Monosynth, Organ, FluidSynth, Wavetable).
    // Codegen UIs don't yet visualise state keys (organ presets, wavetable
    // data, SF2 path, modmatrix rows); hand-written subclasses can override.
    // DPF only declares stateChanged when the plugin opts in, so guard.
#if DISTRHO_PLUGIN_WANT_STATE
    void stateChanged(const char* /*key*/, const char* /*value*/) override {}
#endif

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    CalfTheme                                         fTheme{*this};
    std::unique_ptr<calf_plugins::compressor_audio_module> fShadow;
    std::vector<float>                            fShadowParams;
    struct LineGraphRef { CalfLineGraph* w; int idx; };
    std::vector<LineGraphRef>                     fLineGraphs;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(CompressorUI)
};

UI* createUI() { return new CompressorUI(); }

END_NAMESPACE_DISTRHO
