/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/bassenhancer.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLed.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include "CalfVuMeter.hpp"
#include <calf/metadata.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLed;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfVuMeter;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class BassEnhancerUI : public UI, public CalfWidgetBase::Callback
{
public:
    BassEnhancerUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = bassenhancer_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 10, false);
            {
                auto c_2 = std::make_unique<CalfTableItem>(4, 7, false, 0, 0);
                auto* w_3 = new CalfLabel(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"), nullptr);
                fWidgets.emplace_back(w_3);
                fByIndex[_resolve("bypass")].push_back(w_3);
                c_2->add(std::make_unique<CalfWidgetItem>(w_3), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true});
                auto* w_4 = new CalfToggle(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"));
                w_4->setShowLabels(false);
                fWidgets.emplace_back(w_4);
                fByIndex[_resolve("bypass")].push_back(w_4);
                c_2->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachY=1, .attachH=2});
                auto* w_5 = new CalfLabel(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"), nullptr);
                fWidgets.emplace_back(w_5);
                fByIndex[_resolve("level_in")].push_back(w_5);
                c_2->add(std::make_unique<CalfWidgetItem>(w_5), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=1});
                auto* w_6 = new CalfKnob(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                w_6->setShowLabels(false);
                fWidgets.emplace_back(w_6);
                fByIndex[_resolve("level_in")].push_back(w_6);
                c_2->add(std::make_unique<CalfWidgetItem>(w_6), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=1, .attachY=1, .attachH=2});
                auto* w_7 = new CalfValue(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                fWidgets.emplace_back(w_7);
                fByIndex[_resolve("level_in")].push_back(w_7);
                c_2->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=1, .attachY=3});
                auto* w_8 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_in")), _resolve("meter_in"), nullptr);
                fWidgets.emplace_back(w_8);
                fByIndex[_resolve("meter_in")].push_back(w_8);
                c_2->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                auto* w_9 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_in")), _resolve("meter_in"));
                w_9->setShowLabels(false);
                fWidgets.emplace_back(w_9);
                fByIndex[_resolve("meter_in")].push_back(w_9);
                c_2->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                auto* w_10 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_out")), _resolve("meter_out"));
                w_10->setShowLabels(false);
                fWidgets.emplace_back(w_10);
                fByIndex[_resolve("meter_out")].push_back(w_10);
                c_2->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=2});
                auto* w_11 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_out")), _resolve("meter_out"), nullptr);
                fWidgets.emplace_back(w_11);
                fByIndex[_resolve("meter_out")].push_back(w_11);
                c_2->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=3});
                auto* w_12 = new CalfLabel(this, *meta.get_param_props(_resolve("clip_in")), _resolve("clip_in"), nullptr);
                fWidgets.emplace_back(w_12);
                fByIndex[_resolve("clip_in")].push_back(w_12);
                c_2->add(std::make_unique<CalfWidgetItem>(w_12), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=3});
                auto* w_13 = new CalfLed(this, *meta.get_param_props(_resolve("clip_in")), _resolve("clip_in"));
                w_13->setShowLabels(false);
                fWidgets.emplace_back(w_13);
                fByIndex[_resolve("clip_in")].push_back(w_13);
                c_2->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=3, .attachY=1});
                auto* w_14 = new CalfLed(this, *meta.get_param_props(_resolve("clip_out")), _resolve("clip_out"));
                w_14->setShowLabels(false);
                fWidgets.emplace_back(w_14);
                fByIndex[_resolve("clip_out")].push_back(w_14);
                c_2->add(std::make_unique<CalfWidgetItem>(w_14), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=3, .attachY=2});
                auto* w_15 = new CalfLabel(this, *meta.get_param_props(_resolve("clip_out")), _resolve("clip_out"), nullptr);
                fWidgets.emplace_back(w_15);
                fByIndex[_resolve("clip_out")].push_back(w_15);
                c_2->add(std::make_unique<CalfWidgetItem>(w_15), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=3, .attachY=3});
                auto* w_16 = new CalfLabel(this, *meta.get_param_props(_resolve("amount")), _resolve("amount"), nullptr);
                fWidgets.emplace_back(w_16);
                fByIndex[_resolve("amount")].push_back(w_16);
                c_2->add(std::make_unique<CalfWidgetItem>(w_16), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=4});
                auto* w_17 = new CalfKnob(this, *meta.get_param_props(_resolve("amount")), _resolve("amount"));
                w_17->setShowLabels(false);
                fWidgets.emplace_back(w_17);
                fByIndex[_resolve("amount")].push_back(w_17);
                c_2->add(std::make_unique<CalfWidgetItem>(w_17), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=4, .attachY=1, .attachH=2});
                auto* w_18 = new CalfValue(this, *meta.get_param_props(_resolve("amount")), _resolve("amount"));
                fWidgets.emplace_back(w_18);
                fByIndex[_resolve("amount")].push_back(w_18);
                c_2->add(std::make_unique<CalfWidgetItem>(w_18), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=4, .attachY=3});
                auto* w_19 = new CalfLabel(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"), nullptr);
                fWidgets.emplace_back(w_19);
                fByIndex[_resolve("level_out")].push_back(w_19);
                c_2->add(std::make_unique<CalfWidgetItem>(w_19), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=5});
                auto* w_20 = new CalfKnob(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                w_20->setShowLabels(false);
                fWidgets.emplace_back(w_20);
                fByIndex[_resolve("level_out")].push_back(w_20);
                c_2->add(std::make_unique<CalfWidgetItem>(w_20), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=5, .attachY=1, .attachH=2});
                auto* w_21 = new CalfValue(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                fWidgets.emplace_back(w_21);
                fByIndex[_resolve("level_out")].push_back(w_21);
                c_2->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=5, .attachY=3});
                auto* w_22 = new CalfLabel(this, *meta.get_param_props(_resolve("listen")), _resolve("listen"), nullptr);
                fWidgets.emplace_back(w_22);
                fByIndex[_resolve("listen")].push_back(w_22);
                c_2->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=6});
                auto* w_23 = new CalfToggle(this, *meta.get_param_props(_resolve("listen")), _resolve("listen"));
                w_23->setShowLabels(false);
                fWidgets.emplace_back(w_23);
                fByIndex[_resolve("listen")].push_back(w_23);
                c_2->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=6, .attachY=1, .attachH=2});
                c_1->add(std::move(c_2), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            {
                auto c_25 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_26 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 25, false);
                    {
                        auto c_27 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_28 = new CalfLabel(this, *meta.get_param_props(_resolve("drive")), _resolve("drive"), nullptr);
                        fWidgets.emplace_back(w_28);
                        fByIndex[_resolve("drive")].push_back(w_28);
                        c_27->add(std::make_unique<CalfWidgetItem>(w_28), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_29 = new CalfKnob(this, *meta.get_param_props(_resolve("drive")), _resolve("drive"));
                        w_29->setShowLabels(false);
                        fWidgets.emplace_back(w_29);
                        fByIndex[_resolve("drive")].push_back(w_29);
                        c_27->add(std::make_unique<CalfWidgetItem>(w_29), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_30 = new CalfValue(this, *meta.get_param_props(_resolve("drive")), _resolve("drive"));
                        fWidgets.emplace_back(w_30);
                        fByIndex[_resolve("drive")].push_back(w_30);
                        c_27->add(std::make_unique<CalfWidgetItem>(w_30), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_27), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_31 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        auto* w_32 = new CalfLabel(this, *meta.get_param_props(_resolve("blend")), _resolve("blend"), nullptr);
                        fWidgets.emplace_back(w_32);
                        fByIndex[_resolve("blend")].push_back(w_32);
                        c_31->add(std::make_unique<CalfWidgetItem>(w_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_33 = new CalfKnob(this, *meta.get_param_props(_resolve("blend")), _resolve("blend"));
                        w_33->setShowLabels(false);
                        fWidgets.emplace_back(w_33);
                        fByIndex[_resolve("blend")].push_back(w_33);
                        c_31->add(std::make_unique<CalfWidgetItem>(w_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        {
                            auto c_34 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, false);
                            auto* w_35 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "3rd");
                            fWidgets.emplace_back(w_35);
                            c_34->add(std::make_unique<CalfWidgetItem>(w_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_36 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "2nd");
                            fWidgets.emplace_back(w_36);
                            c_34->add(std::make_unique<CalfWidgetItem>(w_36), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_31->add(std::move(c_34), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        auto* w_37 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_drive")), _resolve("meter_drive"), nullptr);
                        fWidgets.emplace_back(w_37);
                        fByIndex[_resolve("meter_drive")].push_back(w_37);
                        c_31->add(std::make_unique<CalfWidgetItem>(w_37), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_38 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_drive")), _resolve("meter_drive"));
                        w_38->setShowLabels(false);
                        fWidgets.emplace_back(w_38);
                        fByIndex[_resolve("meter_drive")].push_back(w_38);
                        c_31->add(std::make_unique<CalfWidgetItem>(w_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_31), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_39 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_40 = new CalfLabel(this, *meta.get_param_props(_resolve("freq")), _resolve("freq"), nullptr);
                        fWidgets.emplace_back(w_40);
                        fByIndex[_resolve("freq")].push_back(w_40);
                        c_39->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_41 = new CalfKnob(this, *meta.get_param_props(_resolve("freq")), _resolve("freq"));
                        w_41->setShowLabels(false);
                        fWidgets.emplace_back(w_41);
                        fByIndex[_resolve("freq")].push_back(w_41);
                        c_39->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_42 = new CalfValue(this, *meta.get_param_props(_resolve("freq")), _resolve("freq"));
                        fWidgets.emplace_back(w_42);
                        fByIndex[_resolve("freq")].push_back(w_42);
                        c_39->add(std::make_unique<CalfWidgetItem>(w_42), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_39), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_43 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_44 = new CalfLabel(this, *meta.get_param_props(_resolve("floor")), _resolve("floor"), nullptr);
                        fWidgets.emplace_back(w_44);
                        fByIndex[_resolve("floor")].push_back(w_44);
                        c_43->add(std::make_unique<CalfWidgetItem>(w_44), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_45 = new CalfToggle(this, *meta.get_param_props(_resolve("floor_active")), _resolve("floor_active"));
                        w_45->setShowLabels(false);
                        fWidgets.emplace_back(w_45);
                        fByIndex[_resolve("floor_active")].push_back(w_45);
                        c_43->add(std::make_unique<CalfWidgetItem>(w_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_46 = new CalfKnob(this, *meta.get_param_props(_resolve("floor")), _resolve("floor"));
                        w_46->setShowLabels(false);
                        fWidgets.emplace_back(w_46);
                        fByIndex[_resolve("floor")].push_back(w_46);
                        c_43->add(std::make_unique<CalfWidgetItem>(w_46), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_47 = new CalfValue(this, *meta.get_param_props(_resolve("floor")), _resolve("floor"));
                        w_47->setSize(static_cast<uint>(5), static_cast<uint>(w_47->getHeight()));
                        fWidgets.emplace_back(w_47);
                        fByIndex[_resolve("floor")].push_back(w_47);
                        c_43->add(std::make_unique<CalfWidgetItem>(w_47), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_26->add(std::move(c_43), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_25->add(std::move(c_26), CalfPacking{});
                }
                auto c_24 = std::make_unique<CalfFrameItem>("Bass Enhancer", std::move(c_25));
                c_1->add(std::move(c_24), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);
    }

protected:
    void onNanoDisplay() override
    {
        beginPath();
        rect(0, 0, getWidth(), getHeight());
        fillColor(Color(0.12f, 0.12f, 0.14f));
        fill();
        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it == fByIndex.end()) return;
        for (auto* w : it->second) w->setValue(value, /*notify=*/false);
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
    }

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(BassEnhancerUI)
};

UI* createUI() { return new BassEnhancerUI(); }

END_NAMESPACE_DISTRHO
