/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/sidechaingate.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfComboBox.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLed.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include "CalfVuMeter.hpp"
#include <calf/metadata.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfComboBox;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLed;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfVuMeter;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class SidechainGateUI : public UI, public CalfWidgetBase::Callback
{
public:
    SidechainGateUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = sidechaingate_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 8, false);
            {
                auto c_2 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 20, false);
                {
                    auto c_3 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 7, false);
                    auto* w_4 = new CalfLabel(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"), nullptr);
                    fWidgets.emplace_back(w_4);
                    fByIndex[_resolve("bypass")].push_back(w_4);
                    c_3->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    {
                        auto c_6 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_7 = new CalfToggle(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"));
                        w_7->setShowLabels(false);
                        fWidgets.emplace_back(w_7);
                        fByIndex[_resolve("bypass")].push_back(w_7);
                        c_6->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{});
                        auto c_5 = std::make_unique<CalfAlignItem>(std::move(c_6), 0.5f, 0.5f, 0.0f, 0.0f);
                        c_3->add(std::move(c_5), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_2->add(std::move(c_3), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false, .padX=7, .padY=7});
                }
                auto* w_8 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                fWidgets.emplace_back(w_8);
                c_2->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                {
                    auto c_9 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                    auto* w_10 = new CalfLabel(this, *meta.get_param_props(_resolve("range")), _resolve("range"), nullptr);
                    fWidgets.emplace_back(w_10);
                    fByIndex[_resolve("range")].push_back(w_10);
                    c_9->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_11 = new CalfKnob(this, *meta.get_param_props(_resolve("range")), _resolve("range"));
                    w_11->setShowLabels(false);
                    fWidgets.emplace_back(w_11);
                    fByIndex[_resolve("range")].push_back(w_11);
                    c_9->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_12 = new CalfValue(this, *meta.get_param_props(_resolve("range")), _resolve("range"));
                    fWidgets.emplace_back(w_12);
                    fByIndex[_resolve("range")].push_back(w_12);
                    c_9->add(std::make_unique<CalfWidgetItem>(w_12), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_2->add(std::move(c_9), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false, .padX=7, .padY=20, .attachY=1});
                }
                c_1->add(std::move(c_2), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
            }
            {
                auto c_13 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_15 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_16 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        {
                            auto c_17 = std::make_unique<CalfTableItem>(2, 3, false, 0, 0);
                            auto* w_18 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_in")), _resolve("meter_in"), nullptr);
                            fWidgets.emplace_back(w_18);
                            fByIndex[_resolve("meter_in")].push_back(w_18);
                            c_17->add(std::make_unique<CalfWidgetItem>(w_18), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                            auto* w_19 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_in")), _resolve("meter_in"));
                            w_19->setShowLabels(false);
                            fWidgets.emplace_back(w_19);
                            fByIndex[_resolve("meter_in")].push_back(w_19);
                            c_17->add(std::make_unique<CalfWidgetItem>(w_19), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false, .attachX=1});
                            auto* w_20 = new CalfLed(this, *meta.get_param_props(_resolve("clip_in")), _resolve("clip_in"));
                            w_20->setShowLabels(false);
                            fWidgets.emplace_back(w_20);
                            fByIndex[_resolve("clip_in")].push_back(w_20);
                            c_17->add(std::make_unique<CalfWidgetItem>(w_20), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false, .attachX=2});
                            auto* w_21 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_out")), _resolve("meter_out"), nullptr);
                            fWidgets.emplace_back(w_21);
                            fByIndex[_resolve("meter_out")].push_back(w_21);
                            c_17->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false, .attachY=1});
                            auto* w_22 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_out")), _resolve("meter_out"));
                            w_22->setShowLabels(false);
                            fWidgets.emplace_back(w_22);
                            fByIndex[_resolve("meter_out")].push_back(w_22);
                            c_17->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false, .attachX=1, .attachY=1});
                            auto* w_23 = new CalfLed(this, *meta.get_param_props(_resolve("clip_out")), _resolve("clip_out"));
                            w_23->setShowLabels(false);
                            fWidgets.emplace_back(w_23);
                            fByIndex[_resolve("clip_out")].push_back(w_23);
                            c_17->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false, .attachX=2, .attachY=1});
                            c_16->add(std::move(c_17), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        }
                        {
                            auto c_24 = std::make_unique<CalfTableItem>(2, 3, true, 0, 0);
                            {
                                auto c_25 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_26 = new CalfLabel(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"), nullptr);
                                fWidgets.emplace_back(w_26);
                                fByIndex[_resolve("attack")].push_back(w_26);
                                c_25->add(std::make_unique<CalfWidgetItem>(w_26), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_27 = new CalfKnob(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"));
                                w_27->setShowLabels(false);
                                fWidgets.emplace_back(w_27);
                                fByIndex[_resolve("attack")].push_back(w_27);
                                c_25->add(std::make_unique<CalfWidgetItem>(w_27), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_28 = new CalfValue(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"));
                                fWidgets.emplace_back(w_28);
                                fByIndex[_resolve("attack")].push_back(w_28);
                                c_25->add(std::make_unique<CalfWidgetItem>(w_28), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_24->add(std::move(c_25), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_29 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_30 = new CalfLabel(this, *meta.get_param_props(_resolve("release")), _resolve("release"), nullptr);
                                fWidgets.emplace_back(w_30);
                                fByIndex[_resolve("release")].push_back(w_30);
                                c_29->add(std::make_unique<CalfWidgetItem>(w_30), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_31 = new CalfKnob(this, *meta.get_param_props(_resolve("release")), _resolve("release"));
                                w_31->setShowLabels(false);
                                fWidgets.emplace_back(w_31);
                                fByIndex[_resolve("release")].push_back(w_31);
                                c_29->add(std::make_unique<CalfWidgetItem>(w_31), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_32 = new CalfValue(this, *meta.get_param_props(_resolve("release")), _resolve("release"));
                                fWidgets.emplace_back(w_32);
                                fByIndex[_resolve("release")].push_back(w_32);
                                c_29->add(std::make_unique<CalfWidgetItem>(w_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_24->add(std::move(c_29), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                            }
                            {
                                auto c_33 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_34 = new CalfLabel(this, *meta.get_param_props(_resolve("knee")), _resolve("knee"), nullptr);
                                fWidgets.emplace_back(w_34);
                                fByIndex[_resolve("knee")].push_back(w_34);
                                c_33->add(std::make_unique<CalfWidgetItem>(w_34), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_35 = new CalfKnob(this, *meta.get_param_props(_resolve("knee")), _resolve("knee"));
                                w_35->setShowLabels(false);
                                fWidgets.emplace_back(w_35);
                                fByIndex[_resolve("knee")].push_back(w_35);
                                c_33->add(std::make_unique<CalfWidgetItem>(w_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_36 = new CalfValue(this, *meta.get_param_props(_resolve("knee")), _resolve("knee"));
                                fWidgets.emplace_back(w_36);
                                fByIndex[_resolve("knee")].push_back(w_36);
                                c_33->add(std::make_unique<CalfWidgetItem>(w_36), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_24->add(std::move(c_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                            }
                            {
                                auto c_37 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_38 = new CalfLabel(this, *meta.get_param_props(_resolve("ratio")), _resolve("ratio"), nullptr);
                                fWidgets.emplace_back(w_38);
                                fByIndex[_resolve("ratio")].push_back(w_38);
                                c_37->add(std::make_unique<CalfWidgetItem>(w_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_39 = new CalfKnob(this, *meta.get_param_props(_resolve("ratio")), _resolve("ratio"));
                                w_39->setShowLabels(false);
                                fWidgets.emplace_back(w_39);
                                fByIndex[_resolve("ratio")].push_back(w_39);
                                c_37->add(std::make_unique<CalfWidgetItem>(w_39), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_40 = new CalfValue(this, *meta.get_param_props(_resolve("ratio")), _resolve("ratio"));
                                fWidgets.emplace_back(w_40);
                                fByIndex[_resolve("ratio")].push_back(w_40);
                                c_37->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_24->add(std::move(c_37), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                            }
                            {
                                auto c_41 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_42 = new CalfLabel(this, *meta.get_param_props(_resolve("threshold")), _resolve("threshold"), nullptr);
                                fWidgets.emplace_back(w_42);
                                fByIndex[_resolve("threshold")].push_back(w_42);
                                c_41->add(std::make_unique<CalfWidgetItem>(w_42), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_43 = new CalfKnob(this, *meta.get_param_props(_resolve("threshold")), _resolve("threshold"));
                                w_43->setShowLabels(false);
                                fWidgets.emplace_back(w_43);
                                fByIndex[_resolve("threshold")].push_back(w_43);
                                c_41->add(std::make_unique<CalfWidgetItem>(w_43), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_44 = new CalfValue(this, *meta.get_param_props(_resolve("threshold")), _resolve("threshold"));
                                fWidgets.emplace_back(w_44);
                                fByIndex[_resolve("threshold")].push_back(w_44);
                                c_41->add(std::make_unique<CalfWidgetItem>(w_44), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_24->add(std::move(c_41), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                            }
                            {
                                auto c_45 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_46 = new CalfLabel(this, *meta.get_param_props(_resolve("makeup")), _resolve("makeup"), nullptr);
                                fWidgets.emplace_back(w_46);
                                fByIndex[_resolve("makeup")].push_back(w_46);
                                c_45->add(std::make_unique<CalfWidgetItem>(w_46), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_47 = new CalfKnob(this, *meta.get_param_props(_resolve("makeup")), _resolve("makeup"));
                                w_47->setShowLabels(false);
                                fWidgets.emplace_back(w_47);
                                fByIndex[_resolve("makeup")].push_back(w_47);
                                c_45->add(std::make_unique<CalfWidgetItem>(w_47), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_48 = new CalfValue(this, *meta.get_param_props(_resolve("makeup")), _resolve("makeup"));
                                fWidgets.emplace_back(w_48);
                                fByIndex[_resolve("makeup")].push_back(w_48);
                                c_45->add(std::make_unique<CalfWidgetItem>(w_48), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_24->add(std::move(c_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                            }
                            c_16->add(std::move(c_24), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        c_15->add(std::move(c_16), CalfPacking{});
                    }
                    auto c_14 = std::make_unique<CalfFrameItem>("Gate", std::move(c_15));
                    c_13->add(std::move(c_14), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_50 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_51 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, false);
                        {
                            auto c_52 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_53 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Active");
                            fWidgets.emplace_back(w_53);
                            c_52->add(std::make_unique<CalfWidgetItem>(w_53), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                            auto* w_54 = new CalfToggle(this, *meta.get_param_props(_resolve("sc_route")), _resolve("sc_route"));
                            w_54->setShowLabels(false);
                            fWidgets.emplace_back(w_54);
                            fByIndex[_resolve("sc_route")].push_back(w_54);
                            c_52->add(std::make_unique<CalfWidgetItem>(w_54), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                            auto* w_55 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                            fWidgets.emplace_back(w_55);
                            c_52->add(std::make_unique<CalfWidgetItem>(w_55), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_51->add(std::move(c_52), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_56 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_57 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Level");
                            fWidgets.emplace_back(w_57);
                            c_56->add(std::make_unique<CalfWidgetItem>(w_57), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false, .attachY=3});
                            auto* w_58 = new CalfKnob(this, *meta.get_param_props(_resolve("sc_level")), _resolve("sc_level"));
                            w_58->setShowLabels(false);
                            fWidgets.emplace_back(w_58);
                            fByIndex[_resolve("sc_level")].push_back(w_58);
                            c_56->add(std::make_unique<CalfWidgetItem>(w_58), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false, .attachX=1, .attachY=3});
                            auto* w_59 = new CalfValue(this, *meta.get_param_props(_resolve("sc_level")), _resolve("sc_level"));
                            fWidgets.emplace_back(w_59);
                            fByIndex[_resolve("sc_level")].push_back(w_59);
                            c_56->add(std::make_unique<CalfWidgetItem>(w_59), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false, .attachX=2, .attachY=3});
                            c_51->add(std::move(c_56), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_60 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_61 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Listen");
                            fWidgets.emplace_back(w_61);
                            c_60->add(std::make_unique<CalfWidgetItem>(w_61), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                            auto* w_62 = new CalfToggle(this, *meta.get_param_props(_resolve("sc_listen")), _resolve("sc_listen"));
                            w_62->setShowLabels(false);
                            fWidgets.emplace_back(w_62);
                            fByIndex[_resolve("sc_listen")].push_back(w_62);
                            c_60->add(std::make_unique<CalfWidgetItem>(w_62), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                            auto* w_63 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                            fWidgets.emplace_back(w_63);
                            c_60->add(std::make_unique<CalfWidgetItem>(w_63), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_51->add(std::move(c_60), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        c_50->add(std::move(c_51), CalfPacking{});
                    }
                    auto c_49 = std::make_unique<CalfFrameItem>("Sidechain", std::move(c_50));
                    c_13->add(std::move(c_49), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_13), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            {
                auto c_65 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_66 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 8, false);
                    auto* w_67 = new CalfLineGraph(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"), 265, 265);
                    w_67->setSize(static_cast<uint>(265), static_cast<uint>(265));
                    fWidgets.emplace_back(w_67);
                    fByIndex[_resolve("bypass")].push_back(w_67);
                    c_66->add(std::make_unique<CalfWidgetItem>(w_67), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_68 = new CalfVuMeter(this, *meta.get_param_props(_resolve("gating")), _resolve("gating"));
                    w_68->setShowLabels(false);
                    fWidgets.emplace_back(w_68);
                    fByIndex[_resolve("gating")].push_back(w_68);
                    c_66->add(std::make_unique<CalfWidgetItem>(w_68), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_65->add(std::move(c_66), CalfPacking{});
                }
                auto c_64 = std::make_unique<CalfFrameItem>("Gating", std::move(c_65));
                c_1->add(std::move(c_64), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            {
                auto c_69 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                {
                    auto c_71 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_72 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, true);
                        {
                            auto c_73 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_74 = new CalfLabel(this, *meta.get_param_props(_resolve("stereo_link")), _resolve("stereo_link"), nullptr);
                            fWidgets.emplace_back(w_74);
                            fByIndex[_resolve("stereo_link")].push_back(w_74);
                            c_73->add(std::make_unique<CalfWidgetItem>(w_74), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false});
                            auto* w_75 = new CalfComboBox(this, *meta.get_param_props(_resolve("stereo_link")), _resolve("stereo_link"));
                            w_75->setShowLabels(false);
                            fWidgets.emplace_back(w_75);
                            fByIndex[_resolve("stereo_link")].push_back(w_75);
                            c_73->add(std::make_unique<CalfWidgetItem>(w_75), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_72->add(std::move(c_73), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_76 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_77 = new CalfLabel(this, *meta.get_param_props(_resolve("detection")), _resolve("detection"), nullptr);
                            fWidgets.emplace_back(w_77);
                            fByIndex[_resolve("detection")].push_back(w_77);
                            c_76->add(std::make_unique<CalfWidgetItem>(w_77), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false});
                            auto* w_78 = new CalfComboBox(this, *meta.get_param_props(_resolve("detection")), _resolve("detection"));
                            w_78->setShowLabels(false);
                            fWidgets.emplace_back(w_78);
                            fByIndex[_resolve("detection")].push_back(w_78);
                            c_76->add(std::make_unique<CalfWidgetItem>(w_78), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_72->add(std::move(c_76), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        c_71->add(std::move(c_72), CalfPacking{});
                    }
                    auto c_70 = std::make_unique<CalfFrameItem>("Options", std::move(c_71));
                    c_69->add(std::move(c_70), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_80 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_81 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 8, false);
                        auto* w_82 = new CalfLineGraph(this, *meta.get_param_props(_resolve("sc_listen")), _resolve("sc_listen"), 235, 112);
                        w_82->setSize(static_cast<uint>(235), static_cast<uint>(112));
                        fWidgets.emplace_back(w_82);
                        fByIndex[_resolve("sc_listen")].push_back(w_82);
                        c_81->add(std::make_unique<CalfWidgetItem>(w_82), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_83 = new CalfComboBox(this, *meta.get_param_props(_resolve("sc_mode")), _resolve("sc_mode"));
                        w_83->setShowLabels(false);
                        fWidgets.emplace_back(w_83);
                        fByIndex[_resolve("sc_mode")].push_back(w_83);
                        c_81->add(std::make_unique<CalfWidgetItem>(w_83), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        c_80->add(std::move(c_81), CalfPacking{});
                    }
                    auto c_79 = std::make_unique<CalfFrameItem>("S/C Filter", std::move(c_80));
                    c_69->add(std::move(c_79), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_84 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 8, false);
                    {
                        auto c_86 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        {
                            auto c_87 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, false);
                            {
                                auto c_88 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_89 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Active");
                                fWidgets.emplace_back(w_89);
                                c_88->add(std::make_unique<CalfWidgetItem>(w_89), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_90 = new CalfLed(this, *meta.get_param_props(_resolve("f1_active")), _resolve("f1_active"));
                                w_90->setShowLabels(false);
                                fWidgets.emplace_back(w_90);
                                fByIndex[_resolve("f1_active")].push_back(w_90);
                                c_88->add(std::make_unique<CalfWidgetItem>(w_90), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_91 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                                fWidgets.emplace_back(w_91);
                                c_88->add(std::make_unique<CalfWidgetItem>(w_91), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_87->add(std::move(c_88), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_92 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_93 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Freq");
                                fWidgets.emplace_back(w_93);
                                c_92->add(std::make_unique<CalfWidgetItem>(w_93), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_94 = new CalfKnob(this, *meta.get_param_props(_resolve("f1_freq")), _resolve("f1_freq"));
                                w_94->setShowLabels(false);
                                fWidgets.emplace_back(w_94);
                                fByIndex[_resolve("f1_freq")].push_back(w_94);
                                c_92->add(std::make_unique<CalfWidgetItem>(w_94), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_95 = new CalfValue(this, *meta.get_param_props(_resolve("f1_freq")), _resolve("f1_freq"));
                                fWidgets.emplace_back(w_95);
                                fByIndex[_resolve("f1_freq")].push_back(w_95);
                                c_92->add(std::make_unique<CalfWidgetItem>(w_95), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_87->add(std::move(c_92), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_96 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_97 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Level");
                                fWidgets.emplace_back(w_97);
                                c_96->add(std::make_unique<CalfWidgetItem>(w_97), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_98 = new CalfKnob(this, *meta.get_param_props(_resolve("f1_level")), _resolve("f1_level"));
                                w_98->setShowLabels(false);
                                fWidgets.emplace_back(w_98);
                                fByIndex[_resolve("f1_level")].push_back(w_98);
                                c_96->add(std::make_unique<CalfWidgetItem>(w_98), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_99 = new CalfValue(this, *meta.get_param_props(_resolve("f1_level")), _resolve("f1_level"));
                                fWidgets.emplace_back(w_99);
                                fByIndex[_resolve("f1_level")].push_back(w_99);
                                c_96->add(std::make_unique<CalfWidgetItem>(w_99), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_87->add(std::move(c_96), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            c_86->add(std::move(c_87), CalfPacking{});
                        }
                        auto c_85 = std::make_unique<CalfFrameItem>("Filter 1", std::move(c_86));
                        c_84->add(std::move(c_85), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_101 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        {
                            auto c_102 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, false);
                            {
                                auto c_103 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_104 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Active");
                                fWidgets.emplace_back(w_104);
                                c_103->add(std::make_unique<CalfWidgetItem>(w_104), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_105 = new CalfLed(this, *meta.get_param_props(_resolve("f2_active")), _resolve("f2_active"));
                                w_105->setShowLabels(false);
                                fWidgets.emplace_back(w_105);
                                fByIndex[_resolve("f2_active")].push_back(w_105);
                                c_103->add(std::make_unique<CalfWidgetItem>(w_105), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_106 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                                fWidgets.emplace_back(w_106);
                                c_103->add(std::make_unique<CalfWidgetItem>(w_106), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_102->add(std::move(c_103), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_107 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_108 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Freq");
                                fWidgets.emplace_back(w_108);
                                c_107->add(std::make_unique<CalfWidgetItem>(w_108), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_109 = new CalfKnob(this, *meta.get_param_props(_resolve("f2_freq")), _resolve("f2_freq"));
                                w_109->setShowLabels(false);
                                fWidgets.emplace_back(w_109);
                                fByIndex[_resolve("f2_freq")].push_back(w_109);
                                c_107->add(std::make_unique<CalfWidgetItem>(w_109), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_110 = new CalfValue(this, *meta.get_param_props(_resolve("f2_freq")), _resolve("f2_freq"));
                                fWidgets.emplace_back(w_110);
                                fByIndex[_resolve("f2_freq")].push_back(w_110);
                                c_107->add(std::make_unique<CalfWidgetItem>(w_110), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_102->add(std::move(c_107), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_111 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_112 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Level");
                                fWidgets.emplace_back(w_112);
                                c_111->add(std::make_unique<CalfWidgetItem>(w_112), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_113 = new CalfKnob(this, *meta.get_param_props(_resolve("f2_level")), _resolve("f2_level"));
                                w_113->setShowLabels(false);
                                fWidgets.emplace_back(w_113);
                                fByIndex[_resolve("f2_level")].push_back(w_113);
                                c_111->add(std::make_unique<CalfWidgetItem>(w_113), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_114 = new CalfValue(this, *meta.get_param_props(_resolve("f2_level")), _resolve("f2_level"));
                                fWidgets.emplace_back(w_114);
                                fByIndex[_resolve("f2_level")].push_back(w_114);
                                c_111->add(std::make_unique<CalfWidgetItem>(w_114), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_102->add(std::move(c_111), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            c_101->add(std::move(c_102), CalfPacking{});
                        }
                        auto c_100 = std::make_unique<CalfFrameItem>("Filter 2", std::move(c_101));
                        c_84->add(std::move(c_100), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_69->add(std::move(c_84), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_69), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);
    }

protected:
    void onNanoDisplay() override
    {
        beginPath();
        rect(0, 0, getWidth(), getHeight());
        fillColor(Color(0.12f, 0.12f, 0.14f));
        fill();
        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it == fByIndex.end()) return;
        for (auto* w : it->second) w->setValue(value, /*notify=*/false);
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
    }

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(SidechainGateUI)
};

UI* createUI() { return new SidechainGateUI(); }

END_NAMESPACE_DISTRHO
