/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/gate.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfComboBox.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLed.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include "CalfVuMeter.hpp"
#include <calf/metadata.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfComboBox;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLed;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfVuMeter;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class GateUI : public UI, public CalfWidgetBase::Callback
{
public:
    GateUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = gate_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 8, false);
            {
                auto c_2 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 20, false);
                {
                    auto c_3 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 7, false);
                    auto* w_4 = new CalfLabel(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"), nullptr);
                    fWidgets.emplace_back(w_4);
                    fByIndex[_resolve("bypass")].push_back(w_4);
                    c_3->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    {
                        auto c_6 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_7 = new CalfToggle(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"));
                        w_7->setShowLabels(false);
                        fWidgets.emplace_back(w_7);
                        fByIndex[_resolve("bypass")].push_back(w_7);
                        c_6->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{});
                        auto c_5 = std::make_unique<CalfAlignItem>(std::move(c_6), 0.5f, 0.5f, 0.0f, 0.0f);
                        c_3->add(std::move(c_5), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_2->add(std::move(c_3), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                }
                {
                    auto c_8 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 7, false);
                    auto* w_9 = new CalfLabel(this, *meta.get_param_props(_resolve("range")), _resolve("range"), nullptr);
                    fWidgets.emplace_back(w_9);
                    fByIndex[_resolve("range")].push_back(w_9);
                    c_8->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                    auto* w_10 = new CalfKnob(this, *meta.get_param_props(_resolve("range")), _resolve("range"));
                    w_10->setShowLabels(false);
                    fWidgets.emplace_back(w_10);
                    fByIndex[_resolve("range")].push_back(w_10);
                    c_8->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_11 = new CalfValue(this, *meta.get_param_props(_resolve("range")), _resolve("range"));
                    fWidgets.emplace_back(w_11);
                    fByIndex[_resolve("range")].push_back(w_11);
                    c_8->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_2->add(std::move(c_8), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                }
                {
                    auto c_12 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    auto* w_13 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                    fWidgets.emplace_back(w_13);
                    c_12->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_2->add(std::move(c_12), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_2), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
            }
            {
                auto c_14 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                {
                    auto c_16 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_17 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                        {
                            auto c_18 = std::make_unique<CalfTableItem>(3, 3, false, 0, 0);
                            auto* w_19 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_in")), _resolve("meter_in"), nullptr);
                            fWidgets.emplace_back(w_19);
                            fByIndex[_resolve("meter_in")].push_back(w_19);
                            c_18->add(std::make_unique<CalfWidgetItem>(w_19), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true});
                            auto* w_20 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_in")), _resolve("meter_in"));
                            w_20->setShowLabels(false);
                            fWidgets.emplace_back(w_20);
                            fByIndex[_resolve("meter_in")].push_back(w_20);
                            c_18->add(std::make_unique<CalfWidgetItem>(w_20), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                            auto* w_21 = new CalfLed(this, *meta.get_param_props(_resolve("clip_in")), _resolve("clip_in"));
                            w_21->setShowLabels(false);
                            fWidgets.emplace_back(w_21);
                            fByIndex[_resolve("clip_in")].push_back(w_21);
                            c_18->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=2});
                            auto* w_22 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_out")), _resolve("meter_out"), nullptr);
                            fWidgets.emplace_back(w_22);
                            fByIndex[_resolve("meter_out")].push_back(w_22);
                            c_18->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachY=1});
                            auto* w_23 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_out")), _resolve("meter_out"));
                            w_23->setShowLabels(false);
                            fWidgets.emplace_back(w_23);
                            fByIndex[_resolve("meter_out")].push_back(w_23);
                            c_18->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                            auto* w_24 = new CalfLed(this, *meta.get_param_props(_resolve("clip_out")), _resolve("clip_out"));
                            w_24->setShowLabels(false);
                            fWidgets.emplace_back(w_24);
                            fByIndex[_resolve("clip_out")].push_back(w_24);
                            c_18->add(std::make_unique<CalfWidgetItem>(w_24), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=2, .attachY=1});
                            auto* w_25 = new CalfLabel(this, *meta.get_param_props(_resolve("gating")), _resolve("gating"), nullptr);
                            fWidgets.emplace_back(w_25);
                            fByIndex[_resolve("gating")].push_back(w_25);
                            c_18->add(std::make_unique<CalfWidgetItem>(w_25), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachY=2});
                            auto* w_26 = new CalfVuMeter(this, *meta.get_param_props(_resolve("gating")), _resolve("gating"));
                            w_26->setShowLabels(false);
                            fWidgets.emplace_back(w_26);
                            fByIndex[_resolve("gating")].push_back(w_26);
                            c_18->add(std::make_unique<CalfWidgetItem>(w_26), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2, .attachW=2});
                            c_17->add(std::move(c_18), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        }
                        {
                            auto c_27 = std::make_unique<CalfTableItem>(2, 3, true, 0, 0);
                            {
                                auto c_28 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_29 = new CalfLabel(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"), nullptr);
                                fWidgets.emplace_back(w_29);
                                fByIndex[_resolve("attack")].push_back(w_29);
                                c_28->add(std::make_unique<CalfWidgetItem>(w_29), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_30 = new CalfKnob(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"));
                                w_30->setShowLabels(false);
                                fWidgets.emplace_back(w_30);
                                fByIndex[_resolve("attack")].push_back(w_30);
                                c_28->add(std::make_unique<CalfWidgetItem>(w_30), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_31 = new CalfValue(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"));
                                fWidgets.emplace_back(w_31);
                                fByIndex[_resolve("attack")].push_back(w_31);
                                c_28->add(std::make_unique<CalfWidgetItem>(w_31), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_27->add(std::move(c_28), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_32 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_33 = new CalfLabel(this, *meta.get_param_props(_resolve("release")), _resolve("release"), nullptr);
                                fWidgets.emplace_back(w_33);
                                fByIndex[_resolve("release")].push_back(w_33);
                                c_32->add(std::make_unique<CalfWidgetItem>(w_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_34 = new CalfKnob(this, *meta.get_param_props(_resolve("release")), _resolve("release"));
                                w_34->setShowLabels(false);
                                fWidgets.emplace_back(w_34);
                                fByIndex[_resolve("release")].push_back(w_34);
                                c_32->add(std::make_unique<CalfWidgetItem>(w_34), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_35 = new CalfValue(this, *meta.get_param_props(_resolve("release")), _resolve("release"));
                                fWidgets.emplace_back(w_35);
                                fByIndex[_resolve("release")].push_back(w_35);
                                c_32->add(std::make_unique<CalfWidgetItem>(w_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_27->add(std::move(c_32), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachX=1});
                            }
                            {
                                auto c_36 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_37 = new CalfLabel(this, *meta.get_param_props(_resolve("knee")), _resolve("knee"), nullptr);
                                fWidgets.emplace_back(w_37);
                                fByIndex[_resolve("knee")].push_back(w_37);
                                c_36->add(std::make_unique<CalfWidgetItem>(w_37), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_38 = new CalfKnob(this, *meta.get_param_props(_resolve("knee")), _resolve("knee"));
                                w_38->setShowLabels(false);
                                fWidgets.emplace_back(w_38);
                                fByIndex[_resolve("knee")].push_back(w_38);
                                c_36->add(std::make_unique<CalfWidgetItem>(w_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_39 = new CalfValue(this, *meta.get_param_props(_resolve("knee")), _resolve("knee"));
                                fWidgets.emplace_back(w_39);
                                fByIndex[_resolve("knee")].push_back(w_39);
                                c_36->add(std::make_unique<CalfWidgetItem>(w_39), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_27->add(std::move(c_36), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachX=2});
                            }
                            {
                                auto c_40 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_41 = new CalfLabel(this, *meta.get_param_props(_resolve("ratio")), _resolve("ratio"), nullptr);
                                fWidgets.emplace_back(w_41);
                                fByIndex[_resolve("ratio")].push_back(w_41);
                                c_40->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_42 = new CalfKnob(this, *meta.get_param_props(_resolve("ratio")), _resolve("ratio"));
                                w_42->setShowLabels(false);
                                fWidgets.emplace_back(w_42);
                                fByIndex[_resolve("ratio")].push_back(w_42);
                                c_40->add(std::make_unique<CalfWidgetItem>(w_42), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_43 = new CalfValue(this, *meta.get_param_props(_resolve("ratio")), _resolve("ratio"));
                                fWidgets.emplace_back(w_43);
                                fByIndex[_resolve("ratio")].push_back(w_43);
                                c_40->add(std::make_unique<CalfWidgetItem>(w_43), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_27->add(std::move(c_40), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachY=1});
                            }
                            {
                                auto c_44 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_45 = new CalfLabel(this, *meta.get_param_props(_resolve("threshold")), _resolve("threshold"), nullptr);
                                fWidgets.emplace_back(w_45);
                                fByIndex[_resolve("threshold")].push_back(w_45);
                                c_44->add(std::make_unique<CalfWidgetItem>(w_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_46 = new CalfKnob(this, *meta.get_param_props(_resolve("threshold")), _resolve("threshold"));
                                w_46->setShowLabels(false);
                                fWidgets.emplace_back(w_46);
                                fByIndex[_resolve("threshold")].push_back(w_46);
                                c_44->add(std::make_unique<CalfWidgetItem>(w_46), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_47 = new CalfValue(this, *meta.get_param_props(_resolve("threshold")), _resolve("threshold"));
                                fWidgets.emplace_back(w_47);
                                fByIndex[_resolve("threshold")].push_back(w_47);
                                c_44->add(std::make_unique<CalfWidgetItem>(w_47), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_27->add(std::move(c_44), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                            }
                            {
                                auto c_48 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_49 = new CalfLabel(this, *meta.get_param_props(_resolve("makeup")), _resolve("makeup"), nullptr);
                                fWidgets.emplace_back(w_49);
                                fByIndex[_resolve("makeup")].push_back(w_49);
                                c_48->add(std::make_unique<CalfWidgetItem>(w_49), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_50 = new CalfKnob(this, *meta.get_param_props(_resolve("makeup")), _resolve("makeup"));
                                w_50->setShowLabels(false);
                                fWidgets.emplace_back(w_50);
                                fByIndex[_resolve("makeup")].push_back(w_50);
                                c_48->add(std::make_unique<CalfWidgetItem>(w_50), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_51 = new CalfValue(this, *meta.get_param_props(_resolve("makeup")), _resolve("makeup"));
                                fWidgets.emplace_back(w_51);
                                fByIndex[_resolve("makeup")].push_back(w_51);
                                c_48->add(std::make_unique<CalfWidgetItem>(w_51), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_27->add(std::move(c_48), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                            }
                            c_17->add(std::move(c_27), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_52 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, true);
                            {
                                auto c_53 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_54 = new CalfLabel(this, *meta.get_param_props(_resolve("stereo_link")), _resolve("stereo_link"), nullptr);
                                fWidgets.emplace_back(w_54);
                                fByIndex[_resolve("stereo_link")].push_back(w_54);
                                c_53->add(std::make_unique<CalfWidgetItem>(w_54), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false});
                                auto* w_55 = new CalfComboBox(this, *meta.get_param_props(_resolve("stereo_link")), _resolve("stereo_link"));
                                w_55->setShowLabels(false);
                                fWidgets.emplace_back(w_55);
                                fByIndex[_resolve("stereo_link")].push_back(w_55);
                                c_53->add(std::make_unique<CalfWidgetItem>(w_55), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_52->add(std::move(c_53), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_56 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_57 = new CalfLabel(this, *meta.get_param_props(_resolve("detection")), _resolve("detection"), nullptr);
                                fWidgets.emplace_back(w_57);
                                fByIndex[_resolve("detection")].push_back(w_57);
                                c_56->add(std::make_unique<CalfWidgetItem>(w_57), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false});
                                auto* w_58 = new CalfComboBox(this, *meta.get_param_props(_resolve("detection")), _resolve("detection"));
                                w_58->setShowLabels(false);
                                fWidgets.emplace_back(w_58);
                                fByIndex[_resolve("detection")].push_back(w_58);
                                c_56->add(std::make_unique<CalfWidgetItem>(w_58), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_52->add(std::move(c_56), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            c_17->add(std::move(c_52), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        c_16->add(std::move(c_17), CalfPacking{});
                    }
                    auto c_15 = std::make_unique<CalfFrameItem>("Gate", std::move(c_16));
                    c_14->add(std::move(c_15), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_14), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            {
                auto c_60 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_61 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    auto* w_62 = new CalfLineGraph(this, *meta.get_param_props(_resolve("gating")), _resolve("gating"), 320, 320);
                    w_62->setSize(static_cast<uint>(320), static_cast<uint>(320));
                    fWidgets.emplace_back(w_62);
                    fByIndex[_resolve("gating")].push_back(w_62);
                    c_61->add(std::make_unique<CalfWidgetItem>(w_62), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_60->add(std::move(c_61), CalfPacking{});
                }
                auto c_59 = std::make_unique<CalfFrameItem>("Gating", std::move(c_60));
                c_1->add(std::move(c_59), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);
    }

protected:
    void onNanoDisplay() override
    {
        beginPath();
        rect(0, 0, getWidth(), getHeight());
        fillColor(Color(0.12f, 0.12f, 0.14f));
        fill();
        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it == fByIndex.end()) return;
        for (auto* w : it->second) w->setValue(value, /*notify=*/false);
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
    }

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(GateUI)
};

UI* createUI() { return new GateUI(); }

END_NAMESPACE_DISTRHO
