/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/analyzer.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfComboBox.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include <calf/metadata.h>
#ifndef ENABLE_EXPERIMENTAL
#define ENABLE_EXPERIMENTAL 1
#endif
#include <calf/modules_tools.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfComboBox;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class AnalyzerUI : public UI, public CalfWidgetBase::Callback
{
public:
    AnalyzerUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = analyzer_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfTableItem>(3, 2, false, 0, 0);
            {
                auto c_2 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 12, false);
                auto* w_3 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Accuracy");
                fWidgets.emplace_back(w_3);
                c_2->add(std::make_unique<CalfWidgetItem>(w_3), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_4 = new CalfKnob(this, *meta.get_param_props(_resolve("analyzer_accuracy")), _resolve("analyzer_accuracy"));
                w_4->setShowLabels(false);
                fWidgets.emplace_back(w_4);
                fByIndex[_resolve("analyzer_accuracy")].push_back(w_4);
                c_2->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_5 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "   ");
                fWidgets.emplace_back(w_5);
                c_2->add(std::make_unique<CalfWidgetItem>(w_5), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_6 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Speed");
                fWidgets.emplace_back(w_6);
                c_2->add(std::make_unique<CalfWidgetItem>(w_6), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_7 = new CalfKnob(this, *meta.get_param_props(_resolve("analyzer_speed")), _resolve("analyzer_speed"));
                w_7->setShowLabels(false);
                fWidgets.emplace_back(w_7);
                fByIndex[_resolve("analyzer_speed")].push_back(w_7);
                c_2->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_8 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "   ");
                fWidgets.emplace_back(w_8);
                c_2->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_9 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Hold");
                fWidgets.emplace_back(w_9);
                c_2->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_10 = new CalfToggle(this, *meta.get_param_props(_resolve("analyzer_hold")), _resolve("analyzer_hold"));
                w_10->setShowLabels(false);
                fWidgets.emplace_back(w_10);
                fByIndex[_resolve("analyzer_hold")].push_back(w_10);
                c_2->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_11 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "   ");
                fWidgets.emplace_back(w_11);
                c_2->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_12 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Freeze");
                fWidgets.emplace_back(w_12);
                c_2->add(std::make_unique<CalfWidgetItem>(w_12), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_13 = new CalfToggle(this, *meta.get_param_props(_resolve("analyzer_freeze")), _resolve("analyzer_freeze"));
                w_13->setShowLabels(false);
                fWidgets.emplace_back(w_13);
                fByIndex[_resolve("analyzer_freeze")].push_back(w_13);
                c_2->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_14 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "   ");
                fWidgets.emplace_back(w_14);
                c_2->add(std::make_unique<CalfWidgetItem>(w_14), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_15 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Display");
                fWidgets.emplace_back(w_15);
                c_2->add(std::make_unique<CalfWidgetItem>(w_15), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_16 = new CalfToggle(this, *meta.get_param_props(_resolve("analyzer_display")), _resolve("analyzer_display"));
                w_16->setShowLabels(false);
                fWidgets.emplace_back(w_16);
                fByIndex[_resolve("analyzer_display")].push_back(w_16);
                c_2->add(std::make_unique<CalfWidgetItem>(w_16), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_17 = new CalfComboBox(this, *meta.get_param_props(_resolve("analyzer_mode")), _resolve("analyzer_mode"));
                w_17->setShowLabels(false);
                fWidgets.emplace_back(w_17);
                fByIndex[_resolve("analyzer_mode")].push_back(w_17);
                c_2->add(std::make_unique<CalfWidgetItem>(w_17), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                c_1->add(std::move(c_2), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false});
            }
            {
                auto c_19 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_20 = std::make_unique<CalfTableItem>(1, 2, false, 0, 0);
                    auto* w_21 = new CalfLineGraph(this, *meta.get_param_props(_resolve("analyzer_level")), _resolve("analyzer_level"), 560, 250);
                    fLineGraphs.push_back({ w_21, static_cast<int>(_resolve("analyzer_level")) });
                    w_21->setSize(static_cast<uint>(560), static_cast<uint>(250));
                    fWidgets.emplace_back(w_21);
                    fByIndex[_resolve("analyzer_level")].push_back(w_21);
                    c_20->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    {
                        auto c_22 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 3, false);
                        auto* w_23 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Zoom");
                        fWidgets.emplace_back(w_23);
                        c_22->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        auto* w_24 = new CalfKnob(this, *meta.get_param_props(_resolve("analyzer_level")), _resolve("analyzer_level"));
                        w_24->setShowLabels(false);
                        fWidgets.emplace_back(w_24);
                        fByIndex[_resolve("analyzer_level")].push_back(w_24);
                        c_22->add(std::make_unique<CalfWidgetItem>(w_24), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        auto* w_25 = new CalfValue(this, *meta.get_param_props(_resolve("analyzer_level")), _resolve("analyzer_level"));
                        fWidgets.emplace_back(w_25);
                        fByIndex[_resolve("analyzer_level")].push_back(w_25);
                        c_22->add(std::make_unique<CalfWidgetItem>(w_25), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                        c_20->add(std::move(c_22), CalfPacking{.expandX=false, .expandY=true, .fillX=false, .fillY=true, .attachX=1});
                    }
                    c_19->add(std::move(c_20), CalfPacking{});
                }
                auto c_18 = std::make_unique<CalfFrameItem>("Analyzer", std::move(c_19));
                c_1->add(std::move(c_18), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
            }
            {
                auto c_26 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_27 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, true);
                    auto* w_28 = new CalfComboBox(this, *meta.get_param_props(_resolve("analyzer_windowing")), _resolve("analyzer_windowing"));
                    w_28->setShowLabels(false);
                    fWidgets.emplace_back(w_28);
                    fByIndex[_resolve("analyzer_windowing")].push_back(w_28);
                    c_27->add(std::make_unique<CalfWidgetItem>(w_28), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_29 = new CalfComboBox(this, *meta.get_param_props(_resolve("analyzer_smoothing")), _resolve("analyzer_smoothing"));
                    w_29->setShowLabels(false);
                    fWidgets.emplace_back(w_29);
                    fByIndex[_resolve("analyzer_smoothing")].push_back(w_29);
                    c_27->add(std::make_unique<CalfWidgetItem>(w_29), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_30 = new CalfComboBox(this, *meta.get_param_props(_resolve("analyzer_post")), _resolve("analyzer_post"));
                    w_30->setShowLabels(false);
                    fWidgets.emplace_back(w_30);
                    fByIndex[_resolve("analyzer_post")].push_back(w_30);
                    c_27->add(std::make_unique<CalfWidgetItem>(w_30), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_31 = new CalfComboBox(this, *meta.get_param_props(_resolve("analyzer_scale")), _resolve("analyzer_scale"));
                    w_31->setShowLabels(false);
                    fWidgets.emplace_back(w_31);
                    fByIndex[_resolve("analyzer_scale")].push_back(w_31);
                    c_27->add(std::make_unique<CalfWidgetItem>(w_31), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_32 = new CalfComboBox(this, *meta.get_param_props(_resolve("analyzer_view")), _resolve("analyzer_view"));
                    w_32->setShowLabels(false);
                    fWidgets.emplace_back(w_32);
                    fByIndex[_resolve("analyzer_view")].push_back(w_32);
                    c_27->add(std::make_unique<CalfWidgetItem>(w_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_26->add(std::move(c_27), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_33 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, true);
                    auto* w_34 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Windowing");
                    fWidgets.emplace_back(w_34);
                    c_33->add(std::make_unique<CalfWidgetItem>(w_34), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_35 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Smoothing");
                    fWidgets.emplace_back(w_35);
                    c_33->add(std::make_unique<CalfWidgetItem>(w_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_36 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Post Processing");
                    fWidgets.emplace_back(w_36);
                    c_33->add(std::make_unique<CalfWidgetItem>(w_36), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_37 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Scale");
                    fWidgets.emplace_back(w_37);
                    c_33->add(std::make_unique<CalfWidgetItem>(w_37), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    auto* w_38 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "View Mode");
                    fWidgets.emplace_back(w_38);
                    c_33->add(std::make_unique<CalfWidgetItem>(w_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    c_26->add(std::move(c_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_26), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false, .attachY=2});
            }
            {
                auto c_39 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, false);
                auto* w_40 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Density");
                fWidgets.emplace_back(w_40);
                c_39->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_41 = new CalfKnob(this, *meta.get_param_props(_resolve("gonio_accuracy")), _resolve("gonio_accuracy"));
                w_41->setShowLabels(false);
                fWidgets.emplace_back(w_41);
                fByIndex[_resolve("gonio_accuracy")].push_back(w_41);
                c_39->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                auto* w_42 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "   ");
                fWidgets.emplace_back(w_42);
                c_39->add(std::make_unique<CalfWidgetItem>(w_42), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_43 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Soft");
                fWidgets.emplace_back(w_43);
                c_39->add(std::make_unique<CalfWidgetItem>(w_43), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                auto* w_44 = new CalfToggle(this, *meta.get_param_props(_resolve("gonio_use_fade")), _resolve("gonio_use_fade"));
                w_44->setShowLabels(false);
                fWidgets.emplace_back(w_44);
                fByIndex[_resolve("gonio_use_fade")].push_back(w_44);
                c_39->add(std::make_unique<CalfWidgetItem>(w_44), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                auto* w_45 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "   ");
                fWidgets.emplace_back(w_45);
                c_39->add(std::make_unique<CalfWidgetItem>(w_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_46 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Display");
                fWidgets.emplace_back(w_46);
                c_39->add(std::make_unique<CalfWidgetItem>(w_46), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                auto* w_47 = new CalfToggle(this, *meta.get_param_props(_resolve("gonio_display")), _resolve("gonio_display"));
                w_47->setShowLabels(false);
                fWidgets.emplace_back(w_47);
                fByIndex[_resolve("gonio_display")].push_back(w_47);
                c_39->add(std::make_unique<CalfWidgetItem>(w_47), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                c_1->add(std::move(c_39), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false, .attachX=1});
            }
            {
                auto c_49 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                auto* w_50 = new CalfLineGraph(this, *meta.get_param_props(_resolve("gonio_display")), _resolve("gonio_display"));
                fWidgets.emplace_back(w_50);
                fByIndex[_resolve("gonio_display")].push_back(w_50);
                c_49->add(std::make_unique<CalfWidgetItem>(w_50), CalfPacking{});
                auto c_48 = std::make_unique<CalfFrameItem>("Phase Correlation", std::move(c_49));
                c_1->add(std::move(c_48), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
            }
            {
                auto c_51 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                auto* w_52 = new CalfComboBox(this, *meta.get_param_props(_resolve("gonio_mode")), _resolve("gonio_mode"));
                w_52->setShowLabels(false);
                fWidgets.emplace_back(w_52);
                fByIndex[_resolve("gonio_mode")].push_back(w_52);
                c_51->add(std::make_unique<CalfWidgetItem>(w_52), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                auto* w_53 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Display Mode");
                fWidgets.emplace_back(w_53);
                c_51->add(std::make_unique<CalfWidgetItem>(w_53), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                c_1->add(std::move(c_51), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=false, .attachX=1, .attachY=2});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);

        // Shadow module: same DSP class as the running plugin, instantiated
        // UI-side just so <line-graph> widgets can query line_graph_iface
        // synchronously during paint.
        fShadow = std::make_unique<calf_plugins::analyzer_audio_module>();
        fShadowParams.assign(Meta::param_count, 0.0f);
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            fShadowParams[i] = meta.get_param_props(static_cast<int>(i))->def_value;
            fShadow->params[i] = &fShadowParams[i];
        }
        fShadow->post_instantiate(48000);
        fShadow->set_sample_rate(48000);
        fShadow->params_changed();
        fShadow->activate();
        // Not every Calf module inherits line_graph_iface — only the
        // ones that draw curves do. Cross-cast at runtime; null means
        // "this plugin has no curves to draw, paint the placeholder".
        const calf_plugins::line_graph_iface* _lg =
            dynamic_cast<const calf_plugins::line_graph_iface*>(fShadow.get());
        if (_lg) {
            for (auto& g : fLineGraphs)
                g.w->setGraphSource(_lg, g.idx);
        }
    }

protected:
    void onNanoDisplay() override
    {
        beginPath();
        rect(0, 0, getWidth(), getHeight());
        fillColor(Color(0.12f, 0.12f, 0.14f));
        fill();
        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it != fByIndex.end())
            for (auto* w : it->second) w->setValue(value, /*notify=*/false);
        if (fShadow && index < fShadowParams.size()) {
            fShadowParams[index] = value;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
        if (fShadow && w->getParamIndex() < fShadowParams.size()) {
            fShadowParams[w->getParamIndex()] = v;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    // No-op for WANT_STATE plugins (Monosynth, Organ, FluidSynth, Wavetable).
    // Codegen UIs don't yet visualise state keys (organ presets, wavetable
    // data, SF2 path, modmatrix rows); hand-written subclasses can override.
    // DPF only declares stateChanged when the plugin opts in, so guard.
#if DISTRHO_PLUGIN_WANT_STATE
    void stateChanged(const char* /*key*/, const char* /*value*/) override {}
#endif

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    std::unique_ptr<calf_plugins::analyzer_audio_module> fShadow;
    std::vector<float>                            fShadowParams;
    struct LineGraphRef { CalfLineGraph* w; int idx; };
    std::vector<LineGraphRef>                     fLineGraphs;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(AnalyzerUI)
};

UI* createUI() { return new AnalyzerUI(); }

END_NAMESPACE_DISTRHO
