/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/reversedelay.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLed.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include "CalfVuMeter.hpp"
#include <calf/metadata.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLed;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfVuMeter;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class ReverseDelayUI : public UI, public CalfWidgetBase::Callback
{
public:
    ReverseDelayUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = reverse_delay_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
            {
                auto c_2 = std::make_unique<CalfTableItem>(1, 7, false, 5, 5);
                auto* w_3 = new CalfLabel(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"), nullptr);
                fWidgets.emplace_back(w_3);
                fByIndex[_resolve("level_in")].push_back(w_3);
                c_2->add(std::make_unique<CalfWidgetItem>(w_3), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true});
                auto* w_4 = new CalfKnob(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                w_4->setShowLabels(false);
                fWidgets.emplace_back(w_4);
                fByIndex[_resolve("level_in")].push_back(w_4);
                c_2->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=1, .attachH=2});
                auto* w_5 = new CalfValue(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                fWidgets.emplace_back(w_5);
                fByIndex[_resolve("level_in")].push_back(w_5);
                c_2->add(std::make_unique<CalfWidgetItem>(w_5), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=3});
                auto* w_6 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Input level");
                fWidgets.emplace_back(w_6);
                c_2->add(std::make_unique<CalfWidgetItem>(w_6), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                auto* w_7 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inL")), _resolve("meter_inL"));
                w_7->setShowLabels(false);
                fWidgets.emplace_back(w_7);
                fByIndex[_resolve("meter_inL")].push_back(w_7);
                c_2->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                auto* w_8 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inR")), _resolve("meter_inR"));
                w_8->setShowLabels(false);
                fWidgets.emplace_back(w_8);
                fByIndex[_resolve("meter_inR")].push_back(w_8);
                c_2->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2});
                auto* w_9 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_9);
                fByIndex[_resolve("meter_outR")].push_back(w_9);
                c_2->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=3});
                auto* w_10 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_10);
                c_2->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                auto* w_11 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inL")), _resolve("clip_inL"));
                w_11->setShowLabels(false);
                fWidgets.emplace_back(w_11);
                fByIndex[_resolve("clip_inL")].push_back(w_11);
                c_2->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                auto* w_12 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inR")), _resolve("clip_inR"));
                w_12->setShowLabels(false);
                fWidgets.emplace_back(w_12);
                fByIndex[_resolve("clip_inR")].push_back(w_12);
                c_2->add(std::make_unique<CalfWidgetItem>(w_12), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=2});
                auto* w_13 = new CalfLabel(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"), nullptr);
                fWidgets.emplace_back(w_13);
                fByIndex[_resolve("bypass")].push_back(w_13);
                c_2->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=3});
                auto* w_14 = new CalfToggle(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"));
                w_14->setShowLabels(false);
                fWidgets.emplace_back(w_14);
                fByIndex[_resolve("bypass")].push_back(w_14);
                c_2->add(std::make_unique<CalfWidgetItem>(w_14), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=1, .attachH=2});
                auto* w_15 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Output level");
                fWidgets.emplace_back(w_15);
                c_2->add(std::make_unique<CalfWidgetItem>(w_15), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4});
                auto* w_16 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outL")), _resolve("meter_outL"));
                w_16->setShowLabels(false);
                fWidgets.emplace_back(w_16);
                fByIndex[_resolve("meter_outL")].push_back(w_16);
                c_2->add(std::make_unique<CalfWidgetItem>(w_16), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=1});
                auto* w_17 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                w_17->setShowLabels(false);
                fWidgets.emplace_back(w_17);
                fByIndex[_resolve("meter_outR")].push_back(w_17);
                c_2->add(std::make_unique<CalfWidgetItem>(w_17), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=2});
                auto* w_18 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_18);
                fByIndex[_resolve("meter_outR")].push_back(w_18);
                c_2->add(std::make_unique<CalfWidgetItem>(w_18), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=3});
                auto* w_19 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_19);
                c_2->add(std::make_unique<CalfWidgetItem>(w_19), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=5});
                auto* w_20 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outL")), _resolve("clip_outL"));
                w_20->setShowLabels(false);
                fWidgets.emplace_back(w_20);
                fByIndex[_resolve("clip_outL")].push_back(w_20);
                c_2->add(std::make_unique<CalfWidgetItem>(w_20), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=1});
                auto* w_21 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outR")), _resolve("clip_outR"));
                w_21->setShowLabels(false);
                fWidgets.emplace_back(w_21);
                fByIndex[_resolve("clip_outR")].push_back(w_21);
                c_2->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=2});
                auto* w_22 = new CalfLabel(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"), nullptr);
                fWidgets.emplace_back(w_22);
                fByIndex[_resolve("level_out")].push_back(w_22);
                c_2->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6});
                auto* w_23 = new CalfKnob(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                w_23->setShowLabels(false);
                fWidgets.emplace_back(w_23);
                fByIndex[_resolve("level_out")].push_back(w_23);
                c_2->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=1, .attachH=2});
                auto* w_24 = new CalfValue(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                fWidgets.emplace_back(w_24);
                fByIndex[_resolve("level_out")].push_back(w_24);
                c_2->add(std::make_unique<CalfWidgetItem>(w_24), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=3});
                c_1->add(std::move(c_2), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=true});
            }
            {
                auto c_25 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 8, false);
                {
                    auto c_27 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_28 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        {
                            auto c_29 = std::make_unique<CalfTableItem>(4, 2, false, 0, 0);
                            {
                                auto c_30 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 12, false);
                                {
                                    auto c_31 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                    auto* w_32 = new CalfLabel(this, *meta.get_param_props(_resolve("bpm")), _resolve("bpm"), nullptr);
                                    fWidgets.emplace_back(w_32);
                                    fByIndex[_resolve("bpm")].push_back(w_32);
                                    c_31->add(std::make_unique<CalfWidgetItem>(w_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    auto* w_33 = new CalfKnob(this, *meta.get_param_props(_resolve("bpm")), _resolve("bpm"));
                                    w_33->setShowLabels(false);
                                    fWidgets.emplace_back(w_33);
                                    fByIndex[_resolve("bpm")].push_back(w_33);
                                    c_31->add(std::make_unique<CalfWidgetItem>(w_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    auto* w_34 = new CalfValue(this, *meta.get_param_props(_resolve("bpm")), _resolve("bpm"));
                                    fWidgets.emplace_back(w_34);
                                    fByIndex[_resolve("bpm")].push_back(w_34);
                                    c_31->add(std::make_unique<CalfWidgetItem>(w_34), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    c_30->add(std::move(c_31), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                }
                                {
                                    auto c_35 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                    auto* w_36 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Tap");
                                    fWidgets.emplace_back(w_36);
                                    c_35->add(std::make_unique<CalfWidgetItem>(w_36), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    auto* w_37 = new CalfLineGraph(this, *meta.get_param_props(_resolve("bpm")), _resolve("bpm"));
                                    fWidgets.emplace_back(w_37);
                                    fByIndex[_resolve("bpm")].push_back(w_37);
                                    c_35->add(std::make_unique<CalfWidgetItem>(w_37), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    auto* w_38 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                                    fWidgets.emplace_back(w_38);
                                    c_35->add(std::make_unique<CalfWidgetItem>(w_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    auto* w_39 = new CalfToggle(this, *meta.get_param_props(_resolve("sync")), _resolve("sync"));
                                    w_39->setShowLabels(false);
                                    fWidgets.emplace_back(w_39);
                                    fByIndex[_resolve("sync")].push_back(w_39);
                                    c_35->add(std::make_unique<CalfWidgetItem>(w_39), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    auto* w_40 = new CalfLabel(this, *meta.get_param_props(_resolve("sync")), _resolve("sync"), nullptr);
                                    fWidgets.emplace_back(w_40);
                                    fByIndex[_resolve("sync")].push_back(w_40);
                                    c_35->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    c_30->add(std::move(c_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                }
                                c_29->add(std::move(c_30), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .padX=10, .padY=15, .attachH=3});
                            }
                            auto* w_41 = new CalfLabel(this, *meta.get_param_props(_resolve("subdiv")), _resolve("subdiv"), nullptr);
                            fWidgets.emplace_back(w_41);
                            fByIndex[_resolve("subdiv")].push_back(w_41);
                            c_29->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                            auto* w_42 = new CalfKnob(this, *meta.get_param_props(_resolve("subdiv")), _resolve("subdiv"));
                            w_42->setShowLabels(false);
                            fWidgets.emplace_back(w_42);
                            fByIndex[_resolve("subdiv")].push_back(w_42);
                            c_29->add(std::make_unique<CalfWidgetItem>(w_42), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                            auto* w_43 = new CalfLabel(this, *meta.get_param_props(_resolve("time_l")), _resolve("time_l"), nullptr);
                            fWidgets.emplace_back(w_43);
                            fByIndex[_resolve("time_l")].push_back(w_43);
                            c_29->add(std::make_unique<CalfWidgetItem>(w_43), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                            auto* w_44 = new CalfKnob(this, *meta.get_param_props(_resolve("time_l")), _resolve("time_l"));
                            w_44->setShowLabels(false);
                            fWidgets.emplace_back(w_44);
                            fByIndex[_resolve("time_l")].push_back(w_44);
                            c_29->add(std::make_unique<CalfWidgetItem>(w_44), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                            auto* w_45 = new CalfLabel(this, *meta.get_param_props(_resolve("time_r")), _resolve("time_r"), nullptr);
                            fWidgets.emplace_back(w_45);
                            fByIndex[_resolve("time_r")].push_back(w_45);
                            c_29->add(std::make_unique<CalfWidgetItem>(w_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2});
                            auto* w_46 = new CalfKnob(this, *meta.get_param_props(_resolve("time_r")), _resolve("time_r"));
                            w_46->setShowLabels(false);
                            fWidgets.emplace_back(w_46);
                            fByIndex[_resolve("time_r")].push_back(w_46);
                            c_29->add(std::make_unique<CalfWidgetItem>(w_46), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=2});
                            c_28->add(std::move(c_29), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        c_27->add(std::move(c_28), CalfPacking{});
                    }
                    auto c_26 = std::make_unique<CalfFrameItem>("Delay time", std::move(c_27));
                    c_25->add(std::move(c_26), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_48 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_49 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        {
                            auto c_50 = std::make_unique<CalfTableItem>(2, 1, false, 0, 0);
                            {
                                auto c_51 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, false);
                                {
                                    auto c_52 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                    auto* w_53 = new CalfLabel(this, *meta.get_param_props(_resolve("sync_led_l")), _resolve("sync_led_l"), nullptr);
                                    fWidgets.emplace_back(w_53);
                                    fByIndex[_resolve("sync_led_l")].push_back(w_53);
                                    c_52->add(std::make_unique<CalfWidgetItem>(w_53), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    auto* w_54 = new CalfLed(this, *meta.get_param_props(_resolve("sync_led_l")), _resolve("sync_led_l"));
                                    w_54->setShowLabels(false);
                                    fWidgets.emplace_back(w_54);
                                    fByIndex[_resolve("sync_led_l")].push_back(w_54);
                                    c_52->add(std::make_unique<CalfWidgetItem>(w_54), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    c_51->add(std::move(c_52), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                }
                                {
                                    auto c_55 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                    auto* w_56 = new CalfLabel(this, *meta.get_param_props(_resolve("sync_led_r")), _resolve("sync_led_r"), nullptr);
                                    fWidgets.emplace_back(w_56);
                                    fByIndex[_resolve("sync_led_r")].push_back(w_56);
                                    c_55->add(std::make_unique<CalfWidgetItem>(w_56), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    auto* w_57 = new CalfLed(this, *meta.get_param_props(_resolve("sync_led_r")), _resolve("sync_led_r"));
                                    w_57->setShowLabels(false);
                                    fWidgets.emplace_back(w_57);
                                    fByIndex[_resolve("sync_led_r")].push_back(w_57);
                                    c_55->add(std::make_unique<CalfWidgetItem>(w_57), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                    c_51->add(std::move(c_55), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                                }
                                c_50->add(std::move(c_51), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            }
                            {
                                auto c_58 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_59 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Line Reset");
                                fWidgets.emplace_back(w_59);
                                c_58->add(std::make_unique<CalfWidgetItem>(w_59), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                {
                                    auto c_61 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                    auto* w_62 = new CalfToggle(this, *meta.get_param_props(_resolve("reset")), _resolve("reset"));
                                    w_62->setShowLabels(false);
                                    fWidgets.emplace_back(w_62);
                                    fByIndex[_resolve("reset")].push_back(w_62);
                                    c_61->add(std::make_unique<CalfWidgetItem>(w_62), CalfPacking{});
                                    auto c_60 = std::make_unique<CalfAlignItem>(std::move(c_61), 0.5f, 0.5f, 0.0f, 0.0f);
                                    c_58->add(std::move(c_60), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachY=1});
                                }
                                c_50->add(std::move(c_58), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                            }
                            c_49->add(std::move(c_50), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        c_48->add(std::move(c_49), CalfPacking{});
                    }
                    auto c_47 = std::make_unique<CalfFrameItem>("Synchronize", std::move(c_48));
                    c_25->add(std::move(c_47), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                {
                    auto c_64 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_65 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 0, false);
                        {
                            auto c_66 = std::make_unique<CalfTableItem>(2, 2, false, 0, 0);
                            {
                                auto c_67 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_68 = new CalfLabel(this, *meta.get_param_props(_resolve("feedback")), _resolve("feedback"), nullptr);
                                fWidgets.emplace_back(w_68);
                                fByIndex[_resolve("feedback")].push_back(w_68);
                                c_67->add(std::make_unique<CalfWidgetItem>(w_68), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                                auto* w_69 = new CalfKnob(this, *meta.get_param_props(_resolve("feedback")), _resolve("feedback"));
                                w_69->setShowLabels(false);
                                fWidgets.emplace_back(w_69);
                                fByIndex[_resolve("feedback")].push_back(w_69);
                                c_67->add(std::make_unique<CalfWidgetItem>(w_69), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                                auto* w_70 = new CalfValue(this, *meta.get_param_props(_resolve("feedback")), _resolve("feedback"));
                                fWidgets.emplace_back(w_70);
                                fByIndex[_resolve("feedback")].push_back(w_70);
                                c_67->add(std::make_unique<CalfWidgetItem>(w_70), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                                c_66->add(std::move(c_67), CalfPacking{.expandX=true, .expandY=true, .fillX=false, .fillY=false, .padX=10});
                            }
                            {
                                auto c_71 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_72 = new CalfLabel(this, *meta.get_param_props(_resolve("amount")), _resolve("amount"), nullptr);
                                fWidgets.emplace_back(w_72);
                                fByIndex[_resolve("amount")].push_back(w_72);
                                c_71->add(std::make_unique<CalfWidgetItem>(w_72), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_73 = new CalfKnob(this, *meta.get_param_props(_resolve("amount")), _resolve("amount"));
                                w_73->setShowLabels(false);
                                fWidgets.emplace_back(w_73);
                                fByIndex[_resolve("amount")].push_back(w_73);
                                c_71->add(std::make_unique<CalfWidgetItem>(w_73), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_74 = new CalfValue(this, *meta.get_param_props(_resolve("amount")), _resolve("amount"));
                                fWidgets.emplace_back(w_74);
                                fByIndex[_resolve("amount")].push_back(w_74);
                                c_71->add(std::make_unique<CalfWidgetItem>(w_74), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_66->add(std::move(c_71), CalfPacking{.expandX=true, .expandY=true, .fillX=false, .fillY=false, .padX=10, .attachX=1});
                            }
                            {
                                auto c_75 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_76 = new CalfLabel(this, *meta.get_param_props(_resolve("window")), _resolve("window"), nullptr);
                                fWidgets.emplace_back(w_76);
                                fByIndex[_resolve("window")].push_back(w_76);
                                c_75->add(std::make_unique<CalfWidgetItem>(w_76), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                                auto* w_77 = new CalfKnob(this, *meta.get_param_props(_resolve("window")), _resolve("window"));
                                w_77->setShowLabels(false);
                                fWidgets.emplace_back(w_77);
                                fByIndex[_resolve("window")].push_back(w_77);
                                c_75->add(std::make_unique<CalfWidgetItem>(w_77), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                                auto* w_78 = new CalfValue(this, *meta.get_param_props(_resolve("window")), _resolve("window"));
                                fWidgets.emplace_back(w_78);
                                fByIndex[_resolve("window")].push_back(w_78);
                                c_75->add(std::make_unique<CalfWidgetItem>(w_78), CalfPacking{.expandX=false, .expandY=false, .fillX=false, .fillY=false});
                                c_66->add(std::move(c_75), CalfPacking{.expandX=true, .expandY=true, .fillX=false, .fillY=true, .padX=10, .attachY=1});
                            }
                            {
                                auto c_79 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                auto* w_80 = new CalfLabel(this, *meta.get_param_props(_resolve("width")), _resolve("width"), nullptr);
                                fWidgets.emplace_back(w_80);
                                fByIndex[_resolve("width")].push_back(w_80);
                                c_79->add(std::make_unique<CalfWidgetItem>(w_80), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_81 = new CalfKnob(this, *meta.get_param_props(_resolve("width")), _resolve("width"));
                                w_81->setShowLabels(false);
                                fWidgets.emplace_back(w_81);
                                fByIndex[_resolve("width")].push_back(w_81);
                                c_79->add(std::make_unique<CalfWidgetItem>(w_81), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                auto* w_82 = new CalfValue(this, *meta.get_param_props(_resolve("width")), _resolve("width"));
                                fWidgets.emplace_back(w_82);
                                fByIndex[_resolve("width")].push_back(w_82);
                                c_79->add(std::make_unique<CalfWidgetItem>(w_82), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                c_66->add(std::move(c_79), CalfPacking{.expandX=true, .expandY=true, .fillX=false, .fillY=false, .attachX=1, .attachY=1});
                            }
                            c_65->add(std::move(c_66), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true});
                        }
                        c_64->add(std::move(c_65), CalfPacking{});
                    }
                    auto c_63 = std::make_unique<CalfFrameItem>("Mixing", std::move(c_64));
                    c_25->add(std::move(c_63), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_25), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);
    }

protected:
    void onNanoDisplay() override
    {
        beginPath();
        rect(0, 0, getWidth(), getHeight());
        fillColor(Color(0.12f, 0.12f, 0.14f));
        fill();
        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it == fByIndex.end()) return;
        for (auto* w : it->second) w->setValue(value, /*notify=*/false);
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
    }

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(ReverseDelayUI)
};

UI* createUI() { return new ReverseDelayUI(); }

END_NAMESPACE_DISTRHO
