/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/fluidsynth.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfComboBox.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include <calf/metadata.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfComboBox;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class FluidSynthUI : public UI, public CalfWidgetBase::Callback
{
public:
    FluidSynthUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = fluidsynth_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfTableItem>(2, 3, false, 0, 0);
            {
                auto c_2 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                auto* w_3 = new CalfLabel(this, *meta.get_param_props(_resolve("master")), _resolve("master"), nullptr);
                fWidgets.emplace_back(w_3);
                fByIndex[_resolve("master")].push_back(w_3);
                c_2->add(std::make_unique<CalfWidgetItem>(w_3), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_4 = new CalfKnob(this, *meta.get_param_props(_resolve("master")), _resolve("master"));
                w_4->setShowLabels(false);
                fWidgets.emplace_back(w_4);
                fByIndex[_resolve("master")].push_back(w_4);
                c_2->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_5 = new CalfValue(this, *meta.get_param_props(_resolve("master")), _resolve("master"));
                fWidgets.emplace_back(w_5);
                fByIndex[_resolve("master")].push_back(w_5);
                c_2->add(std::make_unique<CalfWidgetItem>(w_5), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                c_1->add(std::move(c_2), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=false, .padX=10});
            }
            {
                auto c_6 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 5, false);
                auto* w_7 = new CalfLabel(this, *meta.get_param_props(_resolve("reverb")), _resolve("reverb"), nullptr);
                fWidgets.emplace_back(w_7);
                fByIndex[_resolve("reverb")].push_back(w_7);
                c_6->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_8 = new CalfToggle(this, *meta.get_param_props(_resolve("reverb")), _resolve("reverb"));
                w_8->setShowLabels(false);
                fWidgets.emplace_back(w_8);
                fByIndex[_resolve("reverb")].push_back(w_8);
                c_6->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_9 = new CalfLabel(this, *meta.get_param_props(0u), 0u, nullptr);
                fWidgets.emplace_back(w_9);
                c_6->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_10 = new CalfToggle(this, *meta.get_param_props(_resolve("chorus")), _resolve("chorus"));
                w_10->setShowLabels(false);
                fWidgets.emplace_back(w_10);
                fByIndex[_resolve("chorus")].push_back(w_10);
                c_6->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                auto* w_11 = new CalfLabel(this, *meta.get_param_props(_resolve("chorus")), _resolve("chorus"), nullptr);
                fWidgets.emplace_back(w_11);
                fByIndex[_resolve("chorus")].push_back(w_11);
                c_6->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                c_1->add(std::move(c_6), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .padX=10, .attachX=1});
            }
            {
                auto c_13 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_14 = std::make_unique<CalfTableItem>(3, 2, false, 0, 0);
                    {
                        auto c_16 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_17 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Soundfont");
                        fWidgets.emplace_back(w_17);
                        c_16->add(std::make_unique<CalfWidgetItem>(w_17), CalfPacking{});
                        auto c_15 = std::make_unique<CalfAlignItem>(std::move(c_16), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_14->add(std::move(c_15), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    auto* w_18 = new CalfLineGraph(this, *meta.get_param_props(0u), 0u);
                    fWidgets.emplace_back(w_18);
                    c_14->add(std::make_unique<CalfWidgetItem>(w_18), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .padX=5, .padY=6, .attachX=1});
                    {
                        auto c_20 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_21 = new CalfLabel(this, *meta.get_param_props(_resolve("interpolation")), _resolve("interpolation"), nullptr);
                        fWidgets.emplace_back(w_21);
                        fByIndex[_resolve("interpolation")].push_back(w_21);
                        c_20->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{});
                        auto c_19 = std::make_unique<CalfAlignItem>(std::move(c_20), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_14->add(std::move(c_19), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                    }
                    auto* w_22 = new CalfComboBox(this, *meta.get_param_props(_resolve("interpolation")), _resolve("interpolation"));
                    w_22->setShowLabels(false);
                    fWidgets.emplace_back(w_22);
                    fByIndex[_resolve("interpolation")].push_back(w_22);
                    c_14->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .padX=5, .padY=6, .attachX=1, .attachY=1});
                    c_13->add(std::move(c_14), CalfPacking{});
                }
                auto c_12 = std::make_unique<CalfFrameItem>("Source", std::move(c_13));
                c_1->add(std::move(c_12), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
            }
            {
                auto c_24 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_25 = std::make_unique<CalfTableItem>(9, 4, false, 0, 0);
                    {
                        auto c_27 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_28 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Ch#");
                        fWidgets.emplace_back(w_28);
                        c_27->add(std::make_unique<CalfWidgetItem>(w_28), CalfPacking{});
                        auto c_26 = std::make_unique<CalfAlignItem>(std::move(c_27), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_26), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_30 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_31 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Current preset");
                        fWidgets.emplace_back(w_31);
                        c_30->add(std::make_unique<CalfWidgetItem>(w_31), CalfPacking{});
                        auto c_29 = std::make_unique<CalfAlignItem>(std::move(c_30), 0.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_29), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                    }
                    {
                        auto c_33 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_34 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Ch#");
                        fWidgets.emplace_back(w_34);
                        c_33->add(std::make_unique<CalfWidgetItem>(w_34), CalfPacking{});
                        auto c_32 = std::make_unique<CalfAlignItem>(std::move(c_33), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                    }
                    {
                        auto c_36 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_37 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Current preset");
                        fWidgets.emplace_back(w_37);
                        c_36->add(std::make_unique<CalfWidgetItem>(w_37), CalfPacking{});
                        auto c_35 = std::make_unique<CalfAlignItem>(std::move(c_36), 0.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3});
                    }
                    {
                        auto c_39 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_40 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "1");
                        fWidgets.emplace_back(w_40);
                        c_39->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{});
                        auto c_38 = std::make_unique<CalfAlignItem>(std::move(c_39), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                    }
                    auto* w_41 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_41->setShowLabels(false);
                    fWidgets.emplace_back(w_41);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                    {
                        auto c_43 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_44 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "2");
                        fWidgets.emplace_back(w_44);
                        c_43->add(std::make_unique<CalfWidgetItem>(w_44), CalfPacking{});
                        auto c_42 = std::make_unique<CalfAlignItem>(std::move(c_43), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_42), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=2});
                    }
                    auto* w_45 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_45->setShowLabels(false);
                    fWidgets.emplace_back(w_45);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2});
                    {
                        auto c_47 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_48 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "3");
                        fWidgets.emplace_back(w_48);
                        c_47->add(std::make_unique<CalfWidgetItem>(w_48), CalfPacking{});
                        auto c_46 = std::make_unique<CalfAlignItem>(std::move(c_47), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_46), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=3});
                    }
                    auto* w_49 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_49->setShowLabels(false);
                    fWidgets.emplace_back(w_49);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_49), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=3});
                    {
                        auto c_51 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_52 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "4");
                        fWidgets.emplace_back(w_52);
                        c_51->add(std::make_unique<CalfWidgetItem>(w_52), CalfPacking{});
                        auto c_50 = std::make_unique<CalfAlignItem>(std::move(c_51), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_50), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=4});
                    }
                    auto* w_53 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_53->setShowLabels(false);
                    fWidgets.emplace_back(w_53);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_53), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=4});
                    {
                        auto c_55 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_56 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "5");
                        fWidgets.emplace_back(w_56);
                        c_55->add(std::make_unique<CalfWidgetItem>(w_56), CalfPacking{});
                        auto c_54 = std::make_unique<CalfAlignItem>(std::move(c_55), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_54), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=5});
                    }
                    auto* w_57 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_57->setShowLabels(false);
                    fWidgets.emplace_back(w_57);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_57), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=5});
                    {
                        auto c_59 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_60 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "6");
                        fWidgets.emplace_back(w_60);
                        c_59->add(std::make_unique<CalfWidgetItem>(w_60), CalfPacking{});
                        auto c_58 = std::make_unique<CalfAlignItem>(std::move(c_59), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_58), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=6});
                    }
                    auto* w_61 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_61->setShowLabels(false);
                    fWidgets.emplace_back(w_61);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_61), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=6});
                    {
                        auto c_63 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_64 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "7");
                        fWidgets.emplace_back(w_64);
                        c_63->add(std::make_unique<CalfWidgetItem>(w_64), CalfPacking{});
                        auto c_62 = std::make_unique<CalfAlignItem>(std::move(c_63), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_62), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=7});
                    }
                    auto* w_65 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_65->setShowLabels(false);
                    fWidgets.emplace_back(w_65);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_65), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=7});
                    {
                        auto c_67 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_68 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "8");
                        fWidgets.emplace_back(w_68);
                        c_67->add(std::make_unique<CalfWidgetItem>(w_68), CalfPacking{});
                        auto c_66 = std::make_unique<CalfAlignItem>(std::move(c_67), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_66), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=8});
                    }
                    auto* w_69 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_69->setShowLabels(false);
                    fWidgets.emplace_back(w_69);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_69), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=8});
                    {
                        auto c_71 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_72 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "9");
                        fWidgets.emplace_back(w_72);
                        c_71->add(std::make_unique<CalfWidgetItem>(w_72), CalfPacking{});
                        auto c_70 = std::make_unique<CalfAlignItem>(std::move(c_71), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_70), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                    }
                    auto* w_73 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_73->setShowLabels(false);
                    fWidgets.emplace_back(w_73);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_73), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=1});
                    {
                        auto c_75 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_76 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "10");
                        fWidgets.emplace_back(w_76);
                        c_75->add(std::make_unique<CalfWidgetItem>(w_76), CalfPacking{});
                        auto c_74 = std::make_unique<CalfAlignItem>(std::move(c_75), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_74), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=2});
                    }
                    auto* w_77 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_77->setShowLabels(false);
                    fWidgets.emplace_back(w_77);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_77), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=2});
                    {
                        auto c_79 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_80 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "11");
                        fWidgets.emplace_back(w_80);
                        c_79->add(std::make_unique<CalfWidgetItem>(w_80), CalfPacking{});
                        auto c_78 = std::make_unique<CalfAlignItem>(std::move(c_79), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_78), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=3});
                    }
                    auto* w_81 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_81->setShowLabels(false);
                    fWidgets.emplace_back(w_81);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_81), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=3});
                    {
                        auto c_83 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_84 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "12");
                        fWidgets.emplace_back(w_84);
                        c_83->add(std::make_unique<CalfWidgetItem>(w_84), CalfPacking{});
                        auto c_82 = std::make_unique<CalfAlignItem>(std::move(c_83), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_82), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=4});
                    }
                    auto* w_85 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_85->setShowLabels(false);
                    fWidgets.emplace_back(w_85);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_85), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=4});
                    {
                        auto c_87 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_88 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "13");
                        fWidgets.emplace_back(w_88);
                        c_87->add(std::make_unique<CalfWidgetItem>(w_88), CalfPacking{});
                        auto c_86 = std::make_unique<CalfAlignItem>(std::move(c_87), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_86), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=5});
                    }
                    auto* w_89 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_89->setShowLabels(false);
                    fWidgets.emplace_back(w_89);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_89), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=5});
                    {
                        auto c_91 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_92 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "14");
                        fWidgets.emplace_back(w_92);
                        c_91->add(std::make_unique<CalfWidgetItem>(w_92), CalfPacking{});
                        auto c_90 = std::make_unique<CalfAlignItem>(std::move(c_91), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_90), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=6});
                    }
                    auto* w_93 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_93->setShowLabels(false);
                    fWidgets.emplace_back(w_93);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_93), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=6});
                    {
                        auto c_95 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_96 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "15");
                        fWidgets.emplace_back(w_96);
                        c_95->add(std::make_unique<CalfWidgetItem>(w_96), CalfPacking{});
                        auto c_94 = std::make_unique<CalfAlignItem>(std::move(c_95), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_94), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=7});
                    }
                    auto* w_97 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_97->setShowLabels(false);
                    fWidgets.emplace_back(w_97);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_97), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=7});
                    {
                        auto c_99 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_100 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "16");
                        fWidgets.emplace_back(w_100);
                        c_99->add(std::make_unique<CalfWidgetItem>(w_100), CalfPacking{});
                        auto c_98 = std::make_unique<CalfAlignItem>(std::move(c_99), 1.0f, 0.5f, 0.0f, 0.0f);
                        c_25->add(std::move(c_98), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=8});
                    }
                    auto* w_101 = new CalfComboBox(this, *meta.get_param_props(0u), 0u);
                    w_101->setShowLabels(false);
                    fWidgets.emplace_back(w_101);
                    c_25->add(std::make_unique<CalfWidgetItem>(w_101), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=8});
                    c_24->add(std::move(c_25), CalfPacking{});
                }
                auto c_23 = std::make_unique<CalfFrameItem>("Channels", std::move(c_24));
                c_1->add(std::move(c_23), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1, .attachW=3});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);
    }

protected:
    void onNanoDisplay() override
    {
        beginPath();
        rect(0, 0, getWidth(), getHeight());
        fillColor(Color(0.12f, 0.12f, 0.14f));
        fill();
        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it == fByIndex.end()) return;
        for (auto* w : it->second) w->setValue(value, /*notify=*/false);
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
    }

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(FluidSynthUI)
};

UI* createUI() { return new FluidSynthUI(); }

END_NAMESPACE_DISTRHO
