/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/limiter.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfTheme.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLed.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include "CalfVuMeter.hpp"
#include <calf/metadata.h>
#ifndef ENABLE_EXPERIMENTAL
#define ENABLE_EXPERIMENTAL 1
#endif
#include <calf/modules_limit.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLed;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfVuMeter;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class LimiterUI : public UI, public CalfWidgetBase::Callback
{
public:
    LimiterUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = limiter_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfTableItem>(3, 1, false, 0, 0);
            {
                auto c_2 = std::make_unique<CalfTableItem>(1, 7, false, 5, 5);
                auto* w_3 = new CalfLabel(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"), nullptr);
                fWidgets.emplace_back(w_3);
                fByIndex[_resolve("level_in")].push_back(w_3);
                c_2->add(std::make_unique<CalfWidgetItem>(w_3), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true});
                auto* w_4 = new CalfKnob(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                w_4->setShowLabels(false);
                fWidgets.emplace_back(w_4);
                fByIndex[_resolve("level_in")].push_back(w_4);
                c_2->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=1, .attachH=2});
                auto* w_5 = new CalfValue(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                fWidgets.emplace_back(w_5);
                fByIndex[_resolve("level_in")].push_back(w_5);
                c_2->add(std::make_unique<CalfWidgetItem>(w_5), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=3});
                auto* w_6 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Input level");
                fWidgets.emplace_back(w_6);
                c_2->add(std::make_unique<CalfWidgetItem>(w_6), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                auto* w_7 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inL")), _resolve("meter_inL"));
                w_7->setShowLabels(false);
                fWidgets.emplace_back(w_7);
                fByIndex[_resolve("meter_inL")].push_back(w_7);
                c_2->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                auto* w_8 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inR")), _resolve("meter_inR"));
                w_8->setShowLabels(false);
                fWidgets.emplace_back(w_8);
                fByIndex[_resolve("meter_inR")].push_back(w_8);
                c_2->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2});
                auto* w_9 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_9);
                fByIndex[_resolve("meter_outR")].push_back(w_9);
                c_2->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=3});
                auto* w_10 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_10);
                c_2->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                auto* w_11 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inL")), _resolve("clip_inL"));
                w_11->setShowLabels(false);
                fWidgets.emplace_back(w_11);
                fByIndex[_resolve("clip_inL")].push_back(w_11);
                c_2->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                auto* w_12 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inR")), _resolve("clip_inR"));
                w_12->setShowLabels(false);
                fWidgets.emplace_back(w_12);
                fByIndex[_resolve("clip_inR")].push_back(w_12);
                c_2->add(std::make_unique<CalfWidgetItem>(w_12), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=2});
                auto* w_13 = new CalfLabel(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"), nullptr);
                fWidgets.emplace_back(w_13);
                fByIndex[_resolve("bypass")].push_back(w_13);
                c_2->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=3});
                auto* w_14 = new CalfToggle(this, *meta.get_param_props(_resolve("bypass")), _resolve("bypass"));
                w_14->setIcon("bypass");
                w_14->setShowLabels(false);
                fWidgets.emplace_back(w_14);
                fByIndex[_resolve("bypass")].push_back(w_14);
                c_2->add(std::make_unique<CalfWidgetItem>(w_14), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=1, .attachH=2});
                auto* w_15 = new CalfLabel(this, *meta.get_param_props(_resolve("auto_level")), _resolve("auto_level"), nullptr);
                fWidgets.emplace_back(w_15);
                fByIndex[_resolve("auto_level")].push_back(w_15);
                c_2->add(std::make_unique<CalfWidgetItem>(w_15), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=4});
                auto* w_16 = new CalfToggle(this, *meta.get_param_props(_resolve("auto_level")), _resolve("auto_level"));
                w_16->setShowLabels(false);
                fWidgets.emplace_back(w_16);
                fByIndex[_resolve("auto_level")].push_back(w_16);
                c_2->add(std::make_unique<CalfWidgetItem>(w_16), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=1, .attachH=2});
                auto* w_17 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Output level");
                fWidgets.emplace_back(w_17);
                c_2->add(std::make_unique<CalfWidgetItem>(w_17), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5});
                auto* w_18 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outL")), _resolve("meter_outL"));
                w_18->setShowLabels(false);
                fWidgets.emplace_back(w_18);
                fByIndex[_resolve("meter_outL")].push_back(w_18);
                c_2->add(std::make_unique<CalfWidgetItem>(w_18), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=1});
                auto* w_19 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                w_19->setShowLabels(false);
                fWidgets.emplace_back(w_19);
                fByIndex[_resolve("meter_outR")].push_back(w_19);
                c_2->add(std::make_unique<CalfWidgetItem>(w_19), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=2});
                auto* w_20 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_20);
                fByIndex[_resolve("meter_outR")].push_back(w_20);
                c_2->add(std::make_unique<CalfWidgetItem>(w_20), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=3});
                auto* w_21 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_21);
                c_2->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6});
                auto* w_22 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outL")), _resolve("clip_outL"));
                w_22->setShowLabels(false);
                fWidgets.emplace_back(w_22);
                fByIndex[_resolve("clip_outL")].push_back(w_22);
                c_2->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=1});
                auto* w_23 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outR")), _resolve("clip_outR"));
                w_23->setShowLabels(false);
                fWidgets.emplace_back(w_23);
                fByIndex[_resolve("clip_outR")].push_back(w_23);
                c_2->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=2});
                auto* w_24 = new CalfLabel(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"), nullptr);
                fWidgets.emplace_back(w_24);
                fByIndex[_resolve("level_out")].push_back(w_24);
                c_2->add(std::make_unique<CalfWidgetItem>(w_24), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=7});
                auto* w_25 = new CalfKnob(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                w_25->setShowLabels(false);
                fWidgets.emplace_back(w_25);
                fByIndex[_resolve("level_out")].push_back(w_25);
                c_2->add(std::make_unique<CalfWidgetItem>(w_25), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=7, .attachY=1, .attachH=2});
                auto* w_26 = new CalfValue(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                fWidgets.emplace_back(w_26);
                fByIndex[_resolve("level_out")].push_back(w_26);
                c_2->add(std::make_unique<CalfWidgetItem>(w_26), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=7, .attachY=3});
                c_1->add(std::move(c_2), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=true});
            }
            {
                auto c_28 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                {
                    auto c_29 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 25, true);
                    {
                        auto c_30 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_31 = new CalfLabel(this, *meta.get_param_props(_resolve("oversampling")), _resolve("oversampling"), nullptr);
                        fWidgets.emplace_back(w_31);
                        fByIndex[_resolve("oversampling")].push_back(w_31);
                        c_30->add(std::make_unique<CalfWidgetItem>(w_31), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_32 = new CalfKnob(this, *meta.get_param_props(_resolve("oversampling")), _resolve("oversampling"));
                        w_32->setKnobSize(3);
                        w_32->setShowLabels(false);
                        fWidgets.emplace_back(w_32);
                        fByIndex[_resolve("oversampling")].push_back(w_32);
                        c_30->add(std::make_unique<CalfWidgetItem>(w_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_33 = new CalfValue(this, *meta.get_param_props(_resolve("oversampling")), _resolve("oversampling"));
                        fWidgets.emplace_back(w_33);
                        fByIndex[_resolve("oversampling")].push_back(w_33);
                        c_30->add(std::make_unique<CalfWidgetItem>(w_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_29->add(std::move(c_30), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_34 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_35 = new CalfLabel(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"), nullptr);
                        fWidgets.emplace_back(w_35);
                        fByIndex[_resolve("attack")].push_back(w_35);
                        c_34->add(std::make_unique<CalfWidgetItem>(w_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_36 = new CalfKnob(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"));
                        w_36->setKnobSize(3);
                        w_36->setShowLabels(false);
                        fWidgets.emplace_back(w_36);
                        fByIndex[_resolve("attack")].push_back(w_36);
                        c_34->add(std::make_unique<CalfWidgetItem>(w_36), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_37 = new CalfValue(this, *meta.get_param_props(_resolve("attack")), _resolve("attack"));
                        fWidgets.emplace_back(w_37);
                        fByIndex[_resolve("attack")].push_back(w_37);
                        c_34->add(std::make_unique<CalfWidgetItem>(w_37), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_29->add(std::move(c_34), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_38 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_39 = new CalfLabel(this, *meta.get_param_props(_resolve("limit")), _resolve("limit"), nullptr);
                        fWidgets.emplace_back(w_39);
                        fByIndex[_resolve("limit")].push_back(w_39);
                        c_38->add(std::make_unique<CalfWidgetItem>(w_39), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_40 = new CalfKnob(this, *meta.get_param_props(_resolve("limit")), _resolve("limit"));
                        w_40->setKnobSize(5);
                        w_40->setShowLabels(false);
                        fWidgets.emplace_back(w_40);
                        fByIndex[_resolve("limit")].push_back(w_40);
                        c_38->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_41 = new CalfValue(this, *meta.get_param_props(_resolve("limit")), _resolve("limit"));
                        fWidgets.emplace_back(w_41);
                        fByIndex[_resolve("limit")].push_back(w_41);
                        c_38->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_29->add(std::move(c_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_42 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_43 = new CalfLabel(this, *meta.get_param_props(_resolve("release")), _resolve("release"), nullptr);
                        fWidgets.emplace_back(w_43);
                        fByIndex[_resolve("release")].push_back(w_43);
                        c_42->add(std::make_unique<CalfWidgetItem>(w_43), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_44 = new CalfKnob(this, *meta.get_param_props(_resolve("release")), _resolve("release"));
                        w_44->setKnobSize(3);
                        w_44->setShowLabels(false);
                        fWidgets.emplace_back(w_44);
                        fByIndex[_resolve("release")].push_back(w_44);
                        c_42->add(std::make_unique<CalfWidgetItem>(w_44), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        auto* w_45 = new CalfValue(this, *meta.get_param_props(_resolve("release")), _resolve("release"));
                        fWidgets.emplace_back(w_45);
                        fByIndex[_resolve("release")].push_back(w_45);
                        c_42->add(std::make_unique<CalfWidgetItem>(w_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        c_29->add(std::move(c_42), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_46 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        auto* w_47 = new CalfLabel(this, *meta.get_param_props(_resolve("asc")), _resolve("asc"), nullptr);
                        fWidgets.emplace_back(w_47);
                        fByIndex[_resolve("asc")].push_back(w_47);
                        c_46->add(std::make_unique<CalfWidgetItem>(w_47), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        {
                            auto c_49 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_50 = new CalfToggle(this, *meta.get_param_props(_resolve("asc")), _resolve("asc"));
                            w_50->setShowLabels(false);
                            fWidgets.emplace_back(w_50);
                            fByIndex[_resolve("asc")].push_back(w_50);
                            c_49->add(std::make_unique<CalfWidgetItem>(w_50), CalfPacking{});
                            auto c_48 = std::make_unique<CalfAlignItem>(std::move(c_49), 0.5f, 0.5f, 0.0f, 0.0f);
                            c_46->add(std::move(c_48), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_52 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            {
                                auto c_53 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 8, false);
                                auto* w_54 = new CalfKnob(this, *meta.get_param_props(_resolve("asc_coeff")), _resolve("asc_coeff"));
                                w_54->setKnobSize(1);
                                w_54->setShowLabels(false);
                                fWidgets.emplace_back(w_54);
                                fByIndex[_resolve("asc_coeff")].push_back(w_54);
                                c_53->add(std::make_unique<CalfWidgetItem>(w_54), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                {
                                    auto c_56 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                                    auto* w_57 = new CalfLed(this, *meta.get_param_props(_resolve("asc_led")), _resolve("asc_led"));
                                    w_57->setShowLabels(false);
                                    fWidgets.emplace_back(w_57);
                                    fByIndex[_resolve("asc_led")].push_back(w_57);
                                    c_56->add(std::make_unique<CalfWidgetItem>(w_57), CalfPacking{});
                                    auto c_55 = std::make_unique<CalfAlignItem>(std::move(c_56), 0.5f, 0.5f, 0.0f, 0.0f);
                                    c_53->add(std::move(c_55), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                                }
                                c_52->add(std::move(c_53), CalfPacking{});
                            }
                            auto c_51 = std::make_unique<CalfAlignItem>(std::move(c_52), 0.5f, 0.5f, 0.0f, 0.0f);
                            c_46->add(std::move(c_51), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        c_29->add(std::move(c_46), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_28->add(std::move(c_29), CalfPacking{});
                }
                auto c_27 = std::make_unique<CalfFrameItem>("Limit", std::move(c_28));
                c_1->add(std::move(c_27), CalfPacking{.expandX=false, .expandY=false, .fillX=true, .fillY=true, .attachY=1});
            }
            {
                auto c_59 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                auto* w_60 = new CalfVuMeter(this, *meta.get_param_props(_resolve("att")), _resolve("att"));
                w_60->setShowLabels(false);
                fWidgets.emplace_back(w_60);
                fByIndex[_resolve("att")].push_back(w_60);
                c_59->add(std::make_unique<CalfWidgetItem>(w_60), CalfPacking{});
                auto c_58 = std::make_unique<CalfFrameItem>("Attenuation", std::move(c_59));
                c_1->add(std::move(c_58), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=2});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);

        // Shadow module: same DSP class as the running plugin, instantiated
        // UI-side just so <line-graph> widgets can query line_graph_iface
        // synchronously during paint.
        fShadow = std::make_unique<calf_plugins::limiter_audio_module>();
        fShadowParams.assign(Meta::param_count, 0.0f);
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            fShadowParams[i] = meta.get_param_props(static_cast<int>(i))->def_value;
            fShadow->params[i] = &fShadowParams[i];
        }
        fShadow->post_instantiate(48000);
        fShadow->set_sample_rate(48000);
        fShadow->params_changed();
        fShadow->activate();
        // Not every Calf module inherits line_graph_iface — only the
        // ones that draw curves do. Cross-cast at runtime; null means
        // "this plugin has no curves to draw, paint the placeholder".
        const calf_plugins::line_graph_iface* _lg =
            dynamic_cast<const calf_plugins::line_graph_iface*>(fShadow.get());
        if (_lg) {
            for (auto& g : fLineGraphs)
                g.w->setGraphSource(_lg, g.idx);
        }
    }

protected:
    void onNanoDisplay() override
    {
        const float w = static_cast<float>(getWidth());
        const float h = static_cast<float>(getHeight());

        // Themed background: stretch the GTK Calf_Default plugin
        // background across the whole UI. Falls back to the dark flat
        // fill if the asset failed to decode.
        beginPath();
        rect(0, 0, w, h);
        NanoImage* _bg = fTheme.image("background_plugin.png");
        if (_bg && _bg->isValid()) {
            fillPaint(imagePattern(0, 0, w, h, 0.0f, *_bg, 1.0f));
        } else {
            fillColor(Color(0.12f, 0.12f, 0.14f));
        }
        fill();

        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it != fByIndex.end())
            for (auto* w : it->second) w->setValue(value, /*notify=*/false);
        if (fShadow && index < fShadowParams.size()) {
            fShadowParams[index] = value;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
        if (fShadow && w->getParamIndex() < fShadowParams.size()) {
            fShadowParams[w->getParamIndex()] = v;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    // No-op for WANT_STATE plugins (Monosynth, Organ, FluidSynth, Wavetable).
    // Codegen UIs don't yet visualise state keys (organ presets, wavetable
    // data, SF2 path, modmatrix rows); hand-written subclasses can override.
    // DPF only declares stateChanged when the plugin opts in, so guard.
#if DISTRHO_PLUGIN_WANT_STATE
    void stateChanged(const char* /*key*/, const char* /*value*/) override {}
#endif

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    CalfTheme                                         fTheme{*this};
    std::unique_ptr<calf_plugins::limiter_audio_module> fShadow;
    std::vector<float>                            fShadowParams;
    struct LineGraphRef { CalfLineGraph* w; int idx; };
    std::vector<LineGraphRef>                     fLineGraphs;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(LimiterUI)
};

UI* createUI() { return new LimiterUI(); }

END_NAMESPACE_DISTRHO
