/*
 * Generated by calf-dpf/tools/xml2ui.py from gui/gui/multichorus.xml.
 * Do not edit by hand — re-run the codegen.
 */
#include "DistrhoUI.hpp"
#include "CalfLayout.hpp"
#include "CalfKnob.hpp"
#include "CalfLabel.hpp"
#include "CalfLed.hpp"
#include "CalfLineGraph.hpp"
#include "CalfToggle.hpp"
#include "CalfValue.hpp"
#include "CalfVuMeter.hpp"
#include <calf/metadata.h>
#ifndef ENABLE_EXPERIMENTAL
#define ENABLE_EXPERIMENTAL 1
#endif
#include <calf/modules_mod.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

START_NAMESPACE_DISTRHO

using DGL_NAMESPACE::CalfAlignItem;
using DGL_NAMESPACE::CalfBoxItem;
using DGL_NAMESPACE::CalfFrameItem;
using DGL_NAMESPACE::CalfKnob;
using DGL_NAMESPACE::CalfLabel;
using DGL_NAMESPACE::CalfLayoutItem;
using DGL_NAMESPACE::CalfLed;
using DGL_NAMESPACE::CalfLineGraph;
using DGL_NAMESPACE::CalfPacking;
using DGL_NAMESPACE::CalfTableItem;
using DGL_NAMESPACE::CalfToggle;
using DGL_NAMESPACE::CalfValue;
using DGL_NAMESPACE::CalfVuMeter;
using DGL_NAMESPACE::CalfWidgetBase;
using DGL_NAMESPACE::CalfWidgetItem;

class MultichorusUI : public UI, public CalfWidgetBase::Callback
{
public:
    MultichorusUI() : UI(640, 400)
    {
        loadSharedResources();
        using namespace calf_plugins;
        using Meta = multichorus_metadata;
        Meta meta;

        std::map<std::string, uint32_t> _byName;
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            const parameter_properties* pp = meta.get_param_props(static_cast<int>(i));
            if (pp && pp->short_name) _byName[pp->short_name] = i;
        }
        auto _resolve = [&](const char* n) -> uint32_t {
            auto it = _byName.find(n);
            return it == _byName.end() ? 0u : it->second;
        };

        std::unique_ptr<CalfLayoutItem> _root;
        {
            auto c_1 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
            {
                auto c_2 = std::make_unique<CalfTableItem>(1, 7, false, 5, 5);
                auto* w_3 = new CalfLabel(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"), nullptr);
                fWidgets.emplace_back(w_3);
                fByIndex[_resolve("level_in")].push_back(w_3);
                c_2->add(std::make_unique<CalfWidgetItem>(w_3), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true});
                auto* w_4 = new CalfKnob(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                w_4->setShowLabels(false);
                fWidgets.emplace_back(w_4);
                fByIndex[_resolve("level_in")].push_back(w_4);
                c_2->add(std::make_unique<CalfWidgetItem>(w_4), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=1, .attachH=2});
                auto* w_5 = new CalfValue(this, *meta.get_param_props(_resolve("level_in")), _resolve("level_in"));
                fWidgets.emplace_back(w_5);
                fByIndex[_resolve("level_in")].push_back(w_5);
                c_2->add(std::make_unique<CalfWidgetItem>(w_5), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachY=3});
                auto* w_6 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Input level");
                fWidgets.emplace_back(w_6);
                c_2->add(std::make_unique<CalfWidgetItem>(w_6), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                auto* w_7 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inL")), _resolve("meter_inL"));
                w_7->setShowLabels(false);
                fWidgets.emplace_back(w_7);
                fByIndex[_resolve("meter_inL")].push_back(w_7);
                c_2->add(std::make_unique<CalfWidgetItem>(w_7), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                auto* w_8 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_inR")), _resolve("meter_inR"));
                w_8->setShowLabels(false);
                fWidgets.emplace_back(w_8);
                fByIndex[_resolve("meter_inR")].push_back(w_8);
                c_2->add(std::make_unique<CalfWidgetItem>(w_8), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=2});
                auto* w_9 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_9);
                fByIndex[_resolve("meter_outR")].push_back(w_9);
                c_2->add(std::make_unique<CalfWidgetItem>(w_9), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=3});
                auto* w_10 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_10);
                c_2->add(std::make_unique<CalfWidgetItem>(w_10), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                auto* w_11 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inL")), _resolve("clip_inL"));
                w_11->setShowLabels(false);
                fWidgets.emplace_back(w_11);
                fByIndex[_resolve("clip_inL")].push_back(w_11);
                c_2->add(std::make_unique<CalfWidgetItem>(w_11), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=1});
                auto* w_12 = new CalfLed(this, *meta.get_param_props(_resolve("clip_inR")), _resolve("clip_inR"));
                w_12->setShowLabels(false);
                fWidgets.emplace_back(w_12);
                fByIndex[_resolve("clip_inR")].push_back(w_12);
                c_2->add(std::make_unique<CalfWidgetItem>(w_12), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=2, .attachY=2});
                auto* w_13 = new CalfLabel(this, *meta.get_param_props(_resolve("on")), _resolve("on"), nullptr);
                fWidgets.emplace_back(w_13);
                fByIndex[_resolve("on")].push_back(w_13);
                c_2->add(std::make_unique<CalfWidgetItem>(w_13), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=3});
                auto* w_14 = new CalfToggle(this, *meta.get_param_props(_resolve("on")), _resolve("on"));
                w_14->setShowLabels(false);
                fWidgets.emplace_back(w_14);
                fByIndex[_resolve("on")].push_back(w_14);
                c_2->add(std::make_unique<CalfWidgetItem>(w_14), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=3, .attachY=1, .attachH=2});
                auto* w_15 = new CalfLabel(this, *meta.get_param_props(_resolve("lfo")), _resolve("lfo"), nullptr);
                fWidgets.emplace_back(w_15);
                fByIndex[_resolve("lfo")].push_back(w_15);
                c_2->add(std::make_unique<CalfWidgetItem>(w_15), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=4});
                auto* w_16 = new CalfToggle(this, *meta.get_param_props(_resolve("lfo")), _resolve("lfo"));
                w_16->setShowLabels(false);
                fWidgets.emplace_back(w_16);
                fByIndex[_resolve("lfo")].push_back(w_16);
                c_2->add(std::make_unique<CalfWidgetItem>(w_16), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=4, .attachY=1, .attachH=2});
                auto* w_17 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Output level");
                fWidgets.emplace_back(w_17);
                c_2->add(std::make_unique<CalfWidgetItem>(w_17), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5});
                auto* w_18 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outL")), _resolve("meter_outL"));
                w_18->setShowLabels(false);
                fWidgets.emplace_back(w_18);
                fByIndex[_resolve("meter_outL")].push_back(w_18);
                c_2->add(std::make_unique<CalfWidgetItem>(w_18), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=1});
                auto* w_19 = new CalfVuMeter(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                w_19->setShowLabels(false);
                fWidgets.emplace_back(w_19);
                fByIndex[_resolve("meter_outR")].push_back(w_19);
                c_2->add(std::make_unique<CalfWidgetItem>(w_19), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=2});
                auto* w_20 = new CalfLabel(this, *meta.get_param_props(_resolve("meter_outR")), _resolve("meter_outR"));
                fWidgets.emplace_back(w_20);
                fByIndex[_resolve("meter_outR")].push_back(w_20);
                c_2->add(std::make_unique<CalfWidgetItem>(w_20), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=5, .attachY=3});
                auto* w_21 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "Clip");
                fWidgets.emplace_back(w_21);
                c_2->add(std::make_unique<CalfWidgetItem>(w_21), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6});
                auto* w_22 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outL")), _resolve("clip_outL"));
                w_22->setShowLabels(false);
                fWidgets.emplace_back(w_22);
                fByIndex[_resolve("clip_outL")].push_back(w_22);
                c_2->add(std::make_unique<CalfWidgetItem>(w_22), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=1});
                auto* w_23 = new CalfLed(this, *meta.get_param_props(_resolve("clip_outR")), _resolve("clip_outR"));
                w_23->setShowLabels(false);
                fWidgets.emplace_back(w_23);
                fByIndex[_resolve("clip_outR")].push_back(w_23);
                c_2->add(std::make_unique<CalfWidgetItem>(w_23), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=6, .attachY=2});
                auto* w_24 = new CalfLabel(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"), nullptr);
                fWidgets.emplace_back(w_24);
                fByIndex[_resolve("level_out")].push_back(w_24);
                c_2->add(std::make_unique<CalfWidgetItem>(w_24), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=7});
                auto* w_25 = new CalfKnob(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                w_25->setShowLabels(false);
                fWidgets.emplace_back(w_25);
                fByIndex[_resolve("level_out")].push_back(w_25);
                c_2->add(std::make_unique<CalfWidgetItem>(w_25), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=7, .attachY=1, .attachH=2});
                auto* w_26 = new CalfValue(this, *meta.get_param_props(_resolve("level_out")), _resolve("level_out"));
                fWidgets.emplace_back(w_26);
                fByIndex[_resolve("level_out")].push_back(w_26);
                c_2->add(std::make_unique<CalfWidgetItem>(w_26), CalfPacking{.expandX=false, .expandY=true, .fillX=true, .fillY=true, .attachX=7, .attachY=3});
                c_1->add(std::move(c_2), CalfPacking{.expandX=true, .expandY=false, .fillX=true, .fillY=true});
            }
            {
                auto c_27 = std::make_unique<CalfTableItem>(2, 3, false, 0, 0);
                {
                    auto c_29 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_30 = std::make_unique<CalfTableItem>(1, 5, true, 0, 0);
                        {
                            auto c_31 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_32 = new CalfLabel(this, *meta.get_param_props(_resolve("min_delay")), _resolve("min_delay"), nullptr);
                            fWidgets.emplace_back(w_32);
                            fByIndex[_resolve("min_delay")].push_back(w_32);
                            c_31->add(std::make_unique<CalfWidgetItem>(w_32), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_33 = new CalfKnob(this, *meta.get_param_props(_resolve("min_delay")), _resolve("min_delay"));
                            w_33->setShowLabels(false);
                            fWidgets.emplace_back(w_33);
                            fByIndex[_resolve("min_delay")].push_back(w_33);
                            c_31->add(std::make_unique<CalfWidgetItem>(w_33), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_34 = new CalfValue(this, *meta.get_param_props(_resolve("min_delay")), _resolve("min_delay"));
                            fWidgets.emplace_back(w_34);
                            fByIndex[_resolve("min_delay")].push_back(w_34);
                            c_31->add(std::make_unique<CalfWidgetItem>(w_34), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_30->add(std::move(c_31), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_35 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_36 = new CalfLabel(this, *meta.get_param_props(_resolve("mod_depth")), _resolve("mod_depth"), nullptr);
                            fWidgets.emplace_back(w_36);
                            fByIndex[_resolve("mod_depth")].push_back(w_36);
                            c_35->add(std::make_unique<CalfWidgetItem>(w_36), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_37 = new CalfKnob(this, *meta.get_param_props(_resolve("mod_depth")), _resolve("mod_depth"));
                            w_37->setShowLabels(false);
                            fWidgets.emplace_back(w_37);
                            fByIndex[_resolve("mod_depth")].push_back(w_37);
                            c_35->add(std::make_unique<CalfWidgetItem>(w_37), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_38 = new CalfValue(this, *meta.get_param_props(_resolve("mod_depth")), _resolve("mod_depth"));
                            fWidgets.emplace_back(w_38);
                            fByIndex[_resolve("mod_depth")].push_back(w_38);
                            c_35->add(std::make_unique<CalfWidgetItem>(w_38), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_30->add(std::move(c_35), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                        }
                        {
                            auto c_39 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_40 = new CalfLabel(this, *meta.get_param_props(_resolve("mod_rate")), _resolve("mod_rate"), nullptr);
                            fWidgets.emplace_back(w_40);
                            fByIndex[_resolve("mod_rate")].push_back(w_40);
                            c_39->add(std::make_unique<CalfWidgetItem>(w_40), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_41 = new CalfKnob(this, *meta.get_param_props(_resolve("mod_rate")), _resolve("mod_rate"));
                            w_41->setShowLabels(false);
                            fWidgets.emplace_back(w_41);
                            fByIndex[_resolve("mod_rate")].push_back(w_41);
                            c_39->add(std::make_unique<CalfWidgetItem>(w_41), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_42 = new CalfValue(this, *meta.get_param_props(_resolve("mod_rate")), _resolve("mod_rate"));
                            fWidgets.emplace_back(w_42);
                            fByIndex[_resolve("mod_rate")].push_back(w_42);
                            c_39->add(std::make_unique<CalfWidgetItem>(w_42), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_30->add(std::move(c_39), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                        }
                        {
                            auto c_43 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_44 = new CalfLabel(this, *meta.get_param_props(_resolve("dry")), _resolve("dry"), nullptr);
                            fWidgets.emplace_back(w_44);
                            fByIndex[_resolve("dry")].push_back(w_44);
                            c_43->add(std::make_unique<CalfWidgetItem>(w_44), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_45 = new CalfKnob(this, *meta.get_param_props(_resolve("dry")), _resolve("dry"));
                            w_45->setShowLabels(false);
                            fWidgets.emplace_back(w_45);
                            fByIndex[_resolve("dry")].push_back(w_45);
                            c_43->add(std::make_unique<CalfWidgetItem>(w_45), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_46 = new CalfValue(this, *meta.get_param_props(_resolve("dry")), _resolve("dry"));
                            fWidgets.emplace_back(w_46);
                            fByIndex[_resolve("dry")].push_back(w_46);
                            c_43->add(std::make_unique<CalfWidgetItem>(w_46), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_30->add(std::move(c_43), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=3});
                        }
                        {
                            auto c_47 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_48 = new CalfLabel(this, *meta.get_param_props(_resolve("amount")), _resolve("amount"), nullptr);
                            fWidgets.emplace_back(w_48);
                            fByIndex[_resolve("amount")].push_back(w_48);
                            c_47->add(std::make_unique<CalfWidgetItem>(w_48), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_49 = new CalfKnob(this, *meta.get_param_props(_resolve("amount")), _resolve("amount"));
                            w_49->setShowLabels(false);
                            fWidgets.emplace_back(w_49);
                            fByIndex[_resolve("amount")].push_back(w_49);
                            c_47->add(std::make_unique<CalfWidgetItem>(w_49), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_50 = new CalfValue(this, *meta.get_param_props(_resolve("amount")), _resolve("amount"));
                            fWidgets.emplace_back(w_50);
                            fByIndex[_resolve("amount")].push_back(w_50);
                            c_47->add(std::make_unique<CalfWidgetItem>(w_50), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_30->add(std::move(c_47), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=4});
                        }
                        c_29->add(std::move(c_30), CalfPacking{});
                    }
                    auto c_28 = std::make_unique<CalfFrameItem>("Timbre", std::move(c_29));
                    c_27->add(std::move(c_28), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                }
                {
                    auto c_52 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_53 = std::make_unique<CalfTableItem>(2, 2, true, 10, 10);
                        {
                            auto c_54 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_55 = new CalfLabel(this, *meta.get_param_props(_resolve("overlap")), _resolve("overlap"), nullptr);
                            fWidgets.emplace_back(w_55);
                            fByIndex[_resolve("overlap")].push_back(w_55);
                            c_54->add(std::make_unique<CalfWidgetItem>(w_55), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_56 = new CalfKnob(this, *meta.get_param_props(_resolve("overlap")), _resolve("overlap"));
                            w_56->setShowLabels(false);
                            fWidgets.emplace_back(w_56);
                            fByIndex[_resolve("overlap")].push_back(w_56);
                            c_54->add(std::make_unique<CalfWidgetItem>(w_56), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_57 = new CalfValue(this, *meta.get_param_props(_resolve("overlap")), _resolve("overlap"));
                            fWidgets.emplace_back(w_57);
                            fByIndex[_resolve("overlap")].push_back(w_57);
                            c_54->add(std::make_unique<CalfWidgetItem>(w_57), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_53->add(std::move(c_54), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_58 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_59 = new CalfLabel(this, *meta.get_param_props(_resolve("voices")), _resolve("voices"), nullptr);
                            fWidgets.emplace_back(w_59);
                            fByIndex[_resolve("voices")].push_back(w_59);
                            c_58->add(std::make_unique<CalfWidgetItem>(w_59), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_60 = new CalfKnob(this, *meta.get_param_props(_resolve("voices")), _resolve("voices"));
                            w_60->setShowLabels(false);
                            fWidgets.emplace_back(w_60);
                            fByIndex[_resolve("voices")].push_back(w_60);
                            c_58->add(std::make_unique<CalfWidgetItem>(w_60), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_61 = new CalfValue(this, *meta.get_param_props(_resolve("voices")), _resolve("voices"));
                            fWidgets.emplace_back(w_61);
                            fByIndex[_resolve("voices")].push_back(w_61);
                            c_58->add(std::make_unique<CalfWidgetItem>(w_61), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_53->add(std::move(c_58), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                        }
                        {
                            auto c_62 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_63 = new CalfLabel(this, *meta.get_param_props(_resolve("stereo")), _resolve("stereo"), nullptr);
                            fWidgets.emplace_back(w_63);
                            fByIndex[_resolve("stereo")].push_back(w_63);
                            c_62->add(std::make_unique<CalfWidgetItem>(w_63), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_64 = new CalfKnob(this, *meta.get_param_props(_resolve("stereo")), _resolve("stereo"));
                            w_64->setShowLabels(false);
                            fWidgets.emplace_back(w_64);
                            fByIndex[_resolve("stereo")].push_back(w_64);
                            c_62->add(std::make_unique<CalfWidgetItem>(w_64), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_65 = new CalfValue(this, *meta.get_param_props(_resolve("stereo")), _resolve("stereo"));
                            fWidgets.emplace_back(w_65);
                            fByIndex[_resolve("stereo")].push_back(w_65);
                            c_62->add(std::make_unique<CalfWidgetItem>(w_65), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_53->add(std::move(c_62), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachY=1});
                        }
                        {
                            auto c_66 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_67 = new CalfLabel(this, *meta.get_param_props(_resolve("vphase")), _resolve("vphase"), nullptr);
                            fWidgets.emplace_back(w_67);
                            fByIndex[_resolve("vphase")].push_back(w_67);
                            c_66->add(std::make_unique<CalfWidgetItem>(w_67), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_68 = new CalfKnob(this, *meta.get_param_props(_resolve("vphase")), _resolve("vphase"));
                            w_68->setShowLabels(false);
                            fWidgets.emplace_back(w_68);
                            fByIndex[_resolve("vphase")].push_back(w_68);
                            c_66->add(std::make_unique<CalfWidgetItem>(w_68), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_69 = new CalfValue(this, *meta.get_param_props(_resolve("vphase")), _resolve("vphase"));
                            fWidgets.emplace_back(w_69);
                            fByIndex[_resolve("vphase")].push_back(w_69);
                            c_66->add(std::make_unique<CalfWidgetItem>(w_69), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_53->add(std::move(c_66), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1, .attachY=1});
                        }
                        c_52->add(std::move(c_53), CalfPacking{});
                    }
                    auto c_51 = std::make_unique<CalfFrameItem>("LFO", std::move(c_52));
                    c_27->add(std::move(c_51), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .padX=8, .attachX=1});
                }
                {
                    auto c_71 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                    {
                        auto c_72 = std::make_unique<CalfTableItem>(1, 3, false, 10, 10);
                        {
                            auto c_73 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_74 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "HP");
                            fWidgets.emplace_back(w_74);
                            c_73->add(std::make_unique<CalfWidgetItem>(w_74), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_75 = new CalfKnob(this, *meta.get_param_props(_resolve("freq")), _resolve("freq"));
                            w_75->setShowLabels(false);
                            fWidgets.emplace_back(w_75);
                            fByIndex[_resolve("freq")].push_back(w_75);
                            c_73->add(std::make_unique<CalfWidgetItem>(w_75), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_76 = new CalfValue(this, *meta.get_param_props(_resolve("freq")), _resolve("freq"));
                            fWidgets.emplace_back(w_76);
                            fByIndex[_resolve("freq")].push_back(w_76);
                            c_73->add(std::make_unique<CalfWidgetItem>(w_76), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_72->add(std::move(c_73), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                        }
                        {
                            auto c_77 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_78 = new CalfLabel(this, *meta.get_param_props(_resolve("q")), _resolve("q"), nullptr);
                            fWidgets.emplace_back(w_78);
                            fByIndex[_resolve("q")].push_back(w_78);
                            c_77->add(std::make_unique<CalfWidgetItem>(w_78), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_79 = new CalfKnob(this, *meta.get_param_props(_resolve("q")), _resolve("q"));
                            w_79->setShowLabels(false);
                            fWidgets.emplace_back(w_79);
                            fByIndex[_resolve("q")].push_back(w_79);
                            c_77->add(std::make_unique<CalfWidgetItem>(w_79), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_80 = new CalfValue(this, *meta.get_param_props(_resolve("q")), _resolve("q"));
                            fWidgets.emplace_back(w_80);
                            fByIndex[_resolve("q")].push_back(w_80);
                            c_77->add(std::make_unique<CalfWidgetItem>(w_80), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_72->add(std::move(c_77), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=1});
                        }
                        {
                            auto c_81 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_82 = new CalfLabel(this, *meta.get_param_props(0u), 0u, "LP");
                            fWidgets.emplace_back(w_82);
                            c_81->add(std::make_unique<CalfWidgetItem>(w_82), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_83 = new CalfKnob(this, *meta.get_param_props(_resolve("freq2")), _resolve("freq2"));
                            w_83->setShowLabels(false);
                            fWidgets.emplace_back(w_83);
                            fByIndex[_resolve("freq2")].push_back(w_83);
                            c_81->add(std::make_unique<CalfWidgetItem>(w_83), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_84 = new CalfValue(this, *meta.get_param_props(_resolve("freq2")), _resolve("freq2"));
                            fWidgets.emplace_back(w_84);
                            fByIndex[_resolve("freq2")].push_back(w_84);
                            c_81->add(std::make_unique<CalfWidgetItem>(w_84), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_72->add(std::move(c_81), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .attachX=2});
                        }
                        c_71->add(std::move(c_72), CalfPacking{});
                    }
                    auto c_70 = std::make_unique<CalfFrameItem>("Post Filter", std::move(c_71));
                    c_27->add(std::move(c_70), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true, .padX=8, .attachX=1, .attachY=1});
                }
                {
                    auto c_85 = std::make_unique<CalfBoxItem>(CalfBoxItem::HORIZONTAL, 8, false);
                    {
                        auto c_87 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        {
                            auto c_88 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                            auto* w_89 = new CalfLineGraph(this, *meta.get_param_props(_resolve("min_delay")), _resolve("min_delay"), 240, 166);
                            fLineGraphs.push_back({ w_89, static_cast<int>(_resolve("min_delay")) });
                            w_89->setSize(static_cast<uint>(240), static_cast<uint>(166));
                            fWidgets.emplace_back(w_89);
                            fByIndex[_resolve("min_delay")].push_back(w_89);
                            c_88->add(std::make_unique<CalfWidgetItem>(w_89), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_87->add(std::move(c_88), CalfPacking{});
                        }
                        auto c_86 = std::make_unique<CalfFrameItem>("Freq. response", std::move(c_87));
                        c_85->add(std::move(c_86), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    {
                        auto c_91 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 0, false);
                        {
                            auto c_92 = std::make_unique<CalfBoxItem>(CalfBoxItem::VERTICAL, 6, false);
                            auto* w_93 = new CalfLineGraph(this, *meta.get_param_props(_resolve("mod_depth")), _resolve("mod_depth"), 240, 20);
                            fLineGraphs.push_back({ w_93, static_cast<int>(_resolve("mod_depth")) });
                            w_93->setSize(static_cast<uint>(240), static_cast<uint>(20));
                            fWidgets.emplace_back(w_93);
                            fByIndex[_resolve("mod_depth")].push_back(w_93);
                            c_92->add(std::make_unique<CalfWidgetItem>(w_93), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            auto* w_94 = new CalfLineGraph(this, *meta.get_param_props(_resolve("mod_rate")), _resolve("mod_rate"), 240, 140);
                            fLineGraphs.push_back({ w_94, static_cast<int>(_resolve("mod_rate")) });
                            w_94->setSize(static_cast<uint>(240), static_cast<uint>(140));
                            fWidgets.emplace_back(w_94);
                            fByIndex[_resolve("mod_rate")].push_back(w_94);
                            c_92->add(std::make_unique<CalfWidgetItem>(w_94), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                            c_91->add(std::move(c_92), CalfPacking{});
                        }
                        auto c_90 = std::make_unique<CalfFrameItem>("LFO positions", std::move(c_91));
                        c_85->add(std::move(c_90), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                    }
                    c_27->add(std::move(c_85), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
                }
                c_1->add(std::move(c_27), CalfPacking{.expandX=true, .expandY=true, .fillX=true, .fillY=true});
            }
            _root = std::move(c_1);
        }

        for (auto& w : fWidgets) w->setCallback(this);
        if (_root) {
            const int W = std::max(320, _root->minW());
            const int H = std::max(240, _root->minH());
            setSize(static_cast<uint>(W), static_cast<uint>(H));
            _root->place(0, 0, W, H);
        }
        fRoot = std::move(_root);

        // Shadow module: same DSP class as the running plugin, instantiated
        // UI-side just so <line-graph> widgets can query line_graph_iface
        // synchronously during paint.
        fShadow = std::make_unique<calf_plugins::multichorus_audio_module>();
        fShadowParams.assign(Meta::param_count, 0.0f);
        for (uint32_t i = 0; i < Meta::param_count; ++i) {
            fShadowParams[i] = meta.get_param_props(static_cast<int>(i))->def_value;
            fShadow->params[i] = &fShadowParams[i];
        }
        fShadow->post_instantiate(48000);
        fShadow->set_sample_rate(48000);
        fShadow->params_changed();
        fShadow->activate();
        // Not every Calf module inherits line_graph_iface — only the
        // ones that draw curves do. Cross-cast at runtime; null means
        // "this plugin has no curves to draw, paint the placeholder".
        const calf_plugins::line_graph_iface* _lg =
            dynamic_cast<const calf_plugins::line_graph_iface*>(fShadow.get());
        if (_lg) {
            for (auto& g : fLineGraphs)
                g.w->setGraphSource(_lg, g.idx);
        }
    }

protected:
    void onNanoDisplay() override
    {
        beginPath();
        rect(0, 0, getWidth(), getHeight());
        fillColor(Color(0.12f, 0.12f, 0.14f));
        fill();
        if (fRoot) fRoot->draw(*this);
    }

    void parameterChanged(uint32_t index, float value) override
    {
        auto it = fByIndex.find(index);
        if (it != fByIndex.end())
            for (auto* w : it->second) w->setValue(value, /*notify=*/false);
        if (fShadow && index < fShadowParams.size()) {
            fShadowParams[index] = value;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    void widgetValueChanged(CalfWidgetBase* w, float v) override
    {
        editParameter(w->getParamIndex(), true);
        setParameterValue(w->getParamIndex(), v);
        editParameter(w->getParamIndex(), false);
        if (fShadow && w->getParamIndex() < fShadowParams.size()) {
            fShadowParams[w->getParamIndex()] = v;
            fShadow->params_changed();
            for (auto& g : fLineGraphs) g.w->refresh();
        }
    }

    // No-op for WANT_STATE plugins (Monosynth, Organ, FluidSynth, Wavetable).
    // Codegen UIs don't yet visualise state keys (organ presets, wavetable
    // data, SF2 path, modmatrix rows); hand-written subclasses can override.
    // DPF only declares stateChanged when the plugin opts in, so guard.
#if DISTRHO_PLUGIN_WANT_STATE
    void stateChanged(const char* /*key*/, const char* /*value*/) override {}
#endif

private:
    std::vector<std::unique_ptr<CalfWidgetBase>>      fWidgets;
    std::map<uint32_t, std::vector<CalfWidgetBase*>>  fByIndex;
    std::unique_ptr<CalfLayoutItem>                   fRoot;
    std::unique_ptr<calf_plugins::multichorus_audio_module> fShadow;
    std::vector<float>                            fShadowParams;
    struct LineGraphRef { CalfLineGraph* w; int idx; };
    std::vector<LineGraphRef>                     fLineGraphs;
    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(MultichorusUI)
};

UI* createUI() { return new MultichorusUI(); }

END_NAMESPACE_DISTRHO
